# **Kalshi MLB Player Prop Market Analysis**


### Section 1: Preprocessing

- Data cleaning and preparation


### Section 2: Dependent & Independent Variable Creation

- Engineering dependent and independent variables 


### Section 3: Analysis

- Market analysis

- Pre-Game Implied Outcome Probability vs. Hit Rate

- Multivariable Regression Analysis

In [82]:
import numpy as np
from utils import *
import pandas as pd

In [83]:
SERIES_TICKERS = {
    "homeruns"         : "KXMLBHR",    # MLB: 'Rafael Devers records n+ home runs in a game'
    "strikeouts"       : "KXMLBKS",    # MLB: 'Logan Webb records n+ strikeouts in a game'
    "hits"             : "KXMLBHIT",   # MLB: 'Luis Arráez records n+ hits in a game'
    "hits_runs_rbi"    : "KXMLBHRR",   # MLB: 'Matt Chapman records n+ combined hits, runs, or RBIs in a game'
    "total_bases"      : "KXMLBTB",    # MLB: 'Willy Adames records n+ total bases in a game'
    "outs"             : "KXMLBOUTS",  # MLB: 'Logan Webb records n+ total outs in a game'
    "rbi"              : "KXMLBRBI",   # MLB: 'Heliot Ramos records n+ total RBIs in a game'
    "stolen_bases"     : "KXMLBSB",    # MLB: 'Jung Hoo Lee records n+ stolen bases in a game'
}

KALSHI_MAKER_FEE: float = 0.0175          # Kalshi maker fee for June 2026
KALSHI_TAKER_FEE: float = 0.07            # Kalshi taker fee for June 2026

# Preprocessing

### Preprocessing - Market Data

In [84]:
# Load in data

recent_markets_df = pd.read_parquet('data/raw/recent_markets.parquet')
historical_markets_df = pd.read_parquet('data/raw/historical_markets.parquet')

In [85]:
recent_markets_df.head(2)

,can_close_early,close_time,created_time,custom_strike,early_close_condition,event_ticker,expected_expiration_time,expiration_time,expiration_value,floor_strike,...,title,updated_time,volume_24h_fp,volume_fp,yes_ask_dollars,yes_ask_size_fp,yes_bid_dollars,yes_bid_size_fp,yes_sub_title,subtitle
0,True,2026-07-11T06:00:26Z,2026-07-10T22:34:20.107856Z,{'baseball_player': 'b160dd99-cd2c-4348-ac4e-4...,This market will close and expire after the ev...,KXMLBHR-26JUL102215COLSF,2026-07-11T05:15:00Z,2026-07-14T02:15:00Z,Willy Adames: 0 home runs,0.5,...,Willy Adames: 1+ home runs?,2026-07-11T06:06:29.51999Z,12001.48,12001.48,1.0000,0.00,0.0000,0.00,Willy Adames: 1+,None
1,True,2026-07-11T06:00:25Z,2026-07-10T22:34:14.897775Z,{'baseball_player': 'c26b6723-732e-48ba-8e2a-4...,This market will close and expire after the ev...,KXMLBHR-26JUL102215COLSF,2026-07-11T05:15:00Z,2026-07-14T02:15:00Z,Willi Castro: 0 home runs,1.5,...,Willi Castro: 2+ home runs?,2026-07-11T06:06:29.51999Z,23.39,23.39,1.0000,0.00,0.0000,0.00,Willi Castro: 2+,None

In [86]:
historical_markets_df.head(2)

,can_close_early,close_time,created_time,custom_strike,early_close_condition,event_ticker,expected_expiration_time,expiration_time,expiration_value,floor_strike,...,ticker,title,updated_time,volume_24h_fp,volume_fp,yes_ask_dollars,yes_ask_size_fp,yes_bid_dollars,yes_bid_size_fp,yes_sub_title
0,True,2026-05-11T23:52:57Z,2026-05-11T20:23:23.775122Z,{'baseball_player': 'e5aede12-a1f0-4820-9402-3...,This market will close and expire after the ev...,KXMLBHR-26MAY111835NYYBAL,2026-05-12T01:35:00Z,2026-05-14T22:35:00Z,Cancelled,1.5,...,KXMLBHR-26MAY111835NYYBAL-BALSBASALLO29-2,Samuel Basallo: 2+ home runs?,2026-05-11T23:59:05.204048Z,0.00,0.00,0.0900,-1.00,0.0000,0.00,Samuel Basallo: 2+
1,True,2026-05-11T23:52:57Z,2026-05-11T20:23:18.567172Z,{'baseball_player': 'e5aede12-a1f0-4820-9402-3...,This market will close and expire after the ev...,KXMLBHR-26MAY111835NYYBAL,2026-05-12T01:35:00Z,2026-05-14T22:35:00Z,Cancelled,0.5,...,KXMLBHR-26MAY111835NYYBAL-BALSBASALLO29-1,Samuel Basallo: 1+ home runs?,2026-05-11T23:59:05.204048Z,0.00,9644.13,0.1300,-117.00,0.0000,0.00,Samuel Basallo: 1+

In [87]:
# Concat data frames

markets_df = pd.concat([recent_markets_df, historical_markets_df], axis=0, join='outer')

In [88]:
print(f"Date of First Market: {markets_df['created_time'].min()} \nDate of Last Market: {markets_df['created_time'].max()}")

Date of First Market: 2026-03-24T00:41:49.013931Z
Date of Last Market: 2026-07-11T00:32:31.73949Z

In [89]:
# Drop duplicate tickers

markets_df = markets_df.drop_duplicates(['ticker'])

In [90]:
# Filter for liquid markets

markets_df = markets_df[markets_df['volume_fp'].astype(float) > 0]

In [91]:
# Market is finalized

markets_df = markets_df[markets_df['status'] == 'finalized']

In [92]:
# Remove 'scalar' (i.e. the game was cancelled)

markets_df = markets_df[markets_df['result'] != 'scalar']

In [93]:
# Create series column

markets_df['series'] = markets_df['ticker'].apply(lambda x: x.split('-')[0])

markets_df['series'].value_counts()

series
KXMLBHRR     76365
KXMLBHIT     66213
KXMLBTB      52325
KXMLBHR      36749
KXMLBKS      19225
KXMLBRBI      3550
KXMLBSB       1342
KXMLBOUTS      427
Name: count, dtype: int64

In [94]:
# Clean up index

markets_df = markets_df.reset_index(drop=True)

In [95]:
# Create series threshold column

markets_df['series_threshold'] = np.where(
    markets_df['floor_strike'].notna(),
    np.ceil(markets_df['floor_strike']),
    np.nan
)
markets_df['series_threshold'] = markets_df['series_threshold'].astype('Int64')

In [96]:
# Clean dates

markets_df['close_time'] = pd.to_datetime(markets_df['close_time'], format='ISO8601', utc=True)

### Preprocessing - Trade Data

In [97]:
# Load in data

recent_trades_df = pd.read_parquet('data/raw/recent_trades.parquet')
historical_trades_df = pd.read_parquet('data/raw/historical_trades.parquet')

In [98]:
recent_trades_df.head(2)

,count_fp,created_time,is_block_trade,no_price_dollars,taker_book_side,taker_outcome_side,taker_side,ticker,trade_id,yes_price_dollars
0,93.51,2026-07-11T04:47:00.715783Z,False,0.9900,bid,yes,yes,KXMLBHR-26JUL102215COLSF-COLHGOODMAN15-2,aabfb046-ca5d-5d40-e6b7-67f813050a64,0.0100
1,62.42,2026-07-11T02:22:09.932424Z,False,0.9700,bid,yes,yes,KXMLBHR-26JUL102215COLSF-COLHGOODMAN15-2,6c3884bb-8305-7e86-8476-a7a0fe5b4eb5,0.0300

In [99]:
recent_trades_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2799802 entries, 0 to 2799801
Data columns (total 10 columns):
 #   Column              Dtype
---  ------              -----
 0   count_fp            object
 1   created_time        object
 2   is_block_trade      bool
 3   no_price_dollars    object
 4   taker_book_side     object
 5   taker_outcome_side  object
 6   taker_side          object
 7   ticker              object
 8   trade_id            object
 9   yes_price_dollars   object
dtypes: bool(1), object(9)
memory usage: 194.9+ MB

In [100]:
historical_trades_df.head(2)

,count_fp,created_time,is_block_trade,no_price_dollars,taker_book_side,taker_outcome_side,taker_side,ticker,trade_id,yes_price_dollars
0,93.51,2026-05-10T22:07:50.435248Z,False,0.9900,bid,yes,yes,KXMLBHR-26MAY101920DETKC-DETMVIERLING8-2,f2a892a3-30f1-589c-413a-124a61d75ca0,0.0100
1,93.51,2026-05-10T22:12:44.497303Z,False,0.9900,bid,yes,yes,KXMLBHR-26MAY101920DETKC-KCMGARCIA11-2,7b23f626-12c0-5570-f8d7-8ed00c8e1751,0.0100

In [101]:
historical_trades_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1463001 entries, 0 to 1463000
Data columns (total 10 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   count_fp            1463001 non-null  object
 1   created_time        1463001 non-null  object
 2   is_block_trade      1463001 non-null  bool
 3   no_price_dollars    1463001 non-null  object
 4   taker_book_side     1463001 non-null  object
 5   taker_outcome_side  1463001 non-null  object
 6   taker_side          1463001 non-null  object
 7   ticker              1463001 non-null  object
 8   trade_id            1463001 non-null  object
 9   yes_price_dollars   1463001 non-null  object
dtypes: bool(1), object(9)
memory usage: 101.9+ MB

In [102]:
# Concat data frames

trades_df = pd.concat([recent_trades_df, historical_trades_df], axis=0, join='outer')

In [103]:
# Convert data

numeric_cols = ['count_fp', 'yes_price_dollars', 'no_price_dollars']

trades_df[numeric_cols] = trades_df[numeric_cols].apply(pd.to_numeric)

trades_df['created_time'] = pd.to_datetime(trades_df['created_time'], format='ISO8601', utc=True)

In [104]:
# Drop duplicate trades

trades_df = trades_df.drop_duplicates(['trade_id']).reset_index(drop=True)

In [105]:
# Ensure no mixed side when grouping by 'ticker' and 'created_time'

mixed_side_groups = trades_df.groupby(['ticker', 'created_time'])['taker_outcome_side'].transform('nunique') > 1

print(f"Number of groups with mixed sides: {mixed_side_groups.sum()}")

Number of groups with mixed sides: 0

In [106]:
# Resample trades that happened at the same time
#   - Here we assume that an order comes from the same party if it was created at the same time
#       - This assumption is defensible because trades are grouped at nanosecond-level timestamp 
#         precision, and no mixed sides (i.e. yes and no) occur when we aggregate by ticker and 
#         created time, suggesting these fills likely originate from a single order.
#   - This occurs when a larger order gets filled at different price levels
#   - Resample yes/no price by weighting yes/no price by dollar volume
#   - Create new variable to analyze order fill dispersion

TICK_SIZE: float = 0.01

trades_df['yes_dollar_vol'] = trades_df['count_fp'] * trades_df['yes_price_dollars']
trades_df['no_dollar_vol']  = trades_df['count_fp'] * trades_df['no_price_dollars']

trades_df = trades_df.groupby(['ticker', 'created_time'], as_index=False).agg(
    # Aggregate previous variables
    count_fp            = ('count_fp', 'sum'),
    yes_dollar_vol      = ('yes_dollar_vol', 'sum'),
    no_dollar_vol       = ('no_dollar_vol', 'sum'),
    taker_book_side     = ('taker_book_side', 'first'),
    taker_outcome_side  = ('taker_outcome_side', 'first'),
    taker_side          = ('taker_side', 'first'),
    trade_id            = ('trade_id', 'first'),

    # Create new variables
    levels_touched      = ('yes_price_dollars', 'nunique'), 
    yes_price_max       = ('yes_price_dollars', 'max'),
    yes_price_min       = ('yes_price_dollars', 'min')
)

# Aggregated yes/no price
trades_df['yes_price_dollars'] = (trades_df['yes_dollar_vol'] / trades_df['count_fp']).round(2)
trades_df['no_price_dollars']  = (trades_df['no_dollar_vol']  / trades_df['count_fp']).round(2)

# Order fill dispersion variable: price delta in ticks
trades_df['price_delta_ticks'] = (
    (trades_df['yes_price_max'] - trades_df['yes_price_min']) / TICK_SIZE
).round().astype(int)

trades_df = trades_df.drop(columns=['yes_dollar_vol', 'no_dollar_vol', 'yes_price_max', 'yes_price_min'])

In [107]:
# Add game start time column

MONTH_MAP = {
    "JAN": 1, "FEB": 2, "MAR": 3, "APR": 4,
    "MAY": 5, "JUN": 6, "JUL": 7, "AUG": 8,
    "SEP": 9, "OCT": 10, "NOV": 11, "DEC": 12,
}

parts = trades_df['ticker'].str.split('-').str[1]

year   = 2000 + parts.str[:2].astype(int)
month  = parts.str[2:5].str.upper().map(MONTH_MAP)
day    = parts.str[5:7].astype(int)
hour   = parts.str[7:9].astype(int)
minute = parts.str[9:11].astype(int)

trades_df['game_start_time'] = pd.to_datetime(
    dict(year=year, month=month, day=day, hour=hour, minute=minute)
).dt.tz_localize('UTC')

### Preprocessing - Combine Data

In [108]:
markets_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 256196 entries, 0 to 256195
Data columns (total 48 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   can_close_early           256196 non-null  bool
 1   close_time                256196 non-null  datetime64[ns, UTC]
 2   created_time              256196 non-null  object
 3   custom_strike             256196 non-null  object
 4   early_close_condition     256196 non-null  object
 5   event_ticker              256196 non-null  object
 6   expected_expiration_time  256196 non-null  object
 7   expiration_time           256196 non-null  object
 8   expiration_value          256196 non-null  object
 9   floor_strike              256196 non-null  float64
 10  last_price_dollars        256196 non-null  object
 11  latest_expiration_time    256196 non-null  object
 12  liquidity_dollars         256196 non-null  object
 13  market_type               256196 non-null  object
 14  no_ask_dollars            256196 non-null  object
 15  no_bid_dollars            256196 non-null  object
 16  no_sub_title              256196 non-null  object
 17  notional_value_dollars    256196 non-null  object
 18  occurrence_datetime       208481 non-null  object
 19  open_interest_fp          256196 non-null  object
 20  open_time                 256196 non-null  object
 21  previous_price_dollars    256196 non-null  object
 22  previous_yes_ask_dollars  256196 non-null  object
 23  previous_yes_bid_dollars  256196 non-null  object
 24  price_level_structure     256196 non-null  object
 25  price_ranges              256196 non-null  object
 26  primary_participant_key   243069 non-null  object
 27  result                    256196 non-null  object
 28  rules_primary             256196 non-null  object
 29  rules_secondary           256196 non-null  object
 30  settlement_timer_seconds  256196 non-null  int64
 31  settlement_ts             256196 non-null  object
 32  settlement_value_dollars  256196 non-null  object
 33  status                    256196 non-null  object
 34  strike_type               256196 non-null  object
 35  ticker                    256196 non-null  object
 36  title                     256196 non-null  object
 37  updated_time              256196 non-null  object
 38  volume_24h_fp             256196 non-null  object
 39  volume_fp                 256196 non-null  object
 40  yes_ask_dollars           256196 non-null  object
 41  yes_ask_size_fp           256196 non-null  object
 42  yes_bid_dollars           256196 non-null  object
 43  yes_bid_size_fp           256196 non-null  object
 44  yes_sub_title             256196 non-null  object
 45  subtitle                  1 non-null       object
 46  series                    256196 non-null  object
 47  series_threshold          256196 non-null  Int64
dtypes: Int64(1), bool(1), datetime64[ns, UTC](1), float64(1), int64(1), object(43)
memory usage: 92.4+ MB

In [109]:
trades_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2783197 entries, 0 to 2783196
Data columns (total 12 columns):
 #   Column              Dtype
---  ------              -----
 0   ticker              object
 1   created_time        datetime64[ns, UTC]
 2   count_fp            float64
 3   taker_book_side     object
 4   taker_outcome_side  object
 5   taker_side          object
 6   trade_id            object
 7   levels_touched      int64
 8   yes_price_dollars   float64
 9   no_price_dollars    float64
 10  price_delta_ticks   int64
 11  game_start_time     datetime64[ns, UTC]
dtypes: datetime64[ns, UTC](2), float64(3), int64(2), object(5)
memory usage: 254.8+ MB

In [110]:
# Merge data frames

merged = trades_df.merge(markets_df, on='ticker', how='left')

required_cols = [
    'ticker', 'created_time', 'count_fp', 'close_time', 'series',
    'game_start_time', 'result', 'yes_price_dollars', 'no_price_dollars',
    'taker_outcome_side', 
]

kalshi_df = merged[[
    'ticker', 'created_time_x', 'count_fp', 'close_time', 'series', 'game_start_time', 'result', 'yes_price_dollars',
    'no_price_dollars','floor_strike', 'taker_outcome_side', 'series_threshold', 'price_delta_ticks', 'levels_touched'
]].rename(columns={'created_time_x': 'created_time'}).dropna(subset=required_cols).sort_values(by=['created_time']).reset_index(drop=True).copy()

kalshi_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2753671 entries, 0 to 2753670
Data columns (total 14 columns):
 #   Column              Dtype
---  ------              -----
 0   ticker              object
 1   created_time        datetime64[ns, UTC]
 2   count_fp            float64
 3   close_time          datetime64[ns, UTC]
 4   series              object
 5   game_start_time     datetime64[ns, UTC]
 6   result              object
 7   yes_price_dollars   float64
 8   no_price_dollars    float64
 9   floor_strike        float64
 10  taker_outcome_side  object
 11  series_threshold    Int64
 12  price_delta_ticks   int64
 13  levels_touched      int64
dtypes: Int64(1), datetime64[ns, UTC](3), float64(4), int64(2), object(4)
memory usage: 296.8+ MB

# Dependent & Independent Variable Creation

In [111]:
# Independent: Number of price levels touched (per order fill)
# Note, heavy tail

kalshi_df['levels_touched'].value_counts()

levels_touched
1     2436088
2      207691
3       52833
4       25602
5       10822
6        6122
7        4114
8        2704
9        1667
10       1537
11        874
12        751
13        476
16        354
14        340
15        250
20        219
17        218
19        214
18        197
22        132
21        130
23        107
24         52
25         35
26         32
27         24
30         20
29         16
28         11
31         11
34          6
32          6
35          4
37          3
33          3
36          3
52          1
51          1
42          1
Name: count, dtype: int64

In [112]:
# Independent: Number of price levels touched (per order fill)

kalshi_df['log_levels_touched'] = np.log(kalshi_df['levels_touched'])   # Apply a log transformation to reduce heavy tail

print(np.isinf(kalshi_df['log_levels_touched']).sum(), 'infinite values')
print(kalshi_df['log_levels_touched'].isna().sum(), 'NaN values')

0 infinite values
0 NaN values

In [113]:
# Independent: Price delta in ticks (per order fill)
# Note, heavy tail

kalshi_df['price_delta_ticks'].value_counts()

price_delta_ticks
0     2436088
1      164534
2       49390
3       23227
4       17662
       ...
93         49
97         49
92         45
96         33
95         23
Name: count, Length: 99, dtype: int64

In [114]:
# Independent: Price delta in ticks (per order fill)

kalshi_df['log_price_delta_ticks'] = np.log1p(kalshi_df['price_delta_ticks'])   # Apply a log transformation to reduce heavy tail

print(np.isinf(kalshi_df['log_price_delta_ticks']).sum(), 'infinite values')
print(kalshi_df['log_price_delta_ticks'].isna().sum(), 'NaN values')

0 infinite values
0 NaN values

In [115]:
# Independent: Number of trades per market (ticker)

kalshi_df['n_trades_in_market'] = kalshi_df.groupby('ticker')['ticker'].transform('count')

In [116]:
# Independent: Number of trades per market (ticker)
# Note, heavy tail

log_bins = np.logspace(
    np.log10(kalshi_df['n_trades_in_market'].min()), 
    np.log10(kalshi_df['n_trades_in_market'].max()), 
    num=21
)

log_bin_counts = (
    pd.cut(kalshi_df['n_trades_in_market'], bins=log_bins, include_lowest=True)
    .value_counts()
    .sort_index()
    .reset_index()
)
log_bin_counts.columns = ["log_bin", "log_count"]

linear_bin_counts = (
    pd.cut(kalshi_df['n_trades_in_market'], bins=20)
    .value_counts()
    .sort_index()
    .reset_index()
)
linear_bin_counts.columns = ["linear_bin", "linear_count"]

pd.concat([log_bin_counts, linear_bin_counts], axis=1)

                log_bin  log_count         linear_bin  linear_count
0        (0.999, 1.446]      64960    (-0.589, 80.45]       1903694
1         (1.446, 2.09]      79256     (80.45, 159.9]        412771
2         (2.09, 3.021]      80328    (159.9, 239.35]        195619
3        (3.021, 4.368]      75404    (239.35, 318.8]         94773
4        (4.368, 6.315]     136429    (318.8, 398.25]         59249
5        (6.315, 9.129]     170907    (398.25, 477.7]         33533
6       (9.129, 13.197]     183682    (477.7, 557.15]         18001
7      (13.197, 19.079]     211749    (557.15, 636.6]         15116
8      (19.079, 27.582]     208959    (636.6, 716.05]          6797
9      (27.582, 39.875]     229304    (716.05, 795.5]          4542
10     (39.875, 57.646]     237298    (795.5, 874.95]          2495
11     (57.646, 83.337]     250193    (874.95, 954.4]           932
12    (83.337, 120.478]     231746   (954.4, 1033.85]          2007
13   (120.478, 174.172]     204041  (1033.85, 1113.3]             0
14   (174.172, 251.795]     164478  (1113.3, 1192.75]             0
15   (251.795, 364.014]     116836  (1192.75, 1272.2]          1210
16   (364.014, 526.244]      66120  (1272.2, 1351.65]          1342
17   (526.244, 760.777]      30839  (1351.65, 1431.1]             0
18  (760.777, 1099.834]       7000  (1431.1, 1510.55]             0
19   (1099.834, 1590.0]       2552  (1510.55, 1590.0]          1590

In [117]:
# Independent: Number of trades per market (ticker)

kalshi_df['log_n_trades_in_market'] = np.log(kalshi_df['n_trades_in_market'])   # Apply a log transformation to reduce heavy tail

print(np.isinf(kalshi_df['log_n_trades_in_market']).sum(), 'infinite values')
print(kalshi_df['log_n_trades_in_market'].isna().sum(), 'NaN values')

0 infinite values
0 NaN values

In [118]:
# Independent: Market Completion Percentage

kalshi_df['n_cum_trades'] = kalshi_df.groupby('ticker').cumcount()  # Cumulative number of trades per market (ticker)

kalshi_df['market_completion_pct'] = kalshi_df['n_cum_trades'] / kalshi_df['n_trades_in_market']

kalshi_df[['ticker', 'market_completion_pct']].sample(n = 3)

                                               ticker  market_completion_pct
2517398   KXMLBHRR-26JUL042010PHIKC-PHIKSCHWARBER12-5               0.333333
814448   KXMLBHR-26MAY021605CLEATH-ATHSLANGELIERS23-1               0.563830
553401       KXMLBKS-26APR211910MINNYM-NYMNMCLEAN26-7               0.695946

In [119]:
# Independent: Post kickoff dummy

kalshi_df['is_post_kickoff_dummy'] = (kalshi_df['created_time'] > kalshi_df['game_start_time']).astype(int)

kalshi_df[['ticker', 'is_post_kickoff_dummy', 'created_time', 'game_start_time']].sample(n = 3)

,ticker,is_post_kickoff_dummy,created_time,game_start_time
2368901,KXMLBHR-26JUN292140LADATH-LADFFREEMAN5-1,1,2026-06-30 03:28:12.468956+00:00,2026-06-29 21:40:00+00:00
2598236,KXMLBKS-26JUL071940BOSCWS-CWSNSCHULTZ75-5,0,2026-07-07 10:34:42.198362+00:00,2026-07-07 19:40:00+00:00
1510722,KXMLBHR-26MAY311610PHILAD-LADSOHTANI17-1,1,2026-05-31 19:48:38.239147+00:00,2026-05-31 16:10:00+00:00

In [120]:
# Independent: Taker outcome side dummy

kalshi_df['taker_outcome_side_dummy'] = (kalshi_df['taker_outcome_side'] == 'yes').astype(int)

kalshi_df[['ticker', 'taker_outcome_side', 'taker_outcome_side_dummy']].sample(n = 3)

,ticker,taker_outcome_side,taker_outcome_side_dummy
743533,KXMLBHR-26APR291340SEAMIN-MINBBUXTON25-1,yes,1
515224,KXMLBTB-26APR191605CWSATH-ATHNKURTZ16-2,yes,1
121289,KXMLBHIT-26MAR311940LAACHC-CHCMAMAYA9-1,yes,1

In [121]:
# Independent: Maker outcome side dummy

kalshi_df['maker_outcome_side'] = np.where(kalshi_df['taker_outcome_side'] == 'yes', 'no', 'yes')

kalshi_df['maker_outcome_side_dummy'] = (kalshi_df['maker_outcome_side'] == 'yes').astype(int)

kalshi_df[['ticker', 'maker_outcome_side', 'maker_outcome_side_dummy']].sample(n = 3)

,ticker,maker_outcome_side,maker_outcome_side_dummy
2088641,KXMLBHR-26JUN201915NYMPHI-NYMJSOTO22-1,no,0
576025,KXMLBHRR-26APR221507TORLAA-TORTHEINEMAN55-1,yes,1
503028,KXMLBKS-26APR191410CINMIN-MINBOBER17-7,no,0

In [122]:
# Independent: Trade Size (count)
# Note, heavy tail

log_bins = np.logspace(
    np.log10(kalshi_df['count_fp'].min()), 
    np.log10(kalshi_df['count_fp'].max()), 
    num=21
)

log_bin_counts = (
    pd.cut(kalshi_df['count_fp'], bins=log_bins, include_lowest=True)
    .value_counts()
    .sort_index()
    .reset_index()
)
log_bin_counts.columns = ["log_bin", "log_count"]

linear_bin_counts = (
    pd.cut(kalshi_df['count_fp'], bins=20)
    .value_counts()
    .sort_index()
    .reset_index()
)
linear_bin_counts.columns = ["linear_bin", "linear_count"]

pd.concat([log_bin_counts, linear_bin_counts], axis=1)

,log_bin,log_count,linear_bin,linear_count
0,"(0.009000000000000001, 0.0214]",620,"(-41.625, 2081.76]",2742657
1,"(0.0214, 0.0459]",434,"(2081.76, 4163.509]",7819
2,"(0.0459, 0.0984]",999,"(4163.509, 6245.258]",1964
3,"(0.0984, 0.211]",4295,"(6245.258, 8327.008]",532
4,"(0.211, 0.452]",5697,"(8327.008, 10408.758]",391
5,"(0.452, 0.968]",12713,"(10408.758, 12490.507]",107
6,"(0.968, 2.074]",320923,"(12490.507, 14572.256]",49
7,"(2.074, 4.444]",169799,"(14572.256, 16654.006]",40
8,"(4.444, 9.523]",325484,"(16654.006, 18735.755]",33
9,"(9.523, 20.405]",450419,"(18735.755, 20817.505]",21
10,"(20.405, 43.722]",451811,"(20817.505, 22899.254]",7
11,"(43.722, 93.686]",403303,"(22899.254, 24981.004]",17
12,"(93.686, 200.747]",317327,"(24981.004, 27062.753]",13
13,"(200.747, 430.151]",163985,"(27062.753, 29144.503]",3
14,"(430.151, 921.709]",80827,"(29144.503, 31226.252]",6
15,"(921.709, 1974.999]",32527,"(31226.252, 33308.002]",5
16,"(1974.999, 4231.943]",9412,"(33308.002, 35389.752]",3
17,"(4231.943, 9068.025]",2490,"(35389.752, 37471.501]",0
18,"(9068.025, 19430.574]",531,"(37471.501, 39553.25]",3
19,"(19430.574, 41635.0]",74,"(39553.25, 41635.0]",1

In [123]:
# Independent: Trade Size (count)

kalshi_df['log_count_fp'] = np.log(kalshi_df['count_fp'])   # Apply a log transformation to reduce heavy tail

print(np.isinf(kalshi_df['log_count_fp']).sum(), 'infinite values')
print(kalshi_df['log_count_fp'].isna().sum(), 'NaN values')

0 infinite values
0 NaN values

In [124]:
# Dependent: Maker PnL & Return

kalshi_df['maker_price'] = np.where(
    kalshi_df['maker_outcome_side'] == 'yes',
    kalshi_df['yes_price_dollars'],
    kalshi_df['no_price_dollars']
)

kalshi_df['maker_dollar_amt'] = kalshi_df['count_fp'] * np.where(
    kalshi_df['maker_outcome_side'] == 'yes', 
    kalshi_df['yes_price_dollars'],
    kalshi_df['no_price_dollars']
)

kalshi_df["maker_fee"] = np.ceil(KALSHI_MAKER_FEE * kalshi_df["count_fp"] * kalshi_df['maker_price'] * (1 - kalshi_df['maker_price']) * 100) / 100

kalshi_df["maker_revenue"] = kalshi_df["count_fp"] * np.where(
    ((kalshi_df['taker_outcome_side'] == "yes") & (kalshi_df["result"] == "no")) |
    ((kalshi_df['taker_outcome_side'] == "no") & (kalshi_df["result"] == "yes")),
    1,
    0
)

kalshi_df["maker_pnl"] = kalshi_df["maker_revenue"] - kalshi_df["maker_dollar_amt"] - kalshi_df["maker_fee"]

kalshi_df["maker_net_return"] = kalshi_df["maker_pnl"] / (kalshi_df["maker_dollar_amt"] + kalshi_df["maker_fee"])

kalshi_df['maker_pnl_per_contract'] = kalshi_df['maker_pnl'] / kalshi_df['count_fp']

kalshi_df[['ticker', 'maker_dollar_amt', 'maker_fee', 'maker_revenue', 'maker_pnl', 'maker_net_return', 'maker_pnl_per_contract']].sample(n = 3)

,ticker,maker_dollar_amt,maker_fee,maker_revenue,maker_pnl,maker_net_return,maker_pnl_per_contract
1819813,KXMLBHR-26JUN111410TEXKC-KCCJENSEN22-1,2210.8129,6.58,2663.63,446.2371,0.201244,0.167530
2255370,KXMLBHR-26JUN261910SEACLE-SEACEMERSON85-1,23.7636,0.04,0.00,-23.8036,-1.000000,-0.921549
2397996,KXMLBHR-26JUN302005SDCHC-CHCABREGMAN3-2,9.4000,0.01,10.00,0.5900,0.062699,0.059000

In [125]:
# Dependent: Taker PnL & Return

kalshi_df['taker_price'] = np.where(
    kalshi_df['taker_outcome_side'] == 'yes',
    kalshi_df['yes_price_dollars'],
    kalshi_df['no_price_dollars']
)

kalshi_df['taker_dollar_amt'] = kalshi_df['count_fp'] * np.where(
    kalshi_df['taker_outcome_side'] == 'yes',
    kalshi_df["yes_price_dollars"],
    kalshi_df["no_price_dollars"]
)

kalshi_df["taker_fee"] = np.ceil(KALSHI_TAKER_FEE * kalshi_df["count_fp"] * kalshi_df['taker_price'] * (1 - kalshi_df['taker_price']) * 100) / 100

kalshi_df["taker_revenue"] = kalshi_df["count_fp"] * np.where(
    ((kalshi_df['taker_outcome_side'] == 'yes') & (kalshi_df["result"] == "yes")) |
    ((kalshi_df['taker_outcome_side'] == 'no') & (kalshi_df["result"] == "no")),
    1,
    0
)

kalshi_df["taker_pnl"] = kalshi_df["taker_revenue"] - kalshi_df["taker_dollar_amt"] - kalshi_df["taker_fee"]

kalshi_df["taker_net_return"] = kalshi_df["taker_pnl"] / (kalshi_df["taker_dollar_amt"] + kalshi_df["taker_fee"])

kalshi_df['taker_pnl_per_contract'] = kalshi_df['taker_pnl'] / kalshi_df['count_fp']

kalshi_df[['ticker', 'taker_dollar_amt', 'taker_fee', 'taker_revenue', 'taker_pnl', 'taker_net_return', 'taker_pnl_per_contract']].sample(n = 3)

,ticker,taker_dollar_amt,taker_fee,taker_revenue,taker_pnl,taker_net_return,taker_pnl_per_contract
765807,KXMLBTB-26APR301505KCATH-ATHJWILSON5-2,9.660,0.34,19.32,9.320,0.932,0.482402
557220,KXMLBHR-26APR211840STLMIA-STLJWALKER18-1,4.719,0.29,0.00,-5.009,-1.000,-0.159218
1275963,KXMLBHR-26MAY221915WSHATL-ATLMOLSON28-1,4.694,0.27,0.00,-4.964,-1.000,-0.211504

# Analysis


### Market Analysis

- Start Date: First trade placed for each series or series threshold.

- End Date: Last trade placed for each series or series threshold.

- $n$ Trades: Number of trades placed for each series or series threshold.

- $n$ Markets: Number of unique markets (tickers) included within each series or series threshold.

- Contract Volume: Total number of contracts transacted on a series or series threshold basis.

- Average Taker Trade Size: Average trade size of a taker in dollars on a series or series threshold basis.

- Median Taker Trade Size: Median trade size of a taker in dollars on a series or series threshold basis.

- Trades per Market: $n$ trades divided by $n$ markets.

- Total Taker PnL: Summation of a taker's profit and loss across all trades; where, profit and loss for a single trade is defined as $$ \text{contracts} \times \text{outcome (1 if taker's side wins, else 0)} - \text{contracts} \times \text{price paid} - \text{taker fees} $$

- Taker Net Return (%): Total taker PnL divided by total taker capital at risk (dollar amount paid plus fees), expressed as a percentage. Represents the aggregate, dollar-weighted return across all taker trades in the series or series threshold.

- Taker Win Rate (%): Percentage of taker trades with positive PnL.

- Taker Winning Trades Average Return (%): Average return of trades where a taker profited (i.e. PnL > 0).

- Taker Losing Trades Average Return (%): Average return of trades where a taker did not profit (i.e. PnL $\leq$ 0).

- Total Maker PnL: Summation of a maker's profit and loss across all trades; where, profit and loss for a single trade is defined as $$ \text{contracts} \times \text{outcome (1 if maker's side wins, else 0)} - \text{contracts} \times \text{price paid} - \text{maker fees} $$

- Maker Net Return (%): Total maker PnL divided by total maker capital at risk (dollar amount paid plus fees), expressed as a percentage. Represents the aggregate, dollar-weighted return across all maker trades in the series or series threshold.

- Maker Win Rate (%): Percentage of maker trades with positive PnL.

- Maker Winning Trades Average Return (%): Average return of trades where a maker profited (i.e. PnL > 0).

- Maker Losing Trades Average Return (%): Average return of trades where a maker did not profit (i.e. PnL $\leq$ 0).

- Maker Fee % of Edge: Total maker fees paid, as a percentage of the maker's gross edge (maker revenue less maker dollar cost, before fees). Represents how much of the maker's raw trading edge is given back in fees.


### Pre-Game Implied Outcome Probability vs. Hit Rate

- <span style="color:#E29A4A; font-weight: bold; font-style: normal;">Pre-Game Market Implied Probability</span>:

    - Seeks to represent how likely the market believes the outcome to be.

    - Let $T_{pg,k} = \{(p_i, c_i)\}_{i=1}^{n}$ be the set of all observed pre-game trades for the $k^{th}$ market, where $p_i$ is the 'Yes' price and $c_i$ is the contract quantity transacted for trade $i$. The contract-weighted average pre-game 'Yes' price by market is then defined as: $$ \frac{\sum_{i=1}^{n} p_i \cdot c_i}{\sum_{i=1}^{n} c_i} $$

    - Then, the pre-game market implied probability for a series with $m$ markets can be defined: $$ \frac{1}{m} \sum_{k=1}^{m} \frac{\sum_{i=1}^{n_k} p_{i,k} \cdot c_{i,k}}{\sum_{i=1}^{n_k} c_{i,k}} $$

- <span style="color:#9096ED; font-weight: bold; font-style: normal;">Hit Rate</span>:
    - Let $G = \{g_1, \dots, g_m\}$ be the set of all finalized markets in the series, and let $y_k \in \{0, 1\}$ indicate whether market $k$ resolved 'Yes'. The hit rate is then defined as: $$ \frac{1}{m} \sum_{k=1}^{m} y_k $$


### Multivariable Regression Analysis

- **Dependent Variable(s)**

    - _Maker profit and loss per contract (maker_pnl_per_contract)_: Defined as maker revenue less the maker's dollar position size and maker fees paid on the position, divided by total contracts. Seeks to avoid extreme returns to reduce outliers, and to normalize by position size to reduce heteroskedasticity.

    - _Taker profit and loss per contract (taker_pnl_per_contract)_: Defined as taker revenue less the taker's dollar position size and taker fees paid on the position, divided by total contracts. Seeks to avoid extreme returns to reduce outliers, and to normalize by position size to reduce heteroskedasticity.

- **Independent Variables**

    - <span style="color:#FDFD96"><em>Outcome side dummy (maker_outcome_side_dummy/taker_outcome_side_dummy)</em></span>: $1$ if a trade is taken on the 'yes' side, $0$ if 'no'. A dummy variable, specified by maker/taker, which measures the effect of side on profitability.

    - <span style="color:#5A99E0"><em>Market completion percentage (market_completion_pct)</em></span>: Defined as the number of trades placed prior to this trade, divided by the total number of trades the market will ever have. A variable seeking to understand the effect market lifecycle stage (maturity) has on profitability, independent of the market's overall size.

    - <span style="color:#5A99E0"><em>Post kickoff dummy (is_post_kickoff_dummy)</em></span>: Defined as $1$ when a trade is placed after game start time and $0$ otherwise. A dummy variable seeking to incorporate pre-game and in-game/post-kickoff dynamics into market lifecycle stage (maturity).

    - <span style="color:#50E3C2"><em>Trade size (log_count_fp)</em></span>: Defined as the number of contracts. A variable seeking to understand whether larger trades signal a more sophisticated trader. In other words, how does trade size measured by contract count affect profitability. *Note, a log transformation was applied to reduce a long right tail.*

    - <span style="color:#FF6B6B"><em>Number of trades per market (log_n_trades_in_market)</em></span>: Defined as the total number of trades in each market (ticker). A variable seeking to understand the effect market size has on profitability. *Note, a log transformation was applied to reduce a long right tail.*

    - <span style="color:#F7A2C0"><em>Number of price levels touched (log_levels_touched)</em></span>: Defined as the number of unique prices within a cluster of trades sharing the same market and timestamp, used as a proxy for a single aggressive order filled across multiple price levels. A variable seeking to capture breadth of order fill dispersion, how many distinct price levels were consumed, and its effect on profitability. *Note, a log transformation was applied to reduce a long right tail.*

    - <span style="color:#F7A2C0"><em>Price delta in ticks (log_price_delta_ticks)</em></span>: Defined as the maximum price less the minimum price within the same trade cluster, divided by tick size. A variable seeking to capture depth of order fill dispersion, how far price moved as a result, and its effect on profitability. *Note, a log1p transformation was applied to accommodate observations with zero price movement, while reducing a long right tail.*

In [126]:
# Create 'prop' data frames

prop_dfs = {
    name: kalshi_df[kalshi_df['series'] == ticker].reset_index(drop=True).copy()
    for name, ticker in SERIES_TICKERS.items()
}

stolen_bases_df   = prop_dfs['stolen_bases']
homeruns_df       = prop_dfs['homeruns']       
strikeouts_df     = prop_dfs['strikeouts']
hits_df           = prop_dfs['hits']            
hits_runs_rbi_df  = prop_dfs['hits_runs_rbi']
total_bases_df    = prop_dfs['total_bases']
outs_df           = prop_dfs['outs']
rbi_df            = prop_dfs['rbi']

### Analysis - **All** in a MLB Game

In [127]:
# Market Analysis

market_analytics_df = market_analysis(
    df                = kalshi_df,
    n_req_trades      = 500, 
    series_thresholds = False  
)

market_analytics_df.melt()

                   variable                             value
0                start_date  2026-03-24 01:36:06.177683+00:00
1                  end_date  2026-07-11 05:55:17.637658+00:00
2                  n_trades                           2753671
3                 n_markets                            256196
4           contract_volume                      273694773.52
5      avg_taker_trade_size                         33.537451
6   median_taker_trade_size                              5.25
7         trades_per_market                         10.748298
8           total_taker_pnl                     -4503020.4675
9         taker_pct_net_ret                         -4.739752
10        taker_pct_winning                         39.958223
11    taker_win_avg_pct_ret                         125.76563
12   taker_loss_avg_pct_ret                        -99.852405
13          total_maker_pnl                      1173819.2395
14        maker_pct_net_ret                           0.64489
15        maker_pct_winning                         59.881918
16    maker_win_avg_pct_ret                           62.8036
17   maker_loss_avg_pct_ret                        -99.854094
18    maker_fee_pct_of_edge                          36.50498

In [128]:
# Comparison Analysis
# Note, hover over bars for t-test

graph_comparison(
    df           = kalshi_df,
    graph_title  = "All MLB",
    n_req_trades = 500,
    ci           = 0.95,
)

In [129]:
# Regression Analysis: Maker PnL
# Note, hover for regression details

graph_regression(
    df           = kalshi_df,
    graph_title  = "All MLB",
    side         = 'maker',
    n_req_trades = 500,
    show_const   = False
)

In [130]:
# Regression Analysis: Taker PnL
# Note, hover for regression details

graph_regression(
    df           = kalshi_df,
    graph_title  = "All MLB",
    side         = 'taker',
    n_req_trades = 500,
    show_const   = False
)

### Analysis - **1+ Stolen Bases** in a MLB Game

In [131]:
# Market Analysis

market_analytics_df = market_analysis(
    df                = stolen_bases_df,
    n_req_trades      = 500, 
    series_thresholds = False  
)

market_analytics_df.melt()

                   variable                             value
0                start_date  2026-06-22 23:30:28.382288+00:00
1                  end_date  2026-07-11 05:53:43.843023+00:00
2                  n_trades                              3303
3                 n_markets                              1342
4           contract_volume                         223020.48
5      avg_taker_trade_size                         38.330914
6   median_taker_trade_size                              4.95
7         trades_per_market                          2.461252
8           total_taker_pnl                        -5616.0085
9         taker_pct_net_ret                         -4.397251
10        taker_pct_winning                         50.893127
11    taker_win_avg_pct_ret                         61.508172
12   taker_loss_avg_pct_ret                        -98.507253
13          total_maker_pnl                         4214.3185
14        maker_pct_net_ret                          4.357875
15        maker_pct_winning                          48.04723
16    maker_win_avg_pct_ret                        105.623609
17   maker_loss_avg_pct_ret                        -99.688497
18    maker_fee_pct_of_edge                          6.481866

In [132]:
# Comparison Analysis
# Note, hover over bars for t-test

graph_comparison(
    df           = stolen_bases_df,
    graph_title  = "1+ Stolen Bases",
    n_req_trades = 500,
    ci           = 0.95,
)

In [133]:
# Regression Analysis: Maker PnL
# Note, hover for regression details

graph_regression(
    df           = stolen_bases_df,
    graph_title  = "1+ Stolen Bases",
    side         = 'maker',
    n_req_trades = 500,
    show_const   = False
)

In [134]:
# Regression Analysis: Taker PnL
# Note, hover for regression details

graph_regression(
    df           = stolen_bases_df,
    graph_title  = "1+ Stolen Bases",
    side         = 'taker',
    n_req_trades = 500,
    show_const   = False
)

### Analysis - **Home Run** in a MLB Game

In [135]:
# Market Analysis

market_analytics_df = market_analysis(
    df                = homeruns_df,
    n_req_trades      = 500,   
    series_thresholds = True
)

market_analytics_df.sort_values(by = ['total_maker_pnl', 'maker_pct_net_ret', 'n_markets'], ascending = False)

,series_threshold,start_date,end_date,n_trades,n_markets,contract_volume,avg_taker_trade_size,median_taker_trade_size,trades_per_market,total_taker_pnl,taker_pct_net_ret,taker_pct_winning,taker_win_avg_pct_ret,taker_loss_avg_pct_ret,total_maker_pnl,maker_pct_net_ret,maker_pct_winning,maker_win_avg_pct_ret,maker_loss_avg_pct_ret,maker_fee_pct_of_edge
0,1,2026-03-24 03:10:16.259495+00:00,2026-07-11 05:54:20.075578+00:00,1040336,24520,1.218971e+08,25.530007,4.7340,42.428059,-1.996951e+06,-7.241690,23.514038,265.754765,-99.942283,722836.8176,0.756141,76.388686,29.115132,-99.807425,26.313814
1,2,2026-03-24 08:17:52.294846+00:00,2026-07-11 05:54:22.081233+00:00,77106,11901,2.017424e+07,18.726649,3.6680,6.478951,-3.136007e+05,-21.071750,14.324436,330.074589,-99.905161,257875.6152,1.375945,85.505668,14.779920,-99.447630,4.236450
2,3,2026-03-25 20:38:53.891270+00:00,2026-07-11 04:33:27.446630+00:00,2490,328,9.360843e+05,28.696946,3.0979,7.591463,-7.074955e+03,-9.747373,18.273092,262.973688,-100.000000,5653.2350,0.653612,81.646586,15.510325,-99.578452,4.938998

In [136]:
# Comparison Analysis
# Note, hover over bars for t-test

graph_comparison_by_threshold(
    df            = homeruns_df,
    graph_title   = "Home Run",
    n_req_trades  = 500,
    n_req_markets = 10,
    ci            = 0.95,
)

In [137]:
# Regression Analysis: Maker PnL
# Note, hover for regression details

graph_regression_by_threshold(
    df          = homeruns_df,        # Consider all Series thresholds
    side        = 'maker',
    graph_title = 'Home Run',
)

In [138]:
# Regression Analysis: Taker PnL
# Note, hover for regression details

graph_regression_by_threshold(
    df          = homeruns_df,        # Consider all Series thresholds
    side        = 'taker',
    graph_title = 'Home Run',
)

### Analysis - **Strikeouts** in a MLB Game

In [139]:
# Market Analysis

market_analytics_df = market_analysis(
    df                = strikeouts_df,
    n_req_trades      = 500,   
    series_thresholds = True
)

market_analytics_df.sort_values(by = ['total_maker_pnl', 'maker_pct_net_ret', 'n_markets'], ascending = False)

Invalid Series Threshold: [1, 14] do not have 500 required trades.

,series_threshold,start_date,end_date,n_trades,n_markets,contract_volume,avg_taker_trade_size,median_taker_trade_size,trades_per_market,total_taker_pnl,taker_pct_net_ret,taker_pct_winning,taker_win_avg_pct_ret,taker_loss_avg_pct_ret,total_maker_pnl,maker_pct_net_ret,maker_pct_winning,maker_win_avg_pct_ret,maker_loss_avg_pct_ret,maker_fee_pct_of_edge
9,11,2026-03-25 17:14:18.734493+00:00,2026-07-11 01:10:04.511844+00:00,6119,387,708292.70,30.076736,4.9500,15.811370,-26666.6179,-14.148949,29.122406,148.514313,-99.805912,21103.7279,4.016813,70.648799,43.019839,-99.783166,5.092229
10,12,2026-03-26 09:19:52.103218+00:00,2026-07-10 01:21:14.532181+00:00,2628,126,306253.19,25.529896,4.9000,20.857143,-16992.4356,-24.640990,24.733638,143.892013,-99.718838,14647.4456,6.112318,74.961948,34.951761,-99.738804,3.157164
1,3,2026-03-24 17:40:52.617804+00:00,2026-07-11 05:47:34.917430+00:00,23679,2267,2276841.57,65.989428,5.5220,10.445082,-30281.5243,-1.921012,63.102327,62.011479,-99.466752,12967.8343,1.806550,36.454242,166.252272,-99.674313,21.462538
8,10,2026-03-25 16:16:57.772729+00:00,2026-07-11 03:38:34.706932+00:00,18533,929,2099618.56,30.514334,6.2370,19.949408,-23402.3268,-4.028054,32.245184,175.023646,-99.736283,4000.3868,0.260097,67.468839,52.877499,-99.743013,49.613784
11,13,2026-04-01 12:37:07.063723+00:00,2026-07-08 00:37:03.801984+00:00,671,26,94592.86,25.633087,4.7125,25.807692,1880.1287,10.593778,18.628912,228.568908,-99.469505,-2567.4987,-3.311502,80.923994,24.309293,-100.000000,-5.753748
7,9,2026-03-24 19:33:52.795484+00:00,2026-07-11 04:49:37.021944+00:00,31378,1655,3260899.18,34.462698,7.2000,18.959517,-33280.6158,-2.998058,38.476002,156.871889,-99.721960,-2720.7002,-0.124413,61.237173,56.277702,-99.772020,159.430149
0,2,2026-03-25 20:03:51.961144+00:00,2026-07-11 04:09:20.425493+00:00,6361,1095,803537.04,92.009420,4.8500,5.809132,803.0365,0.136721,68.542682,38.305150,-99.474075,-3437.5365,-1.570974,31.080019,197.972325,-99.755601,-19.056037
6,8,2026-03-24 04:23:10.278727+00:00,2026-07-11 04:44:14.304866+00:00,61371,2341,6692349.41,43.526768,9.3600,26.215720,-79659.3209,-2.897234,42.327810,117.460718,-99.752903,-18346.5501,-0.454026,57.450587,68.778429,-99.857708,1367.525985
4,6,2026-03-24 01:36:06.177683+00:00,2026-07-11 05:05:48.355024+00:00,140832,2608,15889736.23,56.482650,9.6992,54.000000,-256581.4864,-3.133017,49.609464,86.914753,-99.873842,-37756.6336,-0.472284,50.252073,98.877256,-99.872000,275.256467
2,4,2026-03-24 16:25:53.868379+00:00,2026-07-11 04:07:42.929924+00:00,69443,2582,7636834.84,62.911951,9.3800,26.895043,-66096.9767,-1.480043,56.812062,66.534877,-99.737570,-55538.9233,-1.686787,42.950333,141.793064,-99.812952,-79.219889
5,7,2026-03-24 01:36:06.218367+00:00,2026-07-11 04:30:26.809623+00:00,103347,2581,11318691.20,50.860954,9.6720,40.041457,-43764.7454,-0.808710,48.522937,93.595992,-99.800787,-150824.0346,-2.471873,51.296119,84.710821,-99.870785,-35.163499
3,5,2026-03-24 14:49:23.440252+00:00,2026-07-11 04:49:13.041753+00:00,128951,2607,15337146.92,62.398754,9.7461,49.463368,-128976.3907,-1.558750,52.213632,75.858301,-99.817234,-156475.5433,-2.129425,47.613435,110.556208,-99.858937,-58.075723

In [140]:
# Comparison Analysis
# Note, hover over bars for t-test

graph_comparison_by_threshold(
    df            = strikeouts_df,
    graph_title   = "Strikeouts",
    n_req_trades  = 500,
    n_req_markets = 10,
    ci            = 0.95,
)

In [141]:
# Regression Analysis: Maker PnL
# Note, hover for regression details

valid_series_thresholds = set({4, 5, 6, 7, 8})     # Series thresholds chosen by popularity
valid_strikeouts_df = strikeouts_df[strikeouts_df['series_threshold'].isin(valid_series_thresholds)].copy()

graph_regression_by_threshold(
    df          = valid_strikeouts_df, 
    side        = 'maker',
    graph_title = 'Strikeouts',
)

In [142]:
# Regression Analysis: Taker PnL
# Note, hover for regression details

graph_regression_by_threshold(
    df          = valid_strikeouts_df, 
    side        = 'taker',
    graph_title = 'Strikeouts',
)

### Analysis - **Hits** in a MLB Game

In [143]:
# Market Analysis

market_analytics_df = market_analysis(
    df                = hits_df,
    n_req_trades      = 500,   
    series_thresholds = True
)

market_analytics_df.sort_values(by = ['total_maker_pnl', 'maker_pct_net_ret', 'n_markets'], ascending = False)

,series_threshold,start_date,end_date,n_trades,n_markets,contract_volume,avg_taker_trade_size,median_taker_trade_size,trades_per_market,total_taker_pnl,taker_pct_net_ret,taker_pct_winning,taker_win_avg_pct_ret,taker_loss_avg_pct_ret,total_maker_pnl,maker_pct_net_ret,maker_pct_winning,maker_win_avg_pct_ret,maker_loss_avg_pct_ret,maker_fee_pct_of_edge
0,1,2026-03-24 05:12:10.540550+00:00,2026-07-11 05:53:36.791501+00:00,236679,24532,16103957.81,39.965341,8.2800,9.647766,-281064.9331,-2.916346,60.241509,55.394858,-99.689096,56826.9191,0.849352,39.519349,147.925547,-99.830326,44.531910
1,2,2026-03-24 07:09:16.419720+00:00,2026-07-11 05:55:17.637658+00:00,146323,23877,8448466.52,25.424984,4.9000,6.128199,-122498.4320,-3.218834,47.798364,97.607503,-99.791871,15082.1420,0.317505,52.040349,79.931631,-99.914940,59.322571
2,3,2026-03-24 05:59:38.116766+00:00,2026-07-11 05:24:09.000433+00:00,53472,15960,3198605.68,17.954956,2.8522,3.350376,-31138.0017,-3.192251,39.701152,142.915683,-99.894173,11711.6717,0.522235,60.181029,43.227656,-99.897496,25.873627
3,4,2026-03-24 19:22:18.858196+00:00,2026-07-11 05:53:36.765958+00:00,5069,1844,444180.33,12.263351,1.3546,2.748915,-8162.1779,-12.872815,25.823634,163.998501,-99.935632,6582.9779,1.721701,74.038272,28.236586,-99.731586,4.853596

In [144]:
# Comparison Analysis
# Note, hover over bars for t-test

graph_comparison_by_threshold(
    df            = hits_df,
    graph_title   = "Hits",
    n_req_trades  = 500,
    n_req_markets = 10,
    ci            = 0.95,
)

In [145]:
# Regression Analysis: Maker PnL
# Note, hover for regression details

graph_regression_by_threshold(
    df          = hits_df,      # Consider all Series thresholds
    side        = 'maker',
    graph_title = 'Hits',
)

In [146]:
# Regression Analysis: Taker PnL
# Note, hover for regression details

graph_regression_by_threshold(
    df          = hits_df,      # Consider all Series thresholds
    side        = 'taker',
    graph_title = 'Hits',
)

### Analysis - Combined **Hits, Runs, & RBIs** in a MLB Game

In [147]:
# Market Analysis

market_analytics_df = market_analysis(
    df                = hits_runs_rbi_df,
    n_req_trades      = 500,   
    series_thresholds = True
)

market_analytics_df.sort_values(by = ['total_maker_pnl', 'maker_pct_net_ret', 'n_markets'], ascending = False)

,series_threshold,start_date,end_date,n_trades,n_markets,contract_volume,avg_taker_trade_size,median_taker_trade_size,trades_per_market,total_taker_pnl,taker_pct_net_ret,taker_pct_winning,taker_win_avg_pct_ret,taker_loss_avg_pct_ret,total_maker_pnl,maker_pct_net_ret,maker_pct_winning,maker_win_avg_pct_ret,maker_loss_avg_pct_ret,maker_fee_pct_of_edge
1,2,2026-03-24 14:00:53.244640+00:00,2026-07-11 05:26:44.142407+00:00,161387,20645,10324369.17,34.074793,7.56,7.817244,-445297.2295,-7.874413,53.429954,75.248515,-99.615992,249945.1395,5.137901,46.337685,120.551916,-99.930411,13.673318
2,3,2026-03-24 17:52:01.794245+00:00,2026-07-11 05:07:04.982905+00:00,62626,15407,3767097.25,25.908571,4.95,4.064776,-134911.5795,-8.059281,48.516591,98.316491,-99.855056,70339.7995,3.259975,51.362054,88.929115,-99.939223,15.731209
4,5,2026-03-25 17:19:21.385850+00:00,2026-07-11 03:59:35.644091+00:00,16161,6877,896569.92,18.280551,4.00,2.350007,-21898.3693,-7.249705,48.078708,99.062070,-99.892768,13534.0205,2.244911,51.791350,97.702355,-99.898851,11.378141
3,4,2026-03-24 17:34:10.015144+00:00,2026-07-11 04:50:39.350151+00:00,27765,10394,1321794.10,19.425934,3.92,2.671253,-3528.1408,-0.638686,51.809833,88.907630,-99.864771,-12913.0092,-1.643234,48.031695,81.103205,-99.912229,-35.671362
0,1,2026-03-24 05:20:24.198216+00:00,2026-07-11 05:25:28.341656+00:00,68121,23042,3361764.50,32.719989,4.95,2.956384,62659.9174,2.774744,73.720292,48.301667,-99.385147,-99639.1574,-8.736288,25.974369,199.589246,-99.830145,-8.343793

In [148]:
# Comparison Analysis
# Note, hover over bars for t-test

graph_comparison_by_threshold(
    df            = hits_runs_rbi_df,
    graph_title   = "Hits + Runs + RBIs",
    n_req_trades  = 500,
    n_req_markets = 10,
    ci            = 0.95,
)

In [149]:
# Regression Analysis: Maker PnL
# Note, hover for regression details

graph_regression_by_threshold(
    df          = hits_runs_rbi_df,      # Consider all Series thresholds
    side        = 'maker',
    graph_title = 'Hits + Runs + RBIs',
)

In [150]:
# Regression Analysis: Taker PnL
# Note, hover for regression details

graph_regression_by_threshold(
    df          = hits_runs_rbi_df,      # Consider all Series thresholds
    side        = 'taker',
    graph_title = 'Hits + Runs + RBIs',
)

### Analysis - **Total Bases** in a MLB Game

In [151]:
# Market Analysis

market_analytics_df = market_analysis(
    df                = total_bases_df,
    n_req_trades      = 500,   
    series_thresholds = True
)

market_analytics_df.sort_values(by = ['total_maker_pnl', 'maker_pct_net_ret', 'n_markets'], ascending = False)

Invalid Series Threshold: [8] do not have 500 required trades.

,series_threshold,start_date,end_date,n_trades,n_markets,contract_volume,avg_taker_trade_size,median_taker_trade_size,trades_per_market,total_taker_pnl,taker_pct_net_ret,taker_pct_winning,taker_win_avg_pct_ret,taker_loss_avg_pct_ret,total_maker_pnl,maker_pct_net_ret,maker_pct_winning,maker_win_avg_pct_ret,maker_loss_avg_pct_ret,maker_fee_pct_of_edge
0,2,2026-03-24 22:48:12.700517+00:00,2026-07-11 05:24:07.998115+00:00,144538,19645,9583958.67,31.986527,8.8000,7.357496,-374032.8109,-7.862251,48.600368,86.699007,-99.735698,205887.9109,4.122063,51.212830,93.864314,-99.921986,14.205181
2,4,2026-03-25 02:43:40.704204+00:00,2026-07-11 04:17:50.169635+00:00,29846,10431,1867234.02,22.964373,4.5000,2.861279,-53119.9666,-7.581030,44.937345,108.711334,-99.960734,33856.6566,2.855171,54.998995,70.422053,-99.934747,10.476926
4,6,2026-03-25 09:09:56.365120+00:00,2026-07-11 03:44:32.160887+00:00,4089,1668,328664.62,15.339399,4.0000,2.451439,-12612.8624,-19.529367,27.635119,180.977473,-99.918425,10267.9932,3.853984,72.242602,45.672595,-99.826186,4.497494
3,5,2026-03-25 02:43:49.170285+00:00,2026-07-11 05:04:02.290471+00:00,12616,5589,777272.66,19.385122,4.0812,2.257291,-9339.3255,-3.750907,42.985098,149.919306,-99.911368,3748.9759,0.702220,56.935637,70.409337,-99.946505,23.703077
5,7,2026-03-25 21:00:46.903717+00:00,2026-07-10 22:38:15.720956+00:00,500,175,42316.78,11.848741,3.4100,2.857143,-2635.1706,-42.854082,24.400000,120.029663,-99.742771,2351.9306,6.452334,75.400000,32.110344,-100.000000,2.422094
1,3,2026-03-25 04:00:19.346336+00:00,2026-07-11 05:24:09.003297+00:00,48495,14783,2338955.12,22.562568,4.5600,3.280457,-18827.6298,-1.684836,49.860810,97.360152,-99.931727,-10526.9202,-0.841592,50.083514,75.296036,-99.975055,-135.124939

In [152]:
# Comparison Analysis
# Note, hover over bars for t-test

graph_comparison_by_threshold(
    df            = total_bases_df,
    graph_title   = "Total Bases",
    n_req_trades  = 500,
    n_req_markets = 10,
    ci            = 0.95,
)

In [153]:
# Regression Analysis: Maker PnL
# Note, hover for regression details

valid_series_thresholds = set({2, 3, 4, 5, 6})     # Series thresholds chosen by popularity
valid_total_bases_df = total_bases_df[total_bases_df['series_threshold'].isin(valid_series_thresholds)].copy()

graph_regression_by_threshold(
    df          = valid_total_bases_df, 
    side        = 'maker',
    graph_title = 'Total Bases',
)

In [154]:
# Regression Analysis: Taker PnL
# Note, hover for regression details

graph_regression_by_threshold(
    df          = valid_total_bases_df, 
    side        = 'taker',
    graph_title = 'Total Bases',
)

### Analysis - **Outs** in a MLB Game

In [155]:
# Market Analysis

market_analytics_df = market_analysis(
    df                = outs_df,
    n_req_trades      = 500,   
    series_thresholds = True
)

market_analytics_df.sort_values(by = ['total_maker_pnl', 'maker_pct_net_ret', 'n_markets'], ascending = False)

Invalid Series Threshold: [9, 12, 14, 20] do not have 500 required trades.

,series_threshold,start_date,end_date,n_trades,n_markets,contract_volume,avg_taker_trade_size,median_taker_trade_size,trades_per_market,total_taker_pnl,taker_pct_net_ret,taker_pct_winning,taker_win_avg_pct_ret,taker_loss_avg_pct_ret,total_maker_pnl,maker_pct_net_ret,maker_pct_winning,maker_win_avg_pct_ret,maker_loss_avg_pct_ret,maker_fee_pct_of_edge
3,18,2026-06-23 01:30:54.116517+00:00,2026-07-11 04:22:18.983520+00:00,4828,149,407916.05,48.297112,12.94020,32.402685,-13742.1564,-5.753661,51.201326,70.581401,-99.627650,6643.9764,3.771295,48.529412,158.944107,-99.893496,17.753905
0,15,2026-06-23 01:36:34.899488+00:00,2026-07-11 01:27:44.105658+00:00,880,59,85019.95,60.558527,13.40265,14.915254,-2593.7537,-4.773849,54.090909,63.980393,-99.537611,1289.0637,4.029319,45.454545,186.622120,-99.589768,16.979949
4,19,2026-06-23 15:42:55.804790+00:00,2026-07-11 03:58:51.442429+00:00,1034,25,83679.97,44.357230,11.58360,41.360000,-2486.9856,-5.286258,47.582205,100.021399,-99.184116,1006.8456,2.641677,51.837524,187.713614,-99.899094,22.913570
2,17,2026-06-23 01:20:48.669176+00:00,2026-07-11 04:15:55.411895+00:00,2052,71,146833.92,40.261974,9.70920,28.901408,59.4486,0.070331,51.169591,71.130717,-99.327171,-2453.2886,-3.791712,48.294347,126.736958,-99.764960,-24.640062
1,16,2026-06-23 02:45:19.987633+00:00,2026-07-11 04:07:26.784803+00:00,2144,114,204096.90,54.820526,11.64885,18.807018,10889.7017,9.070108,55.037313,69.273949,-99.647731,-14055.6317,-16.118586,44.682836,144.199456,-99.832095,-4.768212

In [156]:
# Comparison Analysis
# Note, hover over bars for t-test

graph_comparison_by_threshold(
    df            = outs_df,
    graph_title   = "Outs",
    n_req_trades  = 500,
    n_req_markets = 10,
    ci            = 0.95,
)

In [157]:
# Regression Analysis: Maker PnL
# Note, hover for regression details

graph_regression_by_threshold(
    df          = outs_df,        # Consider all Series thresholds
    side        = 'maker',
    graph_title = 'Outs',
)

Invalid Series Threshold: [9, 12, 14, 20] do not have 500 required trades.

In [158]:
# Regression Analysis: Taker PnL
# Note, hover for regression details

graph_regression_by_threshold(
    df          = outs_df,        # Consider all Series thresholds
    side        = 'taker',
    graph_title = 'Outs',
)

Invalid Series Threshold: [9, 12, 14, 20] do not have 500 required trades.

### Analysis - **RBIs** in a MLB Game

In [159]:
# Market Analysis

market_analytics_df = market_analysis(
    df                = rbi_df,
    n_req_trades      = 500,   
    series_thresholds = True
)

market_analytics_df.sort_values(by = ['total_maker_pnl', 'maker_pct_net_ret', 'n_markets'], ascending = False)

Invalid Series Threshold: [3] do not have 500 required trades.

,series_threshold,start_date,end_date,n_trades,n_markets,contract_volume,avg_taker_trade_size,median_taker_trade_size,trades_per_market,total_taker_pnl,taker_pct_net_ret,taker_pct_winning,taker_win_avg_pct_ret,taker_loss_avg_pct_ret,total_maker_pnl,maker_pct_net_ret,maker_pct_winning,maker_win_avg_pct_ret,maker_loss_avg_pct_ret,maker_fee_pct_of_edge
0,1,2026-06-22 23:42:19.477986+00:00,2026-07-11 05:53:58.364019+00:00,5444,2099,178768.45,17.792370,4.7931,2.593616,-8799.3805,-8.89222,64.878766,54.491833,-97.929379,6149.2505,7.457015,34.276267,145.960650,-99.922185,8.198911
1,2,2026-06-23 01:23:56.930028+00:00,2026-07-11 05:54:34.965661+00:00,2315,1241,71350.12,13.386479,3.1488,1.865431,-4483.0083,-14.20460,72.656587,21.138681,-99.736894,3756.6083,9.271853,27.257019,77.560133,-100.000000,3.974348

In [160]:
# Comparison Analysis
# Note, hover over bars for t-test

graph_comparison_by_threshold(
    df            = rbi_df,
    graph_title   = "RBIs",
    n_req_trades  = 500,
    n_req_markets = 10,
    ci            = 0.95,
)

In [161]:
# Regression Analysis: Maker PnL
# Note, hover for regression details

graph_regression_by_threshold(
    df          = rbi_df,        # Consider all Series thresholds
    side        = 'maker',
    graph_title = 'RBIs',
)

Invalid Series Threshold: [3] do not have 500 required trades.

In [162]:
# Regression Analysis: Taker PnL
# Note, hover for regression details

graph_regression_by_threshold(
    df          = rbi_df,        # Consider all Series thresholds
    side        = 'taker',
    graph_title = 'RBIs',
)

Invalid Series Threshold: [3] do not have 500 required trades.