# **Kalshi NFL Player Prop Market Analysis**


### Section 1: Preprocessing

- Data cleaning and preparation


### Section 2: Dependent & Independent Variable Creation

- Engineering dependent and independent variables 


### Section 3: Analysis

- Market analysis

- Pre-Game Implied Outcome Probability vs. Hit Rate

- Multivariable Regression Analysis

In [1]:
import numpy as np
from utils import *
import pandas as pd

# Preprocessing

In [2]:
SERIES_TICKERS = {
    "anytime_td"      : "KXNFLANYTD",     # NFL: 'CMC scores at least one touchdown in a game'
    "two_plus_tds"    : "KXNFL2TD",       # NFL: 'CMC scores at least two touchdowns in a game'
    "first_td"        : "KXNFLFIRSTTD",   # NFL: 'CMC scores the first touchdown in a game'
    "rushing_yards"   : "KXNFLRSHYDS",    # NFL: 'Brock Purdy records 40+ rushing yards in a game'
    "receiving_yards" : "KXNFLRECYDS",    # NFL: 'CMC records 20+ receiving yards in a game'
    "passing_yards"   : "KXNFLPASSYDS",   # NFL: 'Brock Purdy records 200+ passing yards in a game'
    "passing_tds"     : "KXNFLPASSTDS",   # NFL: 'Brock Purdy throws 2+ touchdowns in a game'
    "receptions"      : "KXNFLREC",       # NFL: 'CMC records 4+ receptions in a game'
}
KALSHI_MAKER_FEE: float = 0.0175          # Kalshi maker fee for June 2026
KALSHI_TAKER_FEE: float = 0.07            # Kalshi taker fee for June 2026

### Preprocessing - Market Data

In [3]:
# Load in data

markets_df = pd.read_parquet('data/raw/historical_markets.parquet')

In [4]:
markets_df.head(2)

,can_close_early,close_time,created_time,custom_strike,early_close_condition,event_ticker,expected_expiration_time,expiration_time,expiration_value,last_price_dollars,...,updated_time,volume_24h_fp,volume_fp,yes_ask_dollars,yes_ask_size_fp,yes_bid_dollars,yes_bid_size_fp,yes_sub_title,floor_strike,subtitle
0,True,2026-02-09T03:47:16Z,2026-02-05T18:12:48.735839Z,{'football_player': 'f710b516-32b8-4cc7-ae91-8...,This market will close and expire early if the...,KXNFLANYTD-26FEB08SEANE,2026-02-09T02:30:00Z,2026-02-22T23:30:00Z,No,0.0100,...,2026-02-19T08:48:16.628714Z,0.00,107875.00,1.0000,0.00,0.0000,0.00,George Holani,NaN,None
1,True,2026-02-09T02:37:51Z,2026-02-05T18:12:48.432779Z,{'football_player': '42a1f21f-07d2-41e4-b204-c...,This market will close and expire early if the...,KXNFLANYTD-26FEB08SEANE,2026-02-09T02:30:00Z,2026-02-22T23:30:00Z,Yes,0.9900,...,2026-02-19T08:48:16.628714Z,0.00,182540.00,1.0000,0.00,0.0000,0.00,Mack Hollins,NaN,None

In [5]:
print(f"Date of First Market: {markets_df['created_time'].min()} \nDate of Last Market: {markets_df['created_time'].max()}")

Date of First Market: 2025-09-04T05:25:32.240887Z
Date of Last Market: 2026-02-08T21:56:53.118992Z

In [6]:
# Drop duplicate tickers

markets_df = markets_df.drop_duplicates(['ticker'])

In [7]:
# Filter for liquid markets

markets_df = markets_df[markets_df['volume_fp'].astype(float) > 0]

In [8]:
# Market is finalized

markets_df = markets_df[markets_df['status'] == 'finalized']

In [9]:
# Remove 'scalar' (i.e. the game was cancelled)

markets_df = markets_df[markets_df['result'] != 'scalar']

In [10]:
# Create series column

markets_df['series'] = markets_df['ticker'].apply(lambda x: x.split('-')[0])

markets_df['series'].value_counts()

series
KXNFLRECYDS      8875
KXNFLANYTD       5230
KXNFLREC         4978
KXNFLFIRSTTD     4736
KXNFLRSHYDS      4374
KXNFLPASSYDS     3135
KXNFL2TD         1953
KXNFLPASSTDS      738
KXNFLGAMESACK      14
Name: count, dtype: int64

In [11]:
# Drop 'sacks' and 'No Touchdown' markets

markets_df = markets_df.loc[(markets_df['series'] != "KXNFLGAMESACK") & (markets_df['yes_sub_title'] != "No Touchdown"), :]

In [12]:
# Clean up index

markets_df = markets_df.reset_index(drop=True)

In [13]:
# Create series threshold column

markets_df['series_threshold'] = np.where(
    markets_df['floor_strike'].notna(),
    np.ceil(markets_df['floor_strike']),
    np.nan
)
markets_df['series_threshold'] = markets_df['series_threshold'].astype('Int64')

In [14]:
# Clean dates

markets_df['close_time'] = pd.to_datetime(markets_df['close_time'], format='ISO8601', utc=True)

### Preprocessing - Trade Data

In [15]:
# Load in data

trades_df = pd.read_parquet('data/raw/historical_trades.parquet')

In [16]:
trades_df.head(2)

,count_fp,created_time,is_block_trade,no_price_dollars,taker_book_side,taker_outcome_side,taker_side,ticker,trade_id,yes_price_dollars
0,80.00,2026-02-09T03:08:50.42768Z,False,0.9900,bid,yes,yes,KXNFLANYTD-26FEB08SEANE-SEAESAUBERT81,8e43a171-1168-7940-7792-c01925e63cd3,0.0100
1,467.00,2026-02-09T02:57:25.323792Z,False,0.9900,bid,yes,yes,KXNFLANYTD-26FEB08SEANE-SEAESAUBERT81,073a6a01-9432-4957-b99e-bc62cc79ce28,0.0100

In [17]:
trades_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2276812 entries, 0 to 2276811
Data columns (total 10 columns):
 #   Column              Dtype
---  ------              -----
 0   count_fp            object
 1   created_time        object
 2   is_block_trade      bool
 3   no_price_dollars    object
 4   taker_book_side     object
 5   taker_outcome_side  object
 6   taker_side          object
 7   ticker              object
 8   trade_id            object
 9   yes_price_dollars   object
dtypes: bool(1), object(9)
memory usage: 158.5+ MB

In [18]:
# Convert data

numeric_cols = ['count_fp', 'yes_price_dollars', 'no_price_dollars']

trades_df[numeric_cols] = trades_df[numeric_cols].apply(pd.to_numeric)

trades_df['created_time'] = pd.to_datetime(trades_df['created_time'], format='ISO8601', utc=True)

In [19]:
# Drop duplicate trades

trades_df = trades_df.drop_duplicates(['trade_id']).reset_index(drop=True)

In [20]:
# Ensure no mixed side when grouping by 'ticker' and 'created_time'

mixed_side_groups = trades_df.groupby(['ticker', 'created_time'])['taker_outcome_side'].transform('nunique') > 1

print(f"Number of groups with mixed sides: {mixed_side_groups.sum()}")

Number of groups with mixed sides: 0

In [ ]:
# Resample trades that happened at the same time
#   - Here we assume that an order comes from the same party if it was created at the same time
#       - This assumption is defensible because trades are grouped at nanosecond-level timestamp 
#         precision, and no mixed sides (i.e. yes and no) occur when we aggregate by ticker and 
#         created time, suggesting these fills likely originate from a single order.
#   - This occurs when a larger order gets filled at different price levels
#   - Resample yes/no price by weighting yes/no price by dollar volume
#   - Create new variable to analyze order fill dispersion

TICK_SIZE: float = 0.01

trades_df['yes_dollar_vol'] = trades_df['count_fp'] * trades_df['yes_price_dollars']
trades_df['no_dollar_vol']  = trades_df['count_fp'] * trades_df['no_price_dollars']

trades_df = trades_df.groupby(['ticker', 'created_time'], as_index=False).agg(
    # Aggregate previous variables
    count_fp            = ('count_fp', 'sum'),
    yes_dollar_vol      = ('yes_dollar_vol', 'sum'),
    no_dollar_vol       = ('no_dollar_vol', 'sum'),
    taker_book_side     = ('taker_book_side', 'first'),
    taker_outcome_side  = ('taker_outcome_side', 'first'),
    taker_side          = ('taker_side', 'first'),
    trade_id            = ('trade_id', 'first'),

    # Create new variables
    levels_touched      = ('yes_price_dollars', 'nunique'), 
    yes_price_max       = ('yes_price_dollars', 'max'),
    yes_price_min       = ('yes_price_dollars', 'min')
)

# Aggregated yes/no price
trades_df['yes_price_dollars'] = (trades_df['yes_dollar_vol'] / trades_df['count_fp']).round(2)
trades_df['no_price_dollars']  = (trades_df['no_dollar_vol']  / trades_df['count_fp']).round(2)

# Order fill dispersion variable: price delta in ticks
trades_df['price_delta_ticks'] = (
    (trades_df['yes_price_max'] - trades_df['yes_price_min']) / TICK_SIZE
).round().astype(int)

trades_df = trades_df.drop(columns=['yes_dollar_vol', 'no_dollar_vol', 'yes_price_max', 'yes_price_min'])

In [22]:
# Create game date, away team, and home team columns

date_teams = trades_df['ticker'].str.split('-').str[1]

year  = date_teams.str[0:2]      # "26"
month = date_teams.str[2:5]      # "JUN"
day   = date_teams.str[5:7]      # "13"

trades_df.loc[:, 'game_date'] = pd.to_datetime(
    year + month + day,
    format='%y%b%d'
)

teams_code = date_teams.str[7:]
trades_df[['away_team', 'home_team']] = pd.DataFrame(
    teams_code.apply(find_teams).tolist(),
    index=trades_df.index
)

trades_df.head(2)

,ticker,created_time,count_fp,taker_book_side,taker_outcome_side,taker_side,trade_id,levels_touched,yes_price_dollars,no_price_dollars,price_delta_ticks,game_date,away_team,home_team
0,KXNFL2TD-25DEC01NYGNE-NEHHENRY85,2025-11-28 23:11:48.211379+00:00,3.0,bid,yes,yes,f6302110-aa18-462e-5d03-1e47d79b334a,1,0.06,0.94,0,2025-12-01,NYG,NE
1,KXNFL2TD-25DEC01NYGNE-NEHHENRY85,2025-12-01 12:48:44.199290+00:00,164.0,bid,yes,yes,8520efe0-697c-77e0-c5f5-42b5d202a02a,2,0.06,0.94,1,2025-12-01,NYG,NE

### Preprocessing - NFL Game Start Data

In [23]:
nfl_schedule_df = pd.read_parquet('data/raw/nfl_start_times.parquet')

In [24]:
# Create game start time column

nfl_schedule_df['game_start_time'] = (
    pd.to_datetime(
        nfl_schedule_df['gameday'].astype(str) + ' ' + nfl_schedule_df['gametime'].astype(str),
        format='%Y-%m-%d %H:%M'
    )
    .dt.tz_localize('America/New_York')
    .dt.tz_convert('UTC')
)

In [25]:
# Clean up data frame

nfl_schedule_df = (
    nfl_schedule_df[
        ['gameday', 'game_start_time', 'away_team', 'home_team']
    ]
    .astype({
        "gameday"   : "datetime64[ns, UTC]",
        "away_team" : "str",
        "home_team" : "str",
    })
    .rename(columns={
        "gameday"   : "game_date",
    })
)

nfl_schedule_df["game_date"] = nfl_schedule_df["game_date"].dt.tz_localize(None)

nfl_schedule_df['away_team'] = nfl_schedule_df['away_team'].replace('JAX', 'JAC')
nfl_schedule_df['home_team'] = nfl_schedule_df['home_team'].replace('JAX', 'JAC')

nfl_schedule_df

     game_date           game_start_time away_team home_team
0   2025-09-04 2025-09-05 00:20:00+00:00       DAL       PHI
1   2025-09-05 2025-09-06 00:00:00+00:00        KC       LAC
2   2025-09-07 2025-09-07 17:00:00+00:00        TB       ATL
3   2025-09-07 2025-09-07 17:00:00+00:00       CIN       CLE
4   2025-09-07 2025-09-07 17:00:00+00:00       MIA       IND
..         ...                       ...       ...       ...
280 2026-01-18 2026-01-18 23:30:00+00:00        LA       CHI
281 2026-01-18 2026-01-18 20:00:00+00:00       HOU        NE
282 2026-01-25 2026-01-25 20:00:00+00:00        NE       DEN
283 2026-01-25 2026-01-25 23:30:00+00:00        LA       SEA
284 2026-02-08 2026-02-08 23:30:00+00:00       SEA        NE

[285 rows x 4 columns]

In [26]:
# Add game start time column to trades data frame

trades_df = trades_df.merge(
    nfl_schedule_df,
    on=['game_date', 'away_team', 'home_team'],
    how='left'    
)

In [27]:
# Data validation

print(f"Missing game start time for {trades_df['game_start_time'].isna().sum():,} out of {len(trades_df['game_start_time']):,} trades.")

Missing game start time for 0 out of 2,034,973 trades.

In [28]:
# Merge data frames

merged = trades_df.merge(markets_df, on='ticker', how='left')

required_cols = [
    'ticker', 'created_time', 'count_fp', 'close_time', 'series',
    'game_start_time', 'result', 'yes_price_dollars', 'no_price_dollars',
    'taker_outcome_side', 
]

kalshi_df = merged[[
    'ticker', 'created_time_x', 'count_fp', 'close_time', 'series', 'game_start_time', 'result', 'yes_price_dollars',
    'no_price_dollars','floor_strike', 'taker_outcome_side', 'series_threshold', 'price_delta_ticks', 'levels_touched'
]].rename(columns={'created_time_x': 'created_time'}).dropna(subset=required_cols).sort_values(by=['created_time']).reset_index(drop=True).copy()

kalshi_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2007615 entries, 0 to 2007614
Data columns (total 14 columns):
 #   Column              Dtype
---  ------              -----
 0   ticker              object
 1   created_time        datetime64[ns, UTC]
 2   count_fp            float64
 3   close_time          datetime64[ns, UTC]
 4   series              object
 5   game_start_time     datetime64[ns, UTC]
 6   result              object
 7   yes_price_dollars   float64
 8   no_price_dollars    float64
 9   floor_strike        float64
 10  taker_outcome_side  object
 11  series_threshold    Int64
 12  price_delta_ticks   int64
 13  levels_touched      int64
dtypes: Int64(1), datetime64[ns, UTC](3), float64(4), int64(2), object(4)
memory usage: 216.4+ MB

# Dependent & Independent Variable Creation

In [29]:
# Independent: Number of price levels touched (per order fill)
# Note, heavy tail

kalshi_df['levels_touched'].value_counts()

levels_touched
1     1918724
2       73135
3       10273
4        2920
5        1114
6         607
7         305
8         172
9         107
10         70
11         61
12         43
13         28
14         16
15         12
16         11
18          6
17          3
27          2
19          2
20          1
25          1
21          1
23          1
Name: count, dtype: int64

In [30]:
# Independent: Number of price levels touched (per order fill)

kalshi_df['log_levels_touched'] = np.log(kalshi_df['levels_touched'])   # Apply a log transformation to reduce heavy tail

print(np.isinf(kalshi_df['log_levels_touched']).sum(), 'infinite values')
print(kalshi_df['log_levels_touched'].isna().sum(), 'NaN values')

0 infinite values
0 NaN values

In [31]:
# Independent: Price delta in ticks (per order fill)
# Note, heavy tail

kalshi_df['price_delta_ticks'].value_counts()

price_delta_ticks
0     1918724
1       55668
2       10441
3        4622
4        2681
       ...
94          7
91          7
97          7
96          5
92          3
Name: count, Length: 99, dtype: int64

In [32]:
# Independent: Price delta in ticks (per order fill)

kalshi_df['log_price_delta_ticks'] = np.log1p(kalshi_df['price_delta_ticks'])   # Apply a log transformation to reduce heavy tail

print(np.isinf(kalshi_df['log_price_delta_ticks']).sum(), 'infinite values')
print(kalshi_df['log_price_delta_ticks'].isna().sum(), 'NaN values')

0 infinite values
0 NaN values

In [33]:
# Independent: Number of trades per market (ticker)

kalshi_df['n_trades_in_market'] = kalshi_df.groupby('ticker')['ticker'].transform('count')

In [34]:
# Independent: Number of trades per market (ticker)
# Note, heavy tail

log_bins = np.logspace(
    np.log10(kalshi_df['n_trades_in_market'].min()), 
    np.log10(kalshi_df['n_trades_in_market'].max()), 
    num=21
)

log_bin_counts = (
    pd.cut(kalshi_df['n_trades_in_market'], bins=log_bins, include_lowest=True)
    .value_counts()
    .sort_index()
    .reset_index()
)
log_bin_counts.columns = ["log_bin", "log_count"]

linear_bin_counts = (
    pd.cut(kalshi_df['n_trades_in_market'], bins=20)
    .value_counts()
    .sort_index()
    .reset_index()
)
linear_bin_counts.columns = ["linear_bin", "linear_count"]

pd.concat([log_bin_counts, linear_bin_counts], axis=1)

                  log_bin  log_count           linear_bin  linear_count
0          (0.999, 1.653]       3980   (-22.131, 1157.55]       1438667
1          (1.653, 2.732]       5896    (1157.55, 2314.1]        242312
2          (2.732, 4.515]      14172    (2314.1, 3470.65]         92560
3          (4.515, 7.462]      23908    (3470.65, 4627.2]         66641
4         (7.462, 12.333]      38931    (4627.2, 5783.75]         42261
5        (12.333, 20.383]      55374    (5783.75, 6940.3]         18995
6        (20.383, 33.688]      73313    (6940.3, 8096.85]         15149
7        (33.688, 55.678]     105117    (8096.85, 9253.4]             0
8        (55.678, 92.023]     133412   (9253.4, 10409.95]         20067
9       (92.023, 152.092]     173500  (10409.95, 11566.5]         10769
10     (152.092, 251.372]     205236  (11566.5, 12723.05]             0
11     (251.372, 415.459]     207031  (12723.05, 13879.6]             0
12     (415.459, 686.655]     212605  (13879.6, 15036.15]             0
13    (686.655, 1134.878]     181597  (15036.15, 16192.7]         15144
14   (1134.878, 1875.685]     191304  (16192.7, 17349.25]             0
15   (1875.685, 3100.063]     125743  (17349.25, 18505.8]             0
16   (3100.063, 5123.671]     104153  (18505.8, 19662.35]             0
17   (5123.671, 8468.215]      61313  (19662.35, 20818.9]             0
18  (8468.215, 13995.955]      30836  (20818.9, 21975.45]         21918
19   (13995.955, 23132.0]      60194  (21975.45, 23132.0]         23132

In [35]:
# Independent: Number of trades per market (ticker)

kalshi_df['log_n_trades_in_market'] = np.log(kalshi_df['n_trades_in_market'])   # Apply a log transformation to reduce heavy tail

print(np.isinf(kalshi_df['log_n_trades_in_market']).sum(), 'infinite values')
print(kalshi_df['log_n_trades_in_market'].isna().sum(), 'NaN values')

0 infinite values
0 NaN values

In [36]:
# Independent: Market Completion Percentage

kalshi_df['n_cum_trades'] = kalshi_df.groupby('ticker').cumcount()  # Cumulative number of trades per market (ticker)

kalshi_df['market_completion_pct'] = kalshi_df['n_cum_trades'] / kalshi_df['n_trades_in_market']

kalshi_df[['ticker', 'market_completion_pct']].sample(n = 3)

                                             ticker  market_completion_pct
1548325  KXNFLPASSYDS-26JAN18LACHI-LAMSTAFFORD9-225               0.952381
393846     KXNFLRECYDS-25NOV27CINBAL-BALDHENRY22-30               0.875000
1134481   KXNFLRECYDS-26JAN11BUFJAC-BUFKSHAKIR10-60               0.151899

In [37]:
# Independent: Post kickoff dummy

kalshi_df['is_post_kickoff_dummy'] = (kalshi_df['created_time'] > kalshi_df['game_start_time']).astype(int)

kalshi_df[['ticker', 'is_post_kickoff_dummy', 'created_time', 'game_start_time']].sample(n = 3)

,ticker,is_post_kickoff_dummy,created_time,game_start_time
1353619,KXNFLPASSTDS-26JAN17BUFDEN-DENBNIX10-1,0,2026-01-17 10:26:26.295217+00:00,2026-01-17 21:30:00+00:00
1393177,KXNFLANYTD-26JAN17BUFDEN-BUFJALLEN17,1,2026-01-17 22:15:22.570241+00:00,2026-01-17 21:30:00+00:00
1182949,KXNFLFIRSTTD-26JAN11SFPHI-SFCMCCAFFREY23,0,2026-01-11 21:17:38.121656+00:00,2026-01-11 21:30:00+00:00

In [38]:
# Independent: Taker outcome side dummy

kalshi_df['taker_outcome_side_dummy'] = (kalshi_df['taker_outcome_side'] == 'yes').astype(int)

kalshi_df[['ticker', 'taker_outcome_side', 'taker_outcome_side_dummy']].sample(n = 3)

,ticker,taker_outcome_side,taker_outcome_side_dummy
1303931,KXNFLFIRSTTD-26JAN12HOUPIT-PITDMETCALF4,yes,1
1827907,KXNFLFIRSTTD-26FEB08SEANE-SEAJSMITHNJIGBA11,yes,1
1839101,KXNFLANYTD-26FEB08SEANE-NEDMAYE10,yes,1

In [39]:
# Independent: Maker outcome side dummy

kalshi_df['maker_outcome_side'] = np.where(kalshi_df['taker_outcome_side'] == 'yes', 'no', 'yes')

kalshi_df['maker_outcome_side_dummy'] = (kalshi_df['maker_outcome_side'] == 'yes').astype(int)

kalshi_df[['ticker', 'maker_outcome_side', 'maker_outcome_side_dummy']].sample(n = 3)

,ticker,maker_outcome_side,maker_outcome_side_dummy
268498,KXNFLANYTD-25NOV03ARIDAL-DALJFERGUSON87,no,0
778817,KXNFLPASSTDS-25DEC28SEACAR-SEASDARNOLD14-2,no,0
1368739,KXNFLANYTD-26JAN17BUFDEN-BUFKCOLEMAN0,no,0

In [40]:
# Independent: Trade Size (count)
# Note, heavy tail

log_bins = np.logspace(
    np.log10(kalshi_df['count_fp'].min()), 
    np.log10(kalshi_df['count_fp'].max()), 
    num=21
)

log_bin_counts = (
    pd.cut(kalshi_df['count_fp'], bins=log_bins, include_lowest=True)
    .value_counts()
    .sort_index()
    .reset_index()
)
log_bin_counts.columns = ["log_bin", "log_count"]

linear_bin_counts = (
    pd.cut(kalshi_df['count_fp'], bins=20)
    .value_counts()
    .sort_index()
    .reset_index()
)
linear_bin_counts.columns = ["linear_bin", "linear_count"]

pd.concat([log_bin_counts, linear_bin_counts], axis=1)

                     log_bin  log_count             linear_bin  linear_count
0             (0.999, 1.899]      77618   (-370.299, 18565.95]       2007232
1             (1.899, 3.606]      78853    (18565.95, 37130.9]           293
2             (3.606, 6.846]     117145    (37130.9, 55695.85]            69
3              (6.846, 13.0]     256828    (55695.85, 74260.8]            12
4             (13.0, 24.685]     279889    (74260.8, 92825.75]             4
5           (24.685, 46.872]     313087   (92825.75, 111390.7]             3
6           (46.872, 89.003]     291758  (111390.7, 129955.65]             0
7          (89.003, 169.001]     263348  (129955.65, 148520.6]             1
8         (169.001, 320.905]     160614  (148520.6, 167085.55]             0
9         (320.905, 609.344]      90226  (167085.55, 185650.5]             0
10       (609.344, 1157.041]      42670  (185650.5, 204215.45]             0
11      (1157.041, 2197.025]      21320  (204215.45, 222780.4]             0
12      (2197.025, 4171.778]       8686  (222780.4, 241345.35]             0
13      (4171.778, 7921.501]       3672  (241345.35, 259910.3]             0
14     (7921.501, 15041.589]       1369  (259910.3, 278475.25]             0
15    (15041.589, 28561.431]        372  (278475.25, 297040.2]             0
16    (28561.431, 54233.322]        138  (297040.2, 315605.15]             0
17   (54233.322, 102979.897]         20  (315605.15, 334170.1]             0
18  (102979.897, 195541.392]          1  (334170.1, 352735.05]             0
19    (195541.392, 371300.0]          1  (352735.05, 371300.0]             1

In [41]:
# Independent: Trade Size (count)

kalshi_df['log_count_fp'] = np.log(kalshi_df['count_fp'])   # Apply a log transformation to reduce heavy tail

print(np.isinf(kalshi_df['log_count_fp']).sum(), 'infinite values')
print(kalshi_df['log_count_fp'].isna().sum(), 'NaN values')

0 infinite values
0 NaN values

In [42]:
# Dependent: Maker PnL & Return

kalshi_df['maker_price'] = np.where(
    kalshi_df['maker_outcome_side'] == 'yes',
    kalshi_df['yes_price_dollars'],
    kalshi_df['no_price_dollars']
)

kalshi_df['maker_dollar_amt'] = kalshi_df['count_fp'] * np.where(
    kalshi_df['maker_outcome_side'] == 'yes', 
    kalshi_df['yes_price_dollars'],
    kalshi_df['no_price_dollars']
)

kalshi_df["maker_fee"] = np.ceil(KALSHI_MAKER_FEE * kalshi_df["count_fp"] * kalshi_df['maker_price'] * (1 - kalshi_df['maker_price']) * 100) / 100

kalshi_df["maker_revenue"] = kalshi_df["count_fp"] * np.where(
    ((kalshi_df['taker_outcome_side'] == "yes") & (kalshi_df["result"] == "no")) |
    ((kalshi_df['taker_outcome_side'] == "no") & (kalshi_df["result"] == "yes")),
    1,
    0
)

kalshi_df["maker_pnl"] = kalshi_df["maker_revenue"] - kalshi_df["maker_dollar_amt"] - kalshi_df["maker_fee"]

kalshi_df["maker_net_return"] = kalshi_df["maker_pnl"] / (kalshi_df["maker_dollar_amt"] + kalshi_df["maker_fee"])

kalshi_df['maker_pnl_per_contract'] = kalshi_df['maker_pnl'] / kalshi_df['count_fp']

kalshi_df[['ticker', 'maker_dollar_amt', 'maker_fee', 'maker_revenue', 'maker_pnl', 'maker_net_return', 'maker_pnl_per_contract']].sample(n = 3)

,ticker,maker_dollar_amt,maker_fee,maker_revenue,maker_pnl,maker_net_return,maker_pnl_per_contract
1129905,KXNFLANYTD-26JAN12HOUPIT-PITARODGERS8,293.28,0.31,312.0,18.41,0.062706,0.059006
1382867,KXNFLANYTD-26JAN17BUFDEN-BUFKCOLEMAN0,24.94,0.07,0.0,-25.01,-1.000000,-0.862414
811640,KXNFLANYTD-25DEC28PHIBUF-PHIJHURTS1,136.88,0.99,232.0,94.13,0.682745,0.405733

In [43]:
# Dependent: Taker PnL & Return

kalshi_df['taker_price'] = np.where(
    kalshi_df['taker_outcome_side'] == 'yes',
    kalshi_df['yes_price_dollars'],
    kalshi_df['no_price_dollars']
)

kalshi_df['taker_dollar_amt'] = kalshi_df['count_fp'] * np.where(
    kalshi_df['taker_outcome_side'] == 'yes',
    kalshi_df["yes_price_dollars"],
    kalshi_df["no_price_dollars"]
)

kalshi_df["taker_fee"] = np.ceil(KALSHI_TAKER_FEE * kalshi_df["count_fp"] * kalshi_df['taker_price'] * (1 - kalshi_df['taker_price']) * 100) / 100

kalshi_df["taker_revenue"] = kalshi_df["count_fp"] * np.where(
    ((kalshi_df['taker_outcome_side'] == 'yes') & (kalshi_df["result"] == "yes")) |
    ((kalshi_df['taker_outcome_side'] == 'no') & (kalshi_df["result"] == "no")),
    1,
    0
)

kalshi_df["taker_pnl"] = kalshi_df["taker_revenue"] - kalshi_df["taker_dollar_amt"] - kalshi_df["taker_fee"]

kalshi_df["taker_net_return"] = kalshi_df["taker_pnl"] / (kalshi_df["taker_dollar_amt"] + kalshi_df["taker_fee"])

kalshi_df['taker_pnl_per_contract'] = kalshi_df['taker_pnl'] / kalshi_df['count_fp']

kalshi_df[['ticker', 'taker_dollar_amt', 'taker_fee', 'taker_revenue', 'taker_pnl', 'taker_net_return', 'taker_pnl_per_contract']].sample(n = 3)

,ticker,taker_dollar_amt,taker_fee,taker_revenue,taker_pnl,taker_net_return,taker_pnl_per_contract
1571154,KXNFLFIRSTTD-26JAN25LASEA-SEAJSMITHNJIGBA11,4.80,0.30,0.0,-5.10,-1.0,-0.127500
638581,KXNFLREC-25DEC22SFIND-INDJTAYLOR28-5,0.78,0.05,0.0,-0.83,-1.0,-0.276667
17993,KXNFLANYTD-25SEP08MINCHI-MINJMASON27,1.89,0.11,0.0,-2.00,-1.0,-0.222222

# Analysis


### Market Analysis

- Start Date: First trade placed for each series or series threshold.

- End Date: Last trade placed for each series or series threshold.

- $n$ Trades: Number of trades placed for each series or series threshold.

- $n$ Markets: Number of unique markets (tickers) included within each series or series threshold.

- Contract Volume: Total number of contracts transacted on a series or series threshold basis.

- Average Taker Trade Size: Average trade size of a taker in dollars on a series or series threshold basis.

- Median Taker Trade Size: Median trade size of a taker in dollars on a series or series threshold basis.

- Trades per Market: $n$ trades divided by $n$ markets.

- Total Taker PnL: Summation of a taker's profit and loss across all trades; where, profit and loss for a single trade is defined as $$ \text{contracts} \times \text{outcome (1 if taker's side wins, else 0)} - \text{contracts} \times \text{price paid} - \text{taker fees} $$

- Taker Net Return (%): Total taker PnL divided by total taker capital at risk (dollar amount paid plus fees), expressed as a percentage. Represents the aggregate, dollar-weighted return across all taker trades in the series or series threshold.

- Taker Win Rate (%): Percentage of taker trades with positive PnL.

- Taker Winning Trades Average Return (%): Average return of trades where a taker profited (i.e. PnL > 0).

- Taker Losing Trades Average Return (%): Average return of trades where a taker did not profit (i.e. PnL $\leq$ 0).

- Total Maker PnL: Summation of a maker's profit and loss across all trades; where, profit and loss for a single trade is defined as $$ \text{contracts} \times \text{outcome (1 if maker's side wins, else 0)} - \text{contracts} \times \text{price paid} - \text{maker fees} $$

- Maker Net Return (%): Total maker PnL divided by total maker capital at risk (dollar amount paid plus fees), expressed as a percentage. Represents the aggregate, dollar-weighted return across all maker trades in the series or series threshold.

- Maker Win Rate (%): Percentage of maker trades with positive PnL.

- Maker Winning Trades Average Return (%): Average return of trades where a maker profited (i.e. PnL > 0).

- Maker Losing Trades Average Return (%): Average return of trades where a maker did not profit (i.e. PnL $\leq$ 0).

- Maker Fee % of Edge: Total maker fees paid, as a percentage of the maker's gross edge (maker revenue less maker dollar cost, before fees). Represents how much of the maker's raw trading edge is given back in fees.


### Pre-Game Implied Outcome Probability vs. Hit Rate

- <span style="color:#E29A4A; font-weight: bold; font-style: normal;">Pre-Game Market Implied Probability</span>:

    - Seeks to represent how likely the market believes the outcome to be.

    - Let $T_{pg,k} = \{(p_i, c_i)\}_{i=1}^{n}$ be the set of all observed pre-game trades for the $k^{th}$ market, where $p_i$ is the 'Yes' price and $c_i$ is the contract quantity transacted for trade $i$. The contract-weighted average pre-game 'Yes' price by market is then defined as: $$ \frac{\sum_{i=1}^{n} p_i \cdot c_i}{\sum_{i=1}^{n} c_i} $$

    - Then, the pre-game market implied probability for a series with $m$ markets can be defined: $$ \frac{1}{m} \sum_{k=1}^{m} \frac{\sum_{i=1}^{n_k} p_{i,k} \cdot c_{i,k}}{\sum_{i=1}^{n_k} c_{i,k}} $$

- <span style="color:#9096ED; font-weight: bold; font-style: normal;">Hit Rate</span>:
    - Let $G = \{g_1, \dots, g_m\}$ be the set of all finalized markets in the series, and let $y_k \in \{0, 1\}$ indicate whether market $k$ resolved 'Yes'. The hit rate is then defined as: $$ \frac{1}{m} \sum_{k=1}^{m} y_k $$


### Multivariable Regression Analysis

- **Dependent Variable(s)**

    - _Maker profit and loss per contract (maker_pnl_per_contract)_: Defined as maker revenue less the maker's dollar position size and maker fees paid on the position, divided by total contracts. Seeks to avoid extreme returns to reduce outliers, and to normalize by position size to reduce heteroskedasticity.

    - _Taker profit and loss per contract (taker_pnl_per_contract)_: Defined as taker revenue less the taker's dollar position size and taker fees paid on the position, divided by total contracts. Seeks to avoid extreme returns to reduce outliers, and to normalize by position size to reduce heteroskedasticity.

- **Independent Variables**

    - <span style="color:#FDFD96"><em>Outcome side dummy (maker_outcome_side_dummy/taker_outcome_side_dummy)</em></span>: $1$ if a trade is taken on the 'yes' side, $0$ if 'no'. A dummy variable, specified by maker/taker, which measures the effect of side on profitability.

    - <span style="color:#5A99E0"><em>Market completion percentage (market_completion_pct)</em></span>: Defined as the number of trades placed prior to this trade, divided by the total number of trades the market will ever have. A variable seeking to understand the effect market lifecycle stage (maturity) has on profitability, independent of the market's overall size.

    - <span style="color:#5A99E0"><em>Post kickoff dummy (is_post_kickoff_dummy)</em></span>: Defined as $1$ when a trade is placed after game start time and $0$ otherwise. A dummy variable seeking to incorporate pre-game and in-game/post-kickoff dynamics into market lifecycle stage (maturity).

    - <span style="color:#50E3C2"><em>Trade size (log_count_fp)</em></span>: Defined as the number of contracts. A variable seeking to understand whether larger trades signal a more sophisticated trader. In other words, how does trade size measured by contract count affect profitability. *Note, a log transformation was applied to reduce a long right tail.*

    - <span style="color:#FF6B6B"><em>Number of trades per market (log_n_trades_in_market)</em></span>: Defined as the total number of trades in each market (ticker). A variable seeking to understand the effect market size has on profitability. *Note, a log transformation was applied to reduce a long right tail.*

    - <span style="color:#F7A2C0"><em>Number of price levels touched (log_levels_touched)</em></span>: Defined as the number of unique prices within a cluster of trades sharing the same market and timestamp, used as a proxy for a single aggressive order filled across multiple price levels. A variable seeking to capture breadth of order fill dispersion, how many distinct price levels were consumed, and its effect on profitability. *Note, a log transformation was applied to reduce a long right tail.*

    - <span style="color:#F7A2C0"><em>Price delta in ticks (log_price_delta_ticks)</em></span>: Defined as the maximum price less the minimum price within the same trade cluster, divided by tick size. A variable seeking to capture depth of order fill dispersion, how far price moved as a result, and its effect on profitability. *Note, a log1p transformation was applied to accommodate observations with zero price movement, while reducing a long right tail.*

In [44]:
# Create 'prop' data frames

prop_dfs = {
    name: kalshi_df[kalshi_df['series'] == ticker].reset_index(drop=True).copy()
    for name, ticker in SERIES_TICKERS.items()
}

anytime_td_df      = prop_dfs['anytime_td']
two_plus_tds_df    = prop_dfs['two_plus_tds']
first_td_df        = prop_dfs['first_td']
rushing_yards_df   = prop_dfs['rushing_yards']
receiving_yards_df = prop_dfs['receiving_yards']
passing_yards_df   = prop_dfs['passing_yards']
passing_tds_df     = prop_dfs['passing_tds']
receptions_df      = prop_dfs['receptions']

### Analysis - **All** Prop Markets for a NFL Game

In [45]:
# Market Analysis

market_analytics_df = market_analysis(
    df                = kalshi_df,
    n_req_trades      = 500, 
    series_thresholds = False  
)

market_analytics_df.melt()

                   variable                             value
0                start_date  2025-09-04 09:53:05.465938+00:00
1                  end_date  2026-02-09 03:25:36.022952+00:00
2                  n_trades                           2007615
3                 n_markets                             33598
4           contract_volume                       289992054.0
5      avg_taker_trade_size                         49.343005
6   median_taker_trade_size                              9.24
7         trades_per_market                         59.754003
8           total_taker_pnl                       -9379285.79
9         taker_pct_net_ret                         -9.197467
10        taker_pct_winning                         32.201343
11    taker_win_avg_pct_ret                        149.060937
12   taker_loss_avg_pct_ret                            -100.0
13          total_maker_pnl                        5727652.91
14        maker_pct_net_ret                          2.988338
15        maker_pct_winning                         67.798657
16    maker_win_avg_pct_ret                          61.95937
17   maker_loss_avg_pct_ret                            -100.0
18    maker_fee_pct_of_edge                          11.39477

In [46]:
# Comparison Analysis
# Note, hover over bars for t-test

graph_comparison(
    df           = kalshi_df,
    graph_title  = "All NFL",
    n_req_trades = 500,
    ci           = 0.95,
)

In [47]:
# Regression Analysis: Maker PnL
# Note, hover for regression details

graph_regression(
    df           = kalshi_df,
    graph_title  = "All NFL",
    side         = 'maker',
    n_req_trades = 500,
    show_const   = False
)

In [48]:
# Regression Analysis: Taker PnL
# Note, hover for regression details

graph_regression(
    df           = kalshi_df,
    graph_title  = "All NFL",
    side         = 'taker',
    n_req_trades = 500,
    show_const   = False
)

### Analysis - **Anytime Touchdown** in a NFL Game

In [49]:
# Market Analysis

market_analytics_df = market_analysis(
    df           = anytime_td_df,
    n_req_trades = 500,
    series_thresholds = False 
)

market_analytics_df.melt()

                   variable                             value
0                start_date  2025-09-04 10:05:28.893598+00:00
1                  end_date  2026-02-09 03:25:16.945587+00:00
2                  n_trades                            886443
3                 n_markets                              5010
4           contract_volume                       125579440.0
5      avg_taker_trade_size                         49.793743
6   median_taker_trade_size                              9.25
7         trades_per_market                        176.934731
8           total_taker_pnl                        -5390146.4
9         taker_pct_net_ret                        -11.853009
10        taker_pct_winning                         29.273287
11    taker_win_avg_pct_ret                         167.51557
12   taker_loss_avg_pct_ret                            -100.0
13          total_maker_pnl                        3717227.49
14        maker_pct_net_ret                          4.545542
15        maker_pct_winning                         70.726713
16    maker_win_avg_pct_ret                         57.221827
17   maker_loss_avg_pct_ret                            -100.0
18    maker_fee_pct_of_edge                          8.319919

In [50]:
# Comparison Analysis
# Note, hover over bars for t-test

graph_comparison(
    df           = anytime_td_df,
    graph_title  = "Anytime Touchdown",
    n_req_trades = 500,
    ci           = 0.95,
)

In [51]:
# Regression Analysis: Maker PnL
# Note, hover for regression details

graph_regression(
    df           = anytime_td_df,
    graph_title  = "Anytime Touchdown",
    side         = 'maker',
    n_req_trades = 500,
    show_const   = False
)

In [52]:
# Regression Analysis: Taker PnL
# Note, hover for regression details

graph_regression(
    df           = anytime_td_df,
    graph_title  = "Anytime Touchdown",
    side         = 'taker',
    n_req_trades = 500,
    show_const   = False
)

### Analysis - **2+ Touchdowns** in a NFL Game

In [53]:
# Market Analysis

market_analytics_df = market_analysis(
    df           = two_plus_tds_df,
    n_req_trades = 500,   
)

market_analytics_df.melt()

                   variable                             value
0                start_date  2025-09-04 12:59:16.820615+00:00
1                  end_date  2026-02-09 03:22:58.232150+00:00
2                  n_trades                            161993
3                 n_markets                              1952
4           contract_volume                        30407115.0
5      avg_taker_trade_size                         37.436303
6   median_taker_trade_size                               6.0
7         trades_per_market                         82.988217
8           total_taker_pnl                       -1030456.37
9         taker_pct_net_ret                        -16.458098
10        taker_pct_winning                         21.813288
11    taker_win_avg_pct_ret                        212.233415
12   taker_loss_avg_pct_ret                            -100.0
13          total_maker_pnl                         783967.98
14        maker_pct_net_ret                           3.21397
15        maker_pct_winning                         78.186712
16    maker_win_avg_pct_ret                         28.328277
17   maker_loss_avg_pct_ret                            -100.0
18    maker_fee_pct_of_edge                          5.974856

In [54]:
# Comparison Analysis
# Note, hover over bars for t-test

graph_comparison(
    df           = two_plus_tds_df,
    graph_title  = "2+ Touchdowns",
    n_req_trades = 500,
    ci           = 0.95,
)

In [55]:
# Regression Analysis: Maker PnL
# Note, hover for regression details

graph_regression(
    df           = two_plus_tds_df,
    graph_title  = "2+ Touchdowns",
    side         = 'maker',
    n_req_trades = 500,
    show_const   = False
)

In [56]:
# Regression Analysis: Taker PnL
# Note, hover for regression details

graph_regression(
    df           = two_plus_tds_df,
    graph_title  = "2+ Touchdowns",
    side         = 'taker',
    n_req_trades = 500,
    show_const   = False
)

### Analysis - **First Touchdown** in a NFL Game

In [57]:
# Market Analysis

market_analytics_df = market_analysis(
    df           = first_td_df,
    n_req_trades = 500,   
)

market_analytics_df.melt()

                   variable                             value
0                start_date  2025-09-04 09:53:05.465938+00:00
1                  end_date  2026-02-09 02:29:35.056681+00:00
2                  n_trades                            280954
3                 n_markets                              4536
4           contract_volume                        46275290.0
5      avg_taker_trade_size                         23.482916
6   median_taker_trade_size                              4.68
7         trades_per_market                         61.938713
8           total_taker_pnl                         -853147.1
9         taker_pct_net_ret                         -12.53341
10        taker_pct_winning                         10.243314
11    taker_win_avg_pct_ret                        553.894198
12   taker_loss_avg_pct_ret                            -100.0
13          total_maker_pnl                         590381.76
14        maker_pct_net_ret                          1.485945
15        maker_pct_winning                         89.756686
16    maker_win_avg_pct_ret                         16.521776
17   maker_loss_avg_pct_ret                            -100.0
18    maker_fee_pct_of_edge                          8.295363

In [58]:
# Comparison Analysis
# Note, hover over bars for t-test

graph_comparison(
    df           = first_td_df,
    graph_title  = "First Touchdown",
    n_req_trades = 500,
    ci           = 0.95,
)

In [59]:
# Regression Analysis: Maker PnL
# Note, hover for regression details

graph_regression(
    df           = first_td_df,
    graph_title  = "First Touchdown",
    side         = 'maker',
    n_req_trades = 500,
    show_const   = False
)

In [60]:
# Regression Analysis: Taker PnL
# Note, hover for regression details

graph_regression(
    df           = first_td_df,
    graph_title  = "First Touchdown",
    side         = 'taker',
    n_req_trades = 500,
    show_const   = False
)

### Analysis - **Rushing Yards** in a NFL Game

In [61]:
# Market Analysis

market_analytics_df = market_analysis(
    df                = rushing_yards_df,
    n_req_trades      = 500,   
    series_thresholds = True
)

market_analytics_df.sort_values(by = ['total_maker_pnl', 'maker_pct_net_ret', 'n_markets'], ascending = False)

Invalid Series Threshold: [2, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 18, 19, 21, 22, 23, 24, 25, 26, 27, 28, 29, 31, 32, 33, 34, 35, 36, 37, 38, 39, 41, 42, 44, 46, 47, 48, 49, 51, 52, 53, 54, 55, 56, 57, 58, 59, 61, 62, 63, 64, 65, 66, 67, 68, 69, 71, 72, 73, 74, 75, 76, 77, 78, 79, 81, 82, 83, 84, 85, 86, 88, 89, 91, 98, 125, 130] do not have 500 required trades.

,series_threshold,start_date,end_date,n_trades,n_markets,contract_volume,avg_taker_trade_size,median_taker_trade_size,trades_per_market,total_taker_pnl,taker_pct_net_ret,taker_pct_winning,taker_win_avg_pct_ret,taker_loss_avg_pct_ret,total_maker_pnl,maker_pct_net_ret,maker_pct_winning,maker_win_avg_pct_ret,maker_loss_avg_pct_ret,maker_fee_pct_of_edge
6,50,2025-10-06 22:42:19.436342+00:00,2026-02-09 03:24:44.593522+00:00,26373,505,3924963.0,76.823251,13.020,52.223762,-375477.04,-18.065034,41.917871,73.287706,-100.0,309856.45,16.204953,58.082129,115.630392,-100.0,4.088019
5,40,2025-10-06 22:18:26.107057+00:00,2026-02-09 03:24:19.959858+00:00,23468,576,3330398.0,71.609236,11.815,40.743056,-174334.34,-10.108727,41.618374,94.625402,-100.0,119158.83,7.174002,58.381626,120.645003,-100.0,8.527527
7,60,2025-10-06 22:36:15.766195+00:00,2026-02-09 03:25:19.255181+00:00,23332,444,3298601.0,72.587522,13.000,52.549550,-177407.18,-10.192979,48.782788,83.851659,-100.0,118725.98,7.343278,51.217212,123.210890,-100.0,9.046715
8,70,2025-10-06 22:24:19.244556+00:00,2026-02-09 03:25:32.751520+00:00,19282,343,2289553.0,60.600052,10.260,56.215743,-130378.30,-10.847337,49.719946,84.007956,-100.0,88491.66,7.834578,50.280054,120.052749,-100.0,8.705658
4,30,2025-10-06 22:33:44.289461+00:00,2026-02-09 03:25:36.022952+00:00,24529,549,3096247.0,63.512546,9.620,44.679417,-90415.32,-5.656213,46.915895,102.045888,-100.0,39553.24,2.554136,53.084105,110.102894,-100.0,20.583366
0,1,2025-11-16 05:49:33.102518+00:00,2025-12-23 04:16:21.793101+00:00,958,24,78349.0,38.355418,9.360,39.916667,-10207.93,-26.909052,34.446764,97.644890,-100.0,8716.02,20.798989,65.553236,105.296220,-100.0,3.343384
2,17,2025-11-15 06:20:03.774430+00:00,2025-12-29 04:35:47.299279+00:00,1132,11,106966.0,50.902005,11.595,102.909091,13323.36,22.443259,66.961131,75.367767,-100.0,-15506.98,-31.147908,33.038869,185.082783,-100.0,-2.920635
13,120,2025-10-26 02:07:17.310778+00:00,2026-01-05 04:27:06.142083+00:00,512,11,77781.0,47.753613,9.640,46.545455,19719.72,78.183733,60.546875,136.429937,-100.0,-20687.42,-38.648989,39.453125,45.940610,-100.0,-0.952901
1,10,2025-10-07 01:00:54.509583+00:00,2026-02-09 03:24:36.589218+00:00,17723,368,2271646.0,68.516545,9.310,48.160326,-11026.09,-0.888159,52.513683,85.482308,-100.0,-22963.98,-2.157900,47.486317,123.501562,-100.0,-42.553285
12,110,2025-10-12 16:34:48.360043+00:00,2026-02-09 03:24:53.081510+00:00,2646,46,356502.0,59.044546,12.400,57.521739,24962.94,15.532325,47.127740,128.845160,-100.0,-30578.49,-15.182852,52.872260,116.981182,-100.0,-3.842004
3,20,2025-10-06 22:46:11.813489+00:00,2026-02-09 03:25:10.354693+00:00,33164,483,3319427.0,48.474472,9.350,68.662526,-16628.19,-1.008216,47.988783,85.713614,-100.0,-35578.29,-2.065665,52.011217,99.491531,-100.0,-42.124532
9,80,2025-10-06 22:30:36.900242+00:00,2026-02-09 03:20:56.413019+00:00,13862,288,2050553.0,72.284092,13.830,48.131944,33732.66,3.273073,47.215409,95.213296,-100.0,-69554.88,-6.588109,52.784591,102.735377,-100.0,-11.560981
10,90,2025-10-06 22:42:38.691402+00:00,2026-02-09 03:24:27.986666+00:00,7744,192,1256935.0,74.687102,14.040,40.333333,55903.67,9.373734,48.308368,114.013678,-100.0,-78445.68,-11.483934,51.691632,93.999067,-100.0,-6.132338
11,100,2025-10-06 22:29:22.715507+00:00,2026-02-09 03:24:49.406808+00:00,6326,113,945912.0,63.725621,14.040,55.982301,81784.45,19.655729,50.158078,133.275730,-100.0,-98004.25,-17.947943,49.841922,78.678398,-100.0,-3.444696

In [62]:
# Comparison Analysis
# Note, hover over bars for t-test

graph_comparison_by_threshold(
    df            = rushing_yards_df,
    graph_title   = "Rushing Yard",
    n_req_trades  = 500,
    n_req_markets = 10,
    ci            = 0.95,
)

In [63]:
# Regression Analysis: Maker PnL
# Note, hover for regression details

valid_series_thresholds = set({30, 40, 50, 60, 70})     # Series thresholds chosen where maker PnL statistics are favorable
valid_rushing_yards_df = rushing_yards_df[rushing_yards_df['series_threshold'].isin(valid_series_thresholds)].copy()

graph_regression_by_threshold(
    df          = valid_rushing_yards_df,
    side        = 'maker',
    graph_title = 'Rushing Yards',
)

In [64]:
# Regression Analysis: Taker PnL
# Note, hover for regression details

graph_regression_by_threshold(
    df          = valid_rushing_yards_df,
    side        = 'taker',
    graph_title = 'Rushing Yards',
)

### Analysis - **Receiving Yards** in a NFL Game

In [65]:
# Market Analysis

market_analytics_df = market_analysis(
    df                = receiving_yards_df,
    n_req_trades      = 500,   
    series_thresholds = True
)

market_analytics_df.sort_values(by = ['total_maker_pnl', 'maker_pct_net_ret', 'n_markets'], ascending = False)

Invalid Series Threshold: [5, 6, 7, 8, 9, 11, 12, 13, 14, 16, 18, 19, 21, 22, 23, 24, 25, 26, 27, 28, 29, 31, 32, 33, 34, 35, 36, 37, 38, 39, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51, 52, 53, 54, 55, 56, 57, 58, 59, 61, 62, 63, 64, 65, 66, 67, 68, 69, 71, 72, 73, 74, 75, 76, 77, 78, 79, 81, 83, 85, 86, 87, 88, 89, 91, 92, 93, 95, 97, 98, 106, 125, 130] do not have 500 required trades.

,series_threshold,start_date,end_date,n_trades,n_markets,contract_volume,avg_taker_trade_size,median_taker_trade_size,trades_per_market,total_taker_pnl,taker_pct_net_ret,taker_pct_winning,taker_win_avg_pct_ret,taker_loss_avg_pct_ret,total_maker_pnl,maker_pct_net_ret,maker_pct_winning,maker_win_avg_pct_ret,maker_loss_avg_pct_ret,maker_fee_pct_of_edge
5,40,2025-10-06 22:13:15.599604+00:00,2026-02-09 03:25:29.011357+00:00,32827,1397,4493082.0,61.465718,12.88,23.498210,-318033.70,-15.304027,42.072075,97.608942,-100.0,242444.50,9.734512,57.927925,107.266937,-100.0,5.906921
7,60,2025-10-06 22:23:14.058057+00:00,2026-02-09 03:25:26.072785+00:00,17296,804,2517843.0,67.482357,14.26,21.512438,-188111.86,-15.636807,40.980574,103.219671,-100.0,143254.20,10.535769,59.019426,96.760679,-100.0,5.927015
6,50,2025-10-06 22:32:24.920180+00:00,2026-02-09 03:25:07.456588+00:00,24833,1031,3293845.0,60.131995,14.06,24.086324,-160689.82,-10.443587,43.273064,98.409253,-100.0,103859.05,5.731641,56.726936,106.877289,-100.0,9.925157
9,80,2025-10-06 22:44:12.464699+00:00,2026-02-09 02:57:18.458324+00:00,8696,338,1026921.0,55.666036,13.20,25.727811,-84891.12,-17.009517,42.640294,82.275017,-100.0,66096.60,12.091533,57.359706,109.584879,-100.0,5.417996
8,70,2025-10-06 22:30:18.587370+00:00,2026-02-09 03:19:28.109656+00:00,9546,523,1256446.0,60.147510,14.08,18.252390,-67264.72,-11.357819,42.384245,99.401252,-100.0,44647.32,6.500484,57.615755,98.551174,-100.0,9.253654
10,90,2025-10-12 02:49:43.846891+00:00,2026-02-09 03:16:57.184331+00:00,8396,179,854874.0,49.695844,9.69,46.905028,-40383.10,-9.388622,38.434969,89.602761,-100.0,24249.52,5.500261,61.565031,111.589680,-100.0,11.824769
11,100,2025-10-11 19:30:30.623063+00:00,2026-02-09 03:14:32.237700+00:00,5169,96,578666.0,53.384144,12.48,53.843750,-34832.82,-12.232308,38.305281,96.669474,-100.0,23789.55,7.801171,61.694719,91.415244,-100.0,8.552097
0,10,2025-10-06 23:15:16.765083+00:00,2026-02-09 03:25:28.313872+00:00,16443,900,2445979.0,84.072356,10.00,18.270000,-62343.98,-4.408284,58.152405,58.003547,-100.0,22471.60,2.097003,41.847595,160.154611,-100.0,26.321343
12,110,2025-10-11 19:15:40.101172+00:00,2026-02-09 03:14:18.898131+00:00,1857,47,228967.0,54.059747,9.50,39.510638,-26118.63,-25.149705,37.695207,97.166906,-100.0,21781.89,16.826345,62.304793,73.060415,-100.0,3.853727
13,120,2025-11-03 01:17:11.523732+00:00,2026-02-09 02:21:34.543811+00:00,1607,26,175191.0,48.676409,9.50,61.807692,-20677.30,-25.621699,33.789670,94.677308,-100.0,17571.61,18.004734,66.210330,71.126269,-100.0,3.442028
2,17,2025-11-13 05:04:28.275897+00:00,2025-12-28 21:05:22.595544+00:00,568,30,65442.0,63.096197,12.56,18.933333,-10245.97,-27.860502,49.823944,82.902027,-100.0,9072.09,30.402538,50.176056,207.419974,-100.0,2.541188
4,30,2025-10-06 22:13:28.029309+00:00,2026-02-09 03:25:21.049334+00:00,34471,1394,4366884.0,60.643573,11.20,24.728121,-70453.60,-3.279215,48.722114,92.363124,-100.0,-2236.71,-0.097627,51.277886,112.470623,-100.0,118.026281
1,15,2025-11-14 00:02:00.918537+00:00,2025-12-28 23:53:44.081833+00:00,671,37,63993.0,49.557168,10.60,18.135135,8373.94,24.513115,61.251863,85.063934,-100.0,-9511.78,-30.713102,38.748137,143.891126,-100.0,-2.473998
3,20,2025-10-06 22:14:50.501341+00:00,2026-02-09 03:25:26.143456+00:00,36422,1256,4367921.0,58.355869,9.49,28.998408,245351.95,11.228393,55.908517,96.609530,-100.0,-320074.59,-14.178021,44.091483,106.619983,-100.0,-4.937648

In [66]:
# Comparison Analysis
# Note, hover over bars for t-test

graph_comparison_by_threshold(
    df            = receiving_yards_df,
    graph_title   = "Receiving Yard",
    n_req_trades  = 500,
    n_req_markets = 10,
    ci            = 0.95,
)

In [67]:
# Regression Analysis: Maker PnL
# Note, hover for regression details

valid_series_thresholds = set({40, 50, 60, 70, 80})     # Series thresholds chosen where maker PnL statistics are favorable
valid_receiving_yards_df = receiving_yards_df[receiving_yards_df['series_threshold'].isin(valid_series_thresholds)].copy()

graph_regression_by_threshold(
    df          = valid_receiving_yards_df,
    side        = 'maker',
    graph_title = 'Receiving Yards',
)

In [68]:
# Regression Analysis: Taker PnL
# Note, hover for regression details

graph_regression_by_threshold(
    df          = valid_receiving_yards_df,
    side        = 'taker',
    graph_title = 'Receiving Yards',
)

### Analysis - **Passing Yards** in a NFL Game

In [69]:
# Market Analysis

market_analytics_df = market_analysis(
    df                = passing_yards_df,
    n_req_trades      = 500, 
    series_thresholds = True
)

market_analytics_df.sort_values(by = ['total_maker_pnl', 'maker_pct_net_ret', 'n_markets'], ascending = False)

Invalid Series Threshold: [134, 139, 153, 156, 159, 163, 164, 170, 171, 173, 176, 178, 180, 181, 184, 185, 186, 187, 188, 190, 191, 192, 193, 194, 195, 196, 197, 198, 201, 202, 203, 204, 205, 206, 207, 208, 210, 211, 212, 213, 214, 215, 216, 217, 219, 220, 221, 222, 224, 227, 228, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 263, 264, 265, 266, 267, 268, 270, 271, 272, 283] do not have 500 required trades.

,series_threshold,start_date,end_date,n_trades,n_markets,contract_volume,avg_taker_trade_size,median_taker_trade_size,trades_per_market,total_taker_pnl,taker_pct_net_ret,taker_pct_winning,taker_win_avg_pct_ret,taker_loss_avg_pct_ret,total_maker_pnl,maker_pct_net_ret,maker_pct_winning,maker_win_avg_pct_ret,maker_loss_avg_pct_ret,maker_fee_pct_of_edge
1,175,2025-10-06 23:10:03.421116+00:00,2026-02-09 03:24:56.000303+00:00,21661,391,3065535.0,77.156963,10.000,55.398977,-92660.00,-5.432648,57.435021,57.925935,-100.0,49676.28,3.540959,42.564979,166.818554,-100.0,14.856101
2,199,2025-12-07 09:57:25.727075+00:00,2026-01-13 04:15:21.168404+00:00,916,3,80006.0,49.516594,10.440,305.333333,-36563.18,-78.330346,20.414847,76.042428,-100.0,34908.30,99.787323,79.585153,133.552042,-100.0,0.947444
9,229,2025-11-26 08:14:34.075280+00:00,2026-02-09 03:17:28.368213+00:00,1419,9,120062.0,44.743460,9.180,157.666667,-32300.95,-49.370997,20.789288,74.010167,-100.0,29877.62,52.361411,79.210712,113.399893,-100.0,1.610224
7,225,2025-10-06 23:12:46.797345+00:00,2026-02-09 03:25:03.786314+00:00,23311,386,3364105.0,72.058831,14.210,60.391192,-88689.28,-5.131919,51.529321,80.008183,-100.0,28066.08,1.654314,48.470679,113.291838,-100.0,30.293504
14,350,2025-10-06 23:04:32.840031+00:00,2026-02-09 02:48:25.762071+00:00,4695,345,590915.0,36.012332,4.800,13.608696,-26696.97,-15.435346,36.528222,132.876108,-100.0,21823.39,5.161285,63.471778,239.725123,-100.0,4.346643
8,226,2025-11-16 18:21:32.526465+00:00,2026-02-09 03:23:57.381236+00:00,797,7,132367.0,81.793902,11.500,113.857143,-24189.58,-35.959701,58.343789,113.786610,-100.0,21588.04,31.887818,41.656211,186.863942,-100.0,2.364010
11,275,2025-10-06 23:06:02.542735+00:00,2026-02-09 03:25:16.441540+00:00,10451,374,1490533.0,59.196970,12.610,27.943850,-39549.79,-6.200205,41.795044,137.176470,-100.0,15495.29,1.767439,58.204956,97.359851,-100.0,23.813352
3,200,2025-10-06 23:03:00.546020+00:00,2026-02-09 03:25:33.612056+00:00,35833,391,4421073.0,65.893430,11.050,91.644501,-82622.01,-3.413357,55.892613,65.130797,-100.0,8243.81,0.397311,44.107387,138.830908,-100.0,64.514334
13,325,2025-11-13 18:42:31.354507+00:00,2026-02-09 03:21:29.803404+00:00,2735,243,379185.0,50.902808,9.280,11.255144,-11557.79,-8.110799,39.597806,128.467031,-100.0,7446.33,3.092360,60.402194,72.365610,-100.0,10.048706
6,223,2025-11-16 14:09:40.337147+00:00,2026-01-11 21:10:20.772785+00:00,562,5,88479.0,83.472829,14.255,112.400000,7532.55,15.604565,61.032028,60.863164,-100.0,-9234.49,-22.034365,38.967972,100.539497,-100.0,-3.848511
0,158,2025-12-21 20:09:36.798636+00:00,2025-12-23 04:23:20.248405+00:00,520,1,81504.0,81.945635,14.250,520.000000,16697.40,38.195518,71.730769,60.551739,-100.0,-18079.28,-46.155606,28.269231,38.999547,-100.0,-1.561743
12,300,2025-10-06 23:02:44.878263+00:00,2026-02-09 03:24:06.026289+00:00,10938,375,1756945.0,54.933094,10.220,29.168000,-3688.46,-0.594418,35.856647,150.090081,-100.0,-20927.77,-1.802495,64.143353,66.449400,-100.0,-31.047389
5,218,2025-11-30 16:25:54.295971+00:00,2026-01-18 01:08:26.008761+00:00,601,4,93119.0,71.249135,19.040,150.250000,24853.45,56.162752,73.544093,104.646796,-100.0,-26645.37,-52.598159,26.455907,95.145059,-100.0,-1.369969
4,209,2025-12-10 15:28:38.261224+00:00,2026-01-18 23:20:17.617830+00:00,667,3,127796.0,94.579640,14.440,222.333333,34771.42,53.374130,73.163418,79.874790,-100.0,-37351.39,-57.261596,26.836582,108.124769,-100.0,-1.406360
10,250,2025-10-06 23:11:55.959251+00:00,2026-02-09 03:25:26.583681+00:00,19898,388,2924507.0,65.881730,14.040,51.283505,138757.11,10.265857,52.864610,114.975824,-100.0,-189736.82,-11.684382,47.135390,101.904905,-100.0,-5.714784

In [70]:
# Comparison Analysis
# Note, hover over bars for t-test

graph_comparison_by_threshold(
    df            = passing_yards_df,
    graph_title   = "Passing Yards",
    n_req_trades  = 500,
    n_req_markets = 10,
    ci            = 0.95,
)

In [71]:
# Regression Analysis: Maker PnL
# Note, hover for regression details

valid_series_thresholds = set({175, 225, 350})     # Series thresholds chosen where maker PnL statistics are favorable
valid_passing_yards_df = passing_yards_df[passing_yards_df['series_threshold'].isin(valid_series_thresholds)].copy()

graph_regression_by_threshold(
    df          = valid_passing_yards_df,
    side        = 'maker',
    graph_title = 'Passing Yards',
)

In [72]:
# Regression Analysis: Taker PnL
# Note, hover for regression details

valid_series_thresholds = set({175, 225, 350})     # Series thresholds chosen where maker PnL statistics are favorable
valid_passing_yards_df = passing_yards_df[passing_yards_df['series_threshold'].isin(valid_series_thresholds)].copy()

graph_regression_by_threshold(
    df          = valid_passing_yards_df,
    side        = 'taker',
    graph_title = 'Passing Yards',
)

### Analysis - **Passing Touchdowns** in a NFL Game

In [73]:
# Market Analysis

market_analytics_df = market_analysis(
    df                = passing_tds_df,
    n_req_trades      = 500,
    series_thresholds = True
)

market_analytics_df.sort_values(by = ['total_maker_pnl', 'maker_pct_net_ret', 'n_markets'], ascending = False)

,series_threshold,start_date,end_date,n_trades,n_markets,contract_volume,avg_taker_trade_size,median_taker_trade_size,trades_per_market,total_taker_pnl,taker_pct_net_ret,taker_pct_winning,taker_win_avg_pct_ret,taker_loss_avg_pct_ret,total_maker_pnl,maker_pct_net_ret,maker_pct_winning,maker_win_avg_pct_ret,maker_loss_avg_pct_ret,maker_fee_pct_of_edge
3,4,2025-11-21 03:25:29.254042+00:00,2026-02-09 03:23:18.388336+00:00,4608,170,910121.0,39.858075,5.685,27.105882,-62300.32,-32.959937,20.659722,99.234744,-100.0,55591.85,7.638225,79.340278,35.422006,-100.0,2.382634
1,2,2025-11-21 00:29:13.721015+00:00,2026-02-09 03:22:44.074553+00:00,33240,202,2933230.0,41.518761,9.400,164.554455,-58972.65,-4.138392,43.880866,104.262152,-100.0,2684.40,0.171581,56.119134,119.245649,-100.0,80.883133
0,1,2025-11-21 01:15:11.039699+00:00,2026-02-09 02:41:12.490533+00:00,6901,180,777158.0,69.321648,9.180,38.338889,25427.39,5.215398,71.134618,47.568907,-100.0,-36900.23,-12.255702,28.865382,197.259604,-100.0,-6.699532
2,3,2025-11-21 01:44:36.573035+00:00,2026-02-09 03:24:41.020112+00:00,12648,186,1611071.0,38.506093,9.280,68.000000,52284.58,10.344176,32.779886,223.637953,-100.0,-75364.02,-6.677058,67.220114,55.957125,-100.0,-6.583801

In [74]:
# Comparison Analysis
# Note, hover over bars for t-test

graph_comparison_by_threshold(
    df            = passing_tds_df,
    graph_title   = "Passing Touchdowns",
    n_req_trades  = 500,
    n_req_markets = 10,
    ci            = 0.95
)

In [75]:
# Regression Analysis: Maker PnL
# Note, hover for regression details

graph_regression_by_threshold(
    df          = passing_tds_df,   # All series thresholds are considered
    side        = 'maker',
    graph_title = 'Passing Touchdowns',
)

In [76]:
# Regression Analysis: Taker PnL
# Note, hover for regression details

graph_regression_by_threshold(
    df          = passing_tds_df,   # All series thresholds are considered
    side        = 'taker',
    graph_title = 'Passing Touchdowns',
)

### Analysis - **Receptions** in a NFL Game

In [77]:
# Market Analysis

market_analytics_df = market_analysis(
    df                = receptions_df,
    n_req_trades      = 500,
    series_thresholds = True
)

market_analytics_df.sort_values(by = ['total_maker_pnl', 'maker_pct_net_ret', 'n_markets'], ascending = False)

Invalid Series Threshold: [10, 11] do not have 500 required trades.

,series_threshold,start_date,end_date,n_trades,n_markets,contract_volume,avg_taker_trade_size,median_taker_trade_size,trades_per_market,total_taker_pnl,taker_pct_net_ret,taker_pct_winning,taker_win_avg_pct_ret,taker_loss_avg_pct_ret,total_maker_pnl,maker_pct_net_ret,maker_pct_winning,maker_win_avg_pct_ret,maker_loss_avg_pct_ret,maker_fee_pct_of_edge
6,7,2025-10-27 19:14:57.701607+00:00,2026-02-09 02:42:30.012577+00:00,3027,265,403364.0,65.671044,9.57,11.422642,-57903.53,-28.347186,34.819954,86.582210,-100.0,51042.38,24.782712,65.180046,115.543902,-100.0,2.635751
5,6,2025-10-27 20:47:59.611253+00:00,2026-02-09 02:42:35.843433+00:00,4497,477,506251.0,52.258317,9.44,9.427673,-45653.26,-18.909659,36.980209,96.420925,-100.0,37607.09,13.782109,63.019791,137.200250,-100.0,4.138548
3,4,2025-10-27 20:43:13.500948+00:00,2026-02-09 03:24:34.275686+00:00,9675,955,1142092.0,54.708700,9.36,10.130890,-43900.98,-8.057074,43.545220,105.502085,-100.0,24401.42,3.956667,56.454780,110.425493,-100.0,13.874231
4,5,2025-10-27 20:13:20.624829+00:00,2026-02-09 03:25:09.729964+00:00,8599,856,1045385.0,52.723300,9.35,10.045561,-32369.03,-6.936215,39.341784,112.598004,-100.0,15714.42,2.639426,60.658216,117.645733,-100.0,17.614437
2,3,2025-10-27 19:42:25.125953+00:00,2026-02-09 03:25:02.032062+00:00,11396,977,1281709.0,55.637272,9.36,11.664278,-35303.53,-5.417198,43.743419,90.080941,-100.0,13196.24,2.023582,56.256581,114.670971,-100.0,25.250835
0,1,2025-10-27 20:07:17.873576+00:00,2026-02-09 03:03:37.138876+00:00,2883,412,257656.0,53.199830,4.55,6.997573,-1710.90,-1.102953,75.858481,52.430606,-100.0,-482.72,-0.460920,24.141519,152.274078,-100.0,-1324.372971
8,9,2025-11-02 13:34:59.064912+00:00,2026-02-09 02:09:39.811342+00:00,554,51,70429.0,59.918899,9.45,10.862745,-186.02,-0.544475,36.101083,108.892132,-100.0,-1028.51,-2.744266,63.898917,268.757970,-100.0,-31.199214
7,8,2025-10-27 22:15:44.555103+00:00,2026-02-09 02:15:39.693293+00:00,1275,118,138335.0,52.570243,9.60,10.805085,2378.27,3.439902,39.450980,85.863722,-100.0,-5021.52,-6.989816,60.549020,96.504437,-100.0,-11.864271
1,2,2025-10-27 20:22:31.136549+00:00,2026-02-09 03:25:24.053868+00:00,10727,842,1082975.0,51.137489,9.25,12.739905,41934.17,7.451959,56.642118,83.833645,-100.0,-59696.51,-11.095789,43.357882,161.194784,-100.0,-6.392306

In [78]:
# Comparison Analysis
# Note, hover over bars for t-test

graph_comparison_by_threshold(
    df            = receptions_df,
    graph_title   = "Receptions",
    n_req_trades  = 500,
    n_req_markets = 10,
    ci            = 0.95,
)

In [79]:
# Regression Analysis: Maker PnL
# Note, hover for regression details

valid_series_thresholds = set({4, 5, 6, 7})     # Series thresholds chosen where maker PnL statistics are favorable
valid_receptions_df = receptions_df[receptions_df['series_threshold'].isin(valid_series_thresholds)].copy()

graph_regression_by_threshold(
    df          = valid_receptions_df,
    side        = 'maker',
    graph_title = 'Receptions',
)

In [80]:
# Regression Analysis: Taker PnL
# Note, hover for regression details

graph_regression_by_threshold(
    df          = valid_receptions_df,
    side        = 'taker',
    graph_title = 'Receptions',
)