# **Kalshi NFL Player Prop Market Analysis**

In [1]:
import numpy as np
from utils import *
import pandas as pd

# Preprocessing

In [2]:
SERIES_TICKERS = {
    "anytime_td"      : "KXNFLANYTD",     # NFL: 'CMC scores at least one touchdown in a game'
    "two_plus_tds"    : "KXNFL2TD",       # NFL: 'CMC scores at least two touchdowns in a game'
    "first_td"        : "KXNFLFIRSTTD",   # NFL: 'CMC scores the first touchdown in a game'
    "rushing_yards"   : "KXNFLRSHYDS",    # NFL: 'Brock Purdy records 40+ rushing yards in a game'
    "receiving_yards" : "KXNFLRECYDS",    # NFL: 'CMC records 20+ receiving yards in a game'
    "passing_yards"   : "KXNFLPASSYDS",   # NFL: 'Brock Purdy records 200+ passing yards in a game'
    "passing_tds"     : "KXNFLPASSTDS",   # NFL: 'Brock Purdy throws 2+ touchdowns in a game'
    "receptions"      : "KXNFLREC",       # NFL: 'CMC records 4+ receptions in a game'
}
KALSHI_MAKER_FEE: float = 0.0175          # Kalshi maker fee for June 2026
KALSHI_TAKER_FEE: float = 0.07            # Kalshi taker fee for June 2026

### Preprocessing - Market Data

In [3]:
# Load in data

markets_df = pd.read_parquet('data/raw/historical_markets.parquet')

In [4]:
markets_df.head(2)

,can_close_early,close_time,created_time,custom_strike,early_close_condition,event_ticker,expected_expiration_time,expiration_time,expiration_value,last_price_dollars,...,updated_time,volume_24h_fp,volume_fp,yes_ask_dollars,yes_ask_size_fp,yes_bid_dollars,yes_bid_size_fp,yes_sub_title,floor_strike,subtitle
0,True,2026-02-09T03:47:16Z,2026-02-05T18:12:48.735839Z,{'football_player': 'f710b516-32b8-4cc7-ae91-8...,This market will close and expire early if the...,KXNFLANYTD-26FEB08SEANE,2026-02-09T02:30:00Z,2026-02-22T23:30:00Z,No,0.0100,...,2026-02-19T08:48:16.628714Z,0.00,107875.00,1.0000,0.00,0.0000,0.00,George Holani,NaN,None
1,True,2026-02-09T02:37:51Z,2026-02-05T18:12:48.432779Z,{'football_player': '42a1f21f-07d2-41e4-b204-c...,This market will close and expire early if the...,KXNFLANYTD-26FEB08SEANE,2026-02-09T02:30:00Z,2026-02-22T23:30:00Z,Yes,0.9900,...,2026-02-19T08:48:16.628714Z,0.00,182540.00,1.0000,0.00,0.0000,0.00,Mack Hollins,NaN,None

In [5]:
print(f"Date of First Trade: {markets_df['created_time'].min()} \nDate of Last Trade: {markets_df['created_time'].max()}")

Date of First Trade: 2025-09-04T05:25:32.240887Z
Date of Last Trade: 2026-02-08T21:56:53.118992Z

In [6]:
# Drop duplicate tickers

markets_df = markets_df.drop_duplicates(['ticker'])

In [7]:
# Filter for liquid markets

markets_df = markets_df[markets_df['volume_fp'].astype(float) > 0]

In [8]:
# Market is finalized

markets_df = markets_df[markets_df['status'] == 'finalized']

In [9]:
# Remove 'scalar' (ie the game was cancelled)

markets_df = markets_df[markets_df['result'] != 'scalar']

In [10]:
# Create series column

markets_df['series'] = markets_df['ticker'].apply(lambda x: x.split('-')[0])

markets_df['series'].value_counts()

series
KXNFLRECYDS      8875
KXNFLANYTD       5230
KXNFLREC         4978
KXNFLFIRSTTD     4736
KXNFLRSHYDS      4374
KXNFLPASSYDS     3135
KXNFL2TD         1953
KXNFLPASSTDS      738
KXNFLGAMESACK      14
Name: count, dtype: int64

In [11]:
# Drop 'sacks' and 'No Touchdown' markets

markets_df = markets_df.loc[(markets_df['series'] != "KXNFLGAMESACK") & (markets_df['yes_sub_title'] != "No Touchdown"), :]

In [12]:
# Clean up index

markets_df = markets_df.reset_index(drop=True)

In [13]:
# Create series threshold column

markets_df['series_threshold'] = np.where(
    markets_df['floor_strike'].notna(),
    np.ceil(markets_df['floor_strike']),
    np.nan
)
markets_df['series_threshold'] = markets_df['series_threshold'].astype('Int64')

In [14]:
# Clean dates

markets_df['close_time'] = pd.to_datetime(markets_df['close_time'], format='ISO8601', utc=True)

### Preprocessing - Trade Data

In [15]:
# Load in data

trades_df = pd.read_parquet('data/raw/historical_trades.parquet')

In [16]:
trades_df.head(2)

,count_fp,created_time,is_block_trade,no_price_dollars,taker_book_side,taker_outcome_side,taker_side,ticker,trade_id,yes_price_dollars
0,80.00,2026-02-09T03:08:50.42768Z,False,0.9900,bid,yes,yes,KXNFLANYTD-26FEB08SEANE-SEAESAUBERT81,8e43a171-1168-7940-7792-c01925e63cd3,0.0100
1,467.00,2026-02-09T02:57:25.323792Z,False,0.9900,bid,yes,yes,KXNFLANYTD-26FEB08SEANE-SEAESAUBERT81,073a6a01-9432-4957-b99e-bc62cc79ce28,0.0100

In [17]:
trades_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2276812 entries, 0 to 2276811
Data columns (total 10 columns):
 #   Column              Dtype
---  ------              -----
 0   count_fp            object
 1   created_time        object
 2   is_block_trade      bool
 3   no_price_dollars    object
 4   taker_book_side     object
 5   taker_outcome_side  object
 6   taker_side          object
 7   ticker              object
 8   trade_id            object
 9   yes_price_dollars   object
dtypes: bool(1), object(9)
memory usage: 158.5+ MB

In [18]:
# Convert data

numeric_cols = ['count_fp', 'yes_price_dollars', 'no_price_dollars']

trades_df[numeric_cols] = trades_df[numeric_cols].apply(pd.to_numeric)

trades_df['created_time'] = pd.to_datetime(trades_df['created_time'], format='ISO8601', utc=True)

In [19]:
# Drop duplicate trades

trades_df = trades_df.drop_duplicates(['trade_id']).reset_index(drop=True)

In [20]:
# Resample trades that happened at the same time 
#   - This occurrs when a larger order gets filled at different price levels
#   - Resample by weighting price by dollar volume

trades_df['yes_dollar_vol'] = trades_df['count_fp'] * trades_df['yes_price_dollars']
trades_df['no_dollar_vol']  = trades_df['count_fp'] * trades_df['no_price_dollars']

trades_df = trades_df.groupby(['ticker', 'created_time'], as_index=False).agg(
    count_fp            = ('count_fp', 'sum'),
    yes_dollar_vol      = ('yes_dollar_vol', 'sum'),
    no_dollar_vol       = ('no_dollar_vol', 'sum'),
    taker_book_side     = ('taker_book_side', 'first'),
    taker_outcome_side  = ('taker_outcome_side', 'first'),
    taker_side          = ('taker_side', 'first'),
    trade_id            = ('trade_id', 'first'),
)

trades_df['yes_price_dollars'] = trades_df['yes_dollar_vol'] / trades_df['count_fp']
trades_df['no_price_dollars']  = trades_df['no_dollar_vol']  / trades_df['count_fp']

trades_df = trades_df.drop(columns=['yes_dollar_vol', 'no_dollar_vol'])

In [21]:
# Create game date, away team, and home team columns

date_teams = trades_df['ticker'].str.split('-').str[1]

year  = date_teams.str[0:2]      # "26"
month = date_teams.str[2:5]      # "JUN"
day   = date_teams.str[5:7]      # "13"

trades_df.loc[:, 'game_date'] = pd.to_datetime(
    year + month + day,
    format='%y%b%d'
)

teams_code = date_teams.str[7:]
trades_df[['away_team', 'home_team']] = pd.DataFrame(
    teams_code.apply(find_teams).tolist(),
    index=trades_df.index
)

trades_df.head(2)

,ticker,created_time,count_fp,taker_book_side,taker_outcome_side,taker_side,trade_id,yes_price_dollars,no_price_dollars,game_date,away_team,home_team
0,KXNFL2TD-25DEC01NYGNE-NEHHENRY85,2025-11-28 23:11:48.211379+00:00,3.0,bid,yes,yes,f6302110-aa18-462e-5d03-1e47d79b334a,0.060000,0.940000,2025-12-01,NYG,NE
1,KXNFL2TD-25DEC01NYGNE-NEHHENRY85,2025-12-01 12:48:44.199290+00:00,164.0,bid,yes,yes,8520efe0-697c-77e0-c5f5-42b5d202a02a,0.056951,0.943049,2025-12-01,NYG,NE

### Preprocessing - NFL Game Start Data

In [22]:
nfl_schedule_df = pd.read_parquet('data/raw/nfl_start_times.parquet')

In [23]:
# Create game start time column

nfl_schedule_df['game_start_time'] = (
    pd.to_datetime(
        nfl_schedule_df['gameday'].astype(str) + ' ' + nfl_schedule_df['gametime'].astype(str),
        format='%Y-%m-%d %H:%M'
    )
    .dt.tz_localize('America/New_York')
    .dt.tz_convert('UTC')
)

In [24]:
# Clean up data frame

nfl_schedule_df = (
    nfl_schedule_df[
        ['gameday', 'game_start_time', 'away_team', 'home_team']
    ]
    .astype({
        "gameday"   : "datetime64[ns, UTC]",
        "away_team" : "str",
        "home_team" : "str",
    })
    .rename(columns={
        "gameday"   : "game_date",
    })
)

nfl_schedule_df["game_date"] = nfl_schedule_df["game_date"].dt.tz_localize(None)

nfl_schedule_df['away_team'] = nfl_schedule_df['away_team'].replace('JAX', 'JAC')
nfl_schedule_df['home_team'] = nfl_schedule_df['home_team'].replace('JAX', 'JAC')

nfl_schedule_df

     game_date           game_start_time away_team home_team
0   2025-09-04 2025-09-05 00:20:00+00:00       DAL       PHI
1   2025-09-05 2025-09-06 00:00:00+00:00        KC       LAC
2   2025-09-07 2025-09-07 17:00:00+00:00        TB       ATL
3   2025-09-07 2025-09-07 17:00:00+00:00       CIN       CLE
4   2025-09-07 2025-09-07 17:00:00+00:00       MIA       IND
..         ...                       ...       ...       ...
280 2026-01-18 2026-01-18 23:30:00+00:00        LA       CHI
281 2026-01-18 2026-01-18 20:00:00+00:00       HOU        NE
282 2026-01-25 2026-01-25 20:00:00+00:00        NE       DEN
283 2026-01-25 2026-01-25 23:30:00+00:00        LA       SEA
284 2026-02-08 2026-02-08 23:30:00+00:00       SEA        NE

[285 rows x 4 columns]

In [25]:
# Add game start time column to trades data frame

trades_df = trades_df.merge(
    nfl_schedule_df,
    on=['game_date', 'away_team', 'home_team'],
    how='left'    
)

In [26]:
# Data validation

print(f"Missing game start time for {trades_df['game_start_time'].isna().sum():,} out of {len(trades_df['game_start_time']):,} trades.")

Missing game start time for 0 out of 2,034,973 trades.

In [27]:
# Merge data frames
merged = trades_df.merge(markets_df, on='ticker', how='left')

required_cols = [
    'ticker', 'created_time', 'count_fp', 'close_time', 'series',
    'game_start_time', 'result', 'yes_price_dollars', 'no_price_dollars',
    'taker_outcome_side', 
]

kalshi_df = merged[[
    'ticker', 'created_time_x', 'count_fp', 'close_time', 'series',
    'game_start_time', 'result', 'yes_price_dollars', 'no_price_dollars',
    'floor_strike', 'taker_outcome_side', 'series_threshold'
]].rename(columns={'created_time_x': 'created_time'}).dropna(subset=required_cols).sort_values(by=['created_time']).reset_index(drop=True).copy()

kalshi_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2007615 entries, 0 to 2007614
Data columns (total 12 columns):
 #   Column              Dtype
---  ------              -----
 0   ticker              object
 1   created_time        datetime64[ns, UTC]
 2   count_fp            float64
 3   close_time          datetime64[ns, UTC]
 4   series              object
 5   game_start_time     datetime64[ns, UTC]
 6   result              object
 7   yes_price_dollars   float64
 8   no_price_dollars    float64
 9   floor_strike        float64
 10  taker_outcome_side  object
 11  series_threshold    Int64
dtypes: Int64(1), datetime64[ns, UTC](3), float64(4), object(4)
memory usage: 185.7+ MB

# Dependent & Independent Variable Creation

In [28]:
# Independent: Number of trades per market (ticker)

kalshi_df['n_trades_in_market'] = kalshi_df.groupby('ticker')['ticker'].transform('count')

In [29]:
# Independent: Number of trades per market (ticker)
# Note, heavy tail

log_bins = np.logspace(
    np.log10(kalshi_df['n_trades_in_market'].min()), 
    np.log10(kalshi_df['n_trades_in_market'].max()), 
    num=21
)

log_bin_counts = (
    pd.cut(kalshi_df['n_trades_in_market'], bins=log_bins, include_lowest=True)
    .value_counts()
    .sort_index()
    .reset_index()
)
log_bin_counts.columns = ["log_bin", "log_count"]

linear_bin_counts = (
    pd.cut(kalshi_df['n_trades_in_market'], bins=20)
    .value_counts()
    .sort_index()
    .reset_index()
)
linear_bin_counts.columns = ["linear_bin", "linear_count"]

pd.concat([log_bin_counts, linear_bin_counts], axis=1)

                  log_bin  log_count           linear_bin  linear_count
0          (0.999, 1.653]       3980   (-22.131, 1157.55]       1438667
1          (1.653, 2.732]       5896    (1157.55, 2314.1]        242312
2          (2.732, 4.515]      14172    (2314.1, 3470.65]         92560
3          (4.515, 7.462]      23908    (3470.65, 4627.2]         66641
4         (7.462, 12.333]      38931    (4627.2, 5783.75]         42261
5        (12.333, 20.383]      55374    (5783.75, 6940.3]         18995
6        (20.383, 33.688]      73313    (6940.3, 8096.85]         15149
7        (33.688, 55.678]     105117    (8096.85, 9253.4]             0
8        (55.678, 92.023]     133412   (9253.4, 10409.95]         20067
9       (92.023, 152.092]     173500  (10409.95, 11566.5]         10769
10     (152.092, 251.372]     205236  (11566.5, 12723.05]             0
11     (251.372, 415.459]     207031  (12723.05, 13879.6]             0
12     (415.459, 686.655]     212605  (13879.6, 15036.15]             0
13    (686.655, 1134.878]     181597  (15036.15, 16192.7]         15144
14   (1134.878, 1875.685]     191304  (16192.7, 17349.25]             0
15   (1875.685, 3100.063]     125743  (17349.25, 18505.8]             0
16   (3100.063, 5123.671]     104153  (18505.8, 19662.35]             0
17   (5123.671, 8468.215]      61313  (19662.35, 20818.9]             0
18  (8468.215, 13995.955]      30836  (20818.9, 21975.45]         21918
19   (13995.955, 23132.0]      60194  (21975.45, 23132.0]         23132

In [30]:
# Independent: Number of trades per market (ticker)

kalshi_df['log_n_trades_in_market'] = np.log(kalshi_df['n_trades_in_market'])   # Apply a log transformation to reduce heavy tail

print(np.isinf(kalshi_df['log_n_trades_in_market']).sum(), 'infinite values')
print(kalshi_df['log_n_trades_in_market'].isna().sum(), 'NaN values')

0 infinite values
0 NaN values

In [31]:
# Independent: Market Completion Percentage

kalshi_df['n_cum_trades'] = kalshi_df.groupby('ticker').cumcount()  # Cumulative number of trades per market (ticker)

kalshi_df['market_completion_pct'] = kalshi_df['n_cum_trades'] / kalshi_df['n_trades_in_market']

kalshi_df[['ticker', 'market_completion_pct']].sample(n = 3)

                                           ticker  market_completion_pct
1516643  KXNFLANYTD-26JAN18LACHI-LAJWHITTINGTON88               0.256198
803287          KXNFLANYTD-25DEC28NYGLV-NYGJDART6               0.254642
1887776         KXNFLANYTD-26FEB08SEANE-NESDIGGS8               0.585631

In [32]:
# Independent: Post kickoff dummy

kalshi_df['is_post_kickoff_dummy'] = (kalshi_df['created_time'] > kalshi_df['game_start_time']).astype(int)

kalshi_df[['ticker', 'is_post_kickoff_dummy', 'created_time', 'game_start_time']].sample(n = 3)

,ticker,is_post_kickoff_dummy,created_time,game_start_time
875895,KXNFLRECYDS-25DEC29LAATL-ATLKPITTS8-50,0,2025-12-30 01:02:00.313304+00:00,2025-12-30 01:15:00+00:00
1634975,KXNFLANYTD-26JAN25LASEA-LABCORUM22,0,2026-01-25 23:08:40.676843+00:00,2026-01-25 23:30:00+00:00
469802,KXNFLANYTD-25DEC08PHILAC-PHIABROWN11,0,2025-12-08 14:42:04.903493+00:00,2025-12-09 01:15:00+00:00

In [33]:
# Independent: Taker outcome side dummy

kalshi_df['taker_outcome_side_dummy'] = (kalshi_df['taker_outcome_side'] == 'yes').astype(int)

kalshi_df[['ticker', 'taker_outcome_side', 'taker_outcome_side_dummy']].sample(n = 3)

,ticker,taker_outcome_side,taker_outcome_side_dummy
1958429,KXNFLFIRSTTD-26FEB08SEANE-NETHENDERSON32,no,0
1938577,KXNFLFIRSTTD-26FEB08SEANE-NEHHENRY85,yes,1
506038,KXNFLRSHYDS-25DEC14GBDEN-DENBNIX10-17,yes,1

In [34]:
# Independent: Maker outcome side dummy

kalshi_df['maker_outcome_side'] = np.where(kalshi_df['taker_outcome_side'] == 'yes', 'no', 'yes')

kalshi_df['maker_outcome_side_dummy'] = (kalshi_df['maker_outcome_side'] == 'yes').astype(int)

kalshi_df[['ticker', 'maker_outcome_side', 'maker_outcome_side_dummy']].sample(n = 3)

,ticker,maker_outcome_side,maker_outcome_side_dummy
1435524,KXNFLPASSTDS-26JAN17SFSEA-SEASDARNOLD14-2,no,0
596802,KXNFLANYTD-25DEC21LVHOU-HOUDSCHULTZ86,no,0
982238,KXNFLANYTD-26JAN04ARILA-ARITMCBRIDE85,no,0

In [35]:
# Independent: Trade Size (count)
# Note, heavy tail

log_bins = np.logspace(
    np.log10(kalshi_df['count_fp'].min()), 
    np.log10(kalshi_df['count_fp'].max()), 
    num=21
)

log_bin_counts = (
    pd.cut(kalshi_df['count_fp'], bins=log_bins, include_lowest=True)
    .value_counts()
    .sort_index()
    .reset_index()
)
log_bin_counts.columns = ["log_bin", "log_count"]

linear_bin_counts = (
    pd.cut(kalshi_df['count_fp'], bins=20)
    .value_counts()
    .sort_index()
    .reset_index()
)
linear_bin_counts.columns = ["linear_bin", "linear_count"]

pd.concat([log_bin_counts, linear_bin_counts], axis=1)

                     log_bin  log_count             linear_bin  linear_count
0             (0.999, 1.899]      77618   (-370.299, 18565.95]       2007232
1             (1.899, 3.606]      78853    (18565.95, 37130.9]           293
2             (3.606, 6.846]     117145    (37130.9, 55695.85]            69
3              (6.846, 13.0]     256828    (55695.85, 74260.8]            12
4             (13.0, 24.685]     279889    (74260.8, 92825.75]             4
5           (24.685, 46.872]     313087   (92825.75, 111390.7]             3
6           (46.872, 89.003]     291758  (111390.7, 129955.65]             0
7          (89.003, 169.001]     263348  (129955.65, 148520.6]             1
8         (169.001, 320.905]     160614  (148520.6, 167085.55]             0
9         (320.905, 609.344]      90226  (167085.55, 185650.5]             0
10       (609.344, 1157.041]      42670  (185650.5, 204215.45]             0
11      (1157.041, 2197.025]      21320  (204215.45, 222780.4]             0
12      (2197.025, 4171.778]       8686  (222780.4, 241345.35]             0
13      (4171.778, 7921.501]       3672  (241345.35, 259910.3]             0
14     (7921.501, 15041.589]       1369  (259910.3, 278475.25]             0
15    (15041.589, 28561.431]        372  (278475.25, 297040.2]             0
16    (28561.431, 54233.322]        138  (297040.2, 315605.15]             0
17   (54233.322, 102979.897]         20  (315605.15, 334170.1]             0
18  (102979.897, 195541.392]          1  (334170.1, 352735.05]             0
19    (195541.392, 371300.0]          1  (352735.05, 371300.0]             1

In [36]:
# Independent: Trade Size (count)

kalshi_df['log_count_fp'] = np.log(kalshi_df['count_fp'])   # Apply a log transformation to reduce heavy tail

print(np.isinf(kalshi_df['log_count_fp']).sum(), 'infinite values')
print(kalshi_df['log_count_fp'].isna().sum(), 'NaN values')

0 infinite values
0 NaN values

In [37]:
# Dependent: Maker PnL & Return

kalshi_df['maker_price'] = np.where(
    kalshi_df['maker_outcome_side'] == 'yes',
    kalshi_df['yes_price_dollars'],
    kalshi_df['no_price_dollars']
)

kalshi_df['maker_dollar_amt'] = kalshi_df['count_fp'] * np.where(
    kalshi_df['maker_outcome_side'] == 'yes', 
    kalshi_df['yes_price_dollars'],
    kalshi_df['no_price_dollars']
)

kalshi_df["maker_fee"] = np.ceil(KALSHI_MAKER_FEE * kalshi_df["count_fp"] * kalshi_df['maker_price'] * (1 - kalshi_df['maker_price']) * 100) / 100

kalshi_df["maker_revenue"] = kalshi_df["count_fp"] * np.where(
    ((kalshi_df['taker_outcome_side'] == "yes") & (kalshi_df["result"] == "no")) |
    ((kalshi_df['taker_outcome_side'] == "no") & (kalshi_df["result"] == "yes")),
    1,
    0
)

kalshi_df["maker_pnl"] = kalshi_df["maker_revenue"] - kalshi_df["maker_dollar_amt"] - kalshi_df["maker_fee"]

kalshi_df["maker_net_return"] = kalshi_df["maker_pnl"] / (kalshi_df["maker_dollar_amt"] + kalshi_df["maker_fee"])

kalshi_df['maker_pnl_per_contract'] = kalshi_df['maker_pnl'] / kalshi_df['count_fp']

kalshi_df[['ticker', 'maker_dollar_amt', 'maker_fee', 'maker_revenue', 'maker_pnl', 'maker_net_return', 'maker_pnl_per_contract']]

,ticker,maker_dollar_amt,maker_fee,maker_revenue,maker_pnl,maker_net_return,maker_pnl_per_contract
0,KXNFLFIRSTTD-25SEP04DALPHI-PHISBARKLEY26,47.52,0.24,66.0,18.24,0.381910,0.276364
1,KXNFLANYTD-25SEP04DALPHI-PHISBARKLEY26,7.54,0.10,0.0,-7.64,-1.000000,-0.263448
2,KXNFLANYTD-25SEP04DALPHI-DALJWILLIAMS33,1.22,0.01,0.0,-1.23,-1.000000,-0.615000
3,KXNFLFIRSTTD-25SEP04DALPHI-PHIDEF,177.65,0.16,187.0,9.19,0.051684,0.049144
4,KXNFLANYTD-25SEP04DALPHI-DALJWILLIAMS33,7.32,0.05,0.0,-7.37,-1.000000,-0.614167
...,...,...,...,...,...,...,...
2007610,KXNFLRSHYDS-26FEB08SEANE-SEAKWALKER9-70,25.74,0.01,26.0,0.25,0.009709,0.009615
2007611,KXNFLRSHYDS-26FEB08SEANE-NETHENDERSON32-30,1.97,0.04,0.0,-2.01,-1.000000,-0.010203
2007612,KXNFLRSHYDS-26FEB08SEANE-SEAKWALKER9-70,26.73,0.01,27.0,0.26,0.009723,0.009630
2007613,KXNFLPASSYDS-26FEB08SEANE-NEDMAYE10-200,11.88,0.01,12.0,0.11,0.009251,0.009167
2007614,KXNFLRSHYDS-26FEB08SEANE-NETHENDERSON32-30,0.63,0.02,0.0,-0.65,-1.000000,-0.010317

In [38]:
# Dependent: Taker PnL & Return

kalshi_df['taker_price'] = np.where(
    kalshi_df['taker_outcome_side'] == 'yes',
    kalshi_df['yes_price_dollars'],
    kalshi_df['no_price_dollars']
)

kalshi_df['taker_dollar_amt'] = kalshi_df['count_fp'] * np.where(
    kalshi_df['taker_outcome_side'] == 'yes',
    kalshi_df["yes_price_dollars"],
    kalshi_df["no_price_dollars"]
)

kalshi_df["taker_fee"] = np.ceil(KALSHI_TAKER_FEE * kalshi_df["count_fp"] * kalshi_df['taker_price'] * (1 - kalshi_df['taker_price']) * 100) / 100

kalshi_df["taker_revenue"] = kalshi_df["count_fp"] * np.where(
    ((kalshi_df['taker_outcome_side'] == 'yes') & (kalshi_df["result"] == "yes")) |
    ((kalshi_df['taker_outcome_side'] == 'no') & (kalshi_df["result"] == "no")),
    1,
    0
)

kalshi_df["taker_pnl"] = kalshi_df["taker_revenue"] - kalshi_df["taker_dollar_amt"] - kalshi_df["taker_fee"]

kalshi_df["taker_net_return"] = kalshi_df["taker_pnl"] / (kalshi_df["taker_dollar_amt"] + kalshi_df["taker_fee"])

kalshi_df['taker_pnl_per_contract'] = kalshi_df['taker_pnl'] / kalshi_df['count_fp']

kalshi_df[['ticker', 'taker_dollar_amt', 'taker_fee', 'taker_revenue', 'taker_pnl', 'taker_net_return', 'taker_pnl_per_contract']]

,ticker,taker_dollar_amt,taker_fee,taker_revenue,taker_pnl,taker_net_return,taker_pnl_per_contract
0,KXNFLFIRSTTD-25SEP04DALPHI-PHISBARKLEY26,18.48,0.94,0.0,-19.42,-1.000000,-0.294242
1,KXNFLANYTD-25SEP04DALPHI-PHISBARKLEY26,21.46,0.40,29.0,7.14,0.326624,0.246207
2,KXNFLANYTD-25SEP04DALPHI-DALJWILLIAMS33,0.78,0.04,2.0,1.18,1.439024,0.590000
3,KXNFLFIRSTTD-25SEP04DALPHI-PHIDEF,9.35,0.63,0.0,-9.98,-1.000000,-0.053369
4,KXNFLANYTD-25SEP04DALPHI-DALJWILLIAMS33,4.68,0.20,12.0,7.12,1.459016,0.593333
...,...,...,...,...,...,...,...
2007610,KXNFLRSHYDS-26FEB08SEANE-SEAKWALKER9-70,0.26,0.02,0.0,-0.28,-1.000000,-0.010769
2007611,KXNFLRSHYDS-26FEB08SEANE-NETHENDERSON32-30,195.03,0.14,197.0,1.83,0.009376,0.009289
2007612,KXNFLRSHYDS-26FEB08SEANE-SEAKWALKER9-70,0.27,0.02,0.0,-0.29,-1.000000,-0.010741
2007613,KXNFLPASSYDS-26FEB08SEANE-NEDMAYE10-200,0.12,0.01,0.0,-0.13,-1.000000,-0.010833
2007614,KXNFLRSHYDS-26FEB08SEANE-NETHENDERSON32-30,62.37,0.05,63.0,0.58,0.009292,0.009206

# Analysis


### Market Analysis

- Start Date: First trade placed for each series or series threshold.

- End Date: Last trade placed for each series or series threshold.

- $n$ Trades: Number of trades placed for each series or series threshold.

- $n$ Markets: Number of unique markets (tickers) included within each series or series threshold.

- Contract Volume: Total number of contracts transacted on a series or series threshold basis.

- Average Taker Trade Size: Average trade size of a taker in dollars on a series or series threshold basis.

- Median Taker Trade Size: Median trade size of a taker in dollars on a series or series threshold basis.

- Trades per Market: $n$ trades divided by $n$ markets.

- Total Taker PnL: Summation of a taker's profit and loss across all trades; where, profit and loss for a single trade is defined as $$ \text{contracts} \times \text{outcome (1 if taker's side wins, else 0)} - \text{contracts} \times \text{price paid} - \text{taker fees} $$

- Taker Net Return (%): Total taker PnL divided by total taker capital at risk (dollar amount paid plus fees), expressed as a percentage. Represents the aggregate, dollar-weighted return across all taker trades in the series or series threshold.

- Taker Win Rate (%): Percentage of taker trades with positive PnL.

- Taker Winning Trades Average Return (%): Average return of trades where a taker profited (i.e. PnL > 0).

- Taker Losing Trades Average Return (%): Average return of trades where a taker did not profit (i.e. PnL $\leq$ 0).

- Total Maker PnL: Summation of a maker's profit and loss across all trades; where, profit and loss for a single trade is defined as $$ \text{contracts} \times \text{outcome (1 if maker's side wins, else 0)} - \text{contracts} \times \text{price paid} - \text{maker fees} $$

- Maker Net Return (%): Total maker PnL divided by total maker capital at risk (dollar amount paid plus fees), expressed as a percentage. Represents the aggregate, dollar-weighted return across all maker trades in the series or series threshold.

- Maker Win Rate (%): Percentage of maker trades with positive PnL.

- Maker Winning Trades Average Return (%): Average return of trades where a maker profited (i.e. PnL > 0).

- Maker Losing Trades Average Return (%): Average return of trades where a maker did not profit (i.e. PnL $\leq$ 0).

- Maker Fee % of Edge: Total maker fees paid, as a percentage of the maker's gross edge (maker revenue less maker dollar cost, before fees). Represents how much of the maker's raw trading edge is given back in fees.


### Pre-Game Implied Outcome Probability vs. Hit Rate

- <span style="color:#E29A4A; font-weight: bold; font-style: normal;">Pre-Game Market Implied Probability</span>:

    - Seeks to represent how likely the market believes the outcome to be.

    - Let $T_{pg,k} = \{(p_i, c_i)\}_{i=1}^{n}$ be the set of all observed pre-game trades for the $k^{th}$ market, where $p_i$ is the 'Yes' price and $c_i$ is the contract quantity transacted for trade $i$. The contract-weighted average pre-game 'Yes' price by market is then defined as: $$ \frac{\sum_{i=1}^{n} p_i \cdot c_i}{\sum_{i=1}^{n} c_i} $$

    - Then, the pre-game market implied probability for a series with $m$ markets can be defined: $$ \frac{1}{m} \sum_{k=1}^{m} \frac{\sum_{i=1}^{n_k} p_{i,k} \cdot c_{i,k}}{\sum_{i=1}^{n_k} c_{i,k}} $$

- <span style="color:#9096ED; font-weight: bold; font-style: normal;">Hit Rate</span>:
    - Let $G = \{g_1, \dots, g_m\}$ be the set of all finalized markets in the series, and let $y_k \in \{0, 1\}$ indicate whether market $k$ resolved 'Yes'. The hit rate is then defined as: $$ \frac{1}{m} \sum_{k=1}^{m} y_k $$


### Multivariable Regression Analysis

- **Dependent Variable(s)**

    - _Maker profit and loss per contract (maker_pnl_per_contract)_: Defined as maker revenue less the maker's dollar position size and maker fees paid on the position, divided by total contracts. Seeks to avoid extreme returns to reduce outliers, and to normalize by position size to reduce heteroskedasticity.

    - _Taker profit and loss per contract (taker_pnl_per_contract)_: Defined as taker revenue less the taker's dollar position size and taker fees paid on the position, divided by total contracts. Seeks to avoid extreme returns to reduce outliers, and to normalize by position size to reduce heteroskedasticity.

- **Independent Variables**

    - <span style="color:#5A99E0"><em>Market completion percentage (market_completion_pct)</em></span>: Defined as the number of trades placed prior to this trade, divided by the total number of trades the market will ever have. A variable seeking to understand the effect market lifecycle stage (maturity) has on profitability, independent of the market's overall size.

    - <span style="color:#5A99E0"><em>Post kickoff dummy (is_post_kickoff_dummy)</em></span>: Defined as $1$ when a trade is placed after game start time and $0$ otherwise. A dummy variable seeking to incorporate pre-game and in-game/post-kickoff dynamics into market lifecycle stage (maturity).

    - <span style="color:#FF6B6B"><em>Number of trades per market (log_n_trades_in_market)</em></span>: Defined as the total number of trades in each market (ticker). A variable seeking to understand the effect market size has on profitability. *Note, a log transformation was applied to reduce a long right tail.*

    - <span style="color:#50E3C2"><em>Trade size (log_count_fp)</em></span>: Defined as the number of contracts. A variable seeking to understand whether larger trades signal a more sophisticated trader. In other words, how does trade size measured by contract count affect profitability. *Note, a log transformation was applied to reduce a long right tail.*

    - <span style="color:#FDFD96"><em>Outcome side dummy (maker_outcome_side_dummy/taker_outcome_side_dummy)</em></span>: $1$ if a trade is taken on the 'yes' side, $0$ if 'no'. A dummy variable, specified by maker/taker, which measures the effect of side on profitability.

In [39]:
# Create 'prop' data frames

prop_dfs = {
    name: kalshi_df[kalshi_df['series'] == ticker].reset_index(drop=True).copy()
    for name, ticker in SERIES_TICKERS.items()
}

anytime_td_df      = prop_dfs['anytime_td']
two_plus_tds_df    = prop_dfs['two_plus_tds']
first_td_df        = prop_dfs['first_td']
rushing_yards_df   = prop_dfs['rushing_yards']
receiving_yards_df = prop_dfs['receiving_yards']
passing_yards_df   = prop_dfs['passing_yards']
passing_tds_df     = prop_dfs['passing_tds']
receptions_df      = prop_dfs['receptions']

### Analysis - **All** Prop Markets for a NFL Game

In [40]:
# Market Analysis

market_analytics_df = market_analysis(
    df                = kalshi_df,
    n_req_trades      = 500, 
    series_thresholds = False  
)

market_analytics_df.melt()

                   variable                             value
0                start_date  2025-09-04 09:53:05.465938+00:00
1                  end_date  2026-02-09 03:25:36.022952+00:00
2                  n_trades                           2007615
3                 n_markets                             33598
4           contract_volume                       289992054.0
5      avg_taker_trade_size                         49.337923
6   median_taker_trade_size                              9.24
7         trades_per_market                         59.754003
8           total_taker_pnl                       -9369225.91
9         taker_pct_net_ret                         -9.188508
10        taker_pct_winning                         32.201343
11    taker_win_avg_pct_ret                        149.066366
12   taker_loss_avg_pct_ret                            -100.0
13          total_maker_pnl                        5717382.71
14        maker_pct_net_ret                           2.98282
15        maker_pct_winning                         67.798657
16    maker_win_avg_pct_ret                         61.873656
17   maker_loss_avg_pct_ret                            -100.0
18    maker_fee_pct_of_edge                         11.413323

In [41]:
# Comparison Analysis
# Note, hover over bars for t-test

graph_comparison(
    df           = kalshi_df,
    graph_title  = "All NFL",
    n_req_trades = 500,
    ci           = 0.95,
)

In [42]:
# Regression Analysis: Maker PnL
# Note, hover for regression details

graph_regression(
    df           = kalshi_df,
    graph_title  = "All NFL",
    side         = 'maker',
    n_req_trades = 500,
    show_const   = False
)

In [43]:
# Regression Analysis: Taker PnL
# Note, hover for regression details

graph_regression(
    df           = kalshi_df,
    graph_title  = "All NFL",
    side         = 'taker',
    n_req_trades = 500,
    show_const   = False
)

### Analysis - **Anytime Touchdown** in a NFL Game

In [44]:
# Market Analysis

market_analytics_df = market_analysis(
    df           = anytime_td_df,
    n_req_trades = 500,
    series_thresholds = False 
)

market_analytics_df.melt()

                   variable                             value
0                start_date  2025-09-04 10:05:28.893598+00:00
1                  end_date  2026-02-09 03:25:16.945587+00:00
2                  n_trades                            886443
3                 n_markets                              5010
4           contract_volume                       125579440.0
5      avg_taker_trade_size                         49.787663
6   median_taker_trade_size                              9.26
7         trades_per_market                        176.934731
8           total_taker_pnl                       -5384843.48
9         taker_pct_net_ret                        -11.842729
10        taker_pct_winning                         29.273287
11    taker_win_avg_pct_ret                        167.519357
12   taker_loss_avg_pct_ret                            -100.0
13          total_maker_pnl                        3711794.76
14        maker_pct_net_ret                          4.538597
15        maker_pct_winning                         70.726713
16    maker_win_avg_pct_ret                         57.149254
17   maker_loss_avg_pct_ret                            -100.0
18    maker_fee_pct_of_edge                          8.331554

In [45]:
# Comparison Analysis
# Note, hover over bars for t-test

graph_comparison(
    df           = anytime_td_df,
    graph_title  = "Anytime Touchdown",
    n_req_trades = 500,
    ci           = 0.95,
)

In [46]:
# Regression Analysis: Maker PnL
# Note, hover for regression details

graph_regression(
    df           = anytime_td_df,
    graph_title  = "Anytime Touchdown",
    side         = 'maker',
    n_req_trades = 500,
    show_const   = False
)

In [47]:
# Regression Analysis: Taker PnL
# Note, hover for regression details

graph_regression(
    df           = anytime_td_df,
    graph_title  = "Anytime Touchdown",
    side         = 'taker',
    n_req_trades = 500,
    show_const   = False
)

### Analysis - **2+ Touchdowns** in a NFL Game

In [48]:
# Market Analysis

market_analytics_df = market_analysis(
    df           = two_plus_tds_df,
    n_req_trades = 500,   
)

market_analytics_df.melt()

                   variable                             value
0                start_date  2025-09-04 12:59:16.820615+00:00
1                  end_date  2026-02-09 03:22:58.232150+00:00
2                  n_trades                            161993
3                 n_markets                              1952
4           contract_volume                        30407115.0
5      avg_taker_trade_size                         37.428221
6   median_taker_trade_size                               6.0
7         trades_per_market                         82.988217
8           total_taker_pnl                       -1029137.18
9         taker_pct_net_ret                        -16.440492
10        taker_pct_winning                         21.813288
11    taker_win_avg_pct_ret                        212.276202
12   taker_loss_avg_pct_ret                            -100.0
13          total_maker_pnl                         782661.08
14        maker_pct_net_ret                           3.20844
15        maker_pct_winning                         78.186712
16    maker_win_avg_pct_ret                         28.294139
17   maker_loss_avg_pct_ret                            -100.0
18    maker_fee_pct_of_edge                          5.983932

In [49]:
# Comparison Analysis
# Note, hover over bars for t-test

graph_comparison(
    df           = two_plus_tds_df,
    graph_title  = "2+ Touchdowns",
    n_req_trades = 500,
    ci           = 0.95,
)

In [50]:
# Regression Analysis: Maker PnL
# Note, hover for regression details

graph_regression(
    df           = two_plus_tds_df,
    graph_title  = "2+ Touchdowns",
    side         = 'maker',
    n_req_trades = 500,
    show_const   = False
)

In [51]:
# Regression Analysis: Taker PnL
# Note, hover for regression details

graph_regression(
    df           = two_plus_tds_df,
    graph_title  = "2+ Touchdowns",
    side         = 'taker',
    n_req_trades = 500,
    show_const   = False
)

### Analysis - **First Touchdown** in a NFL Game

In [52]:
# Market Analysis

market_analytics_df = market_analysis(
    df           = first_td_df,
    n_req_trades = 500,   
)

market_analytics_df.melt()

                   variable                             value
0                start_date  2025-09-04 09:53:05.465938+00:00
1                  end_date  2026-02-09 02:29:35.056681+00:00
2                  n_trades                            280954
3                 n_markets                              4536
4           contract_volume                        46275290.0
5      avg_taker_trade_size                         23.478055
6   median_taker_trade_size                              4.68
7         trades_per_market                         61.938713
8           total_taker_pnl                        -851777.53
9         taker_pct_net_ret                        -12.515808
10        taker_pct_winning                         10.243314
11    taker_win_avg_pct_ret                        553.963717
12   taker_loss_avg_pct_ret                            -100.0
13          total_maker_pnl                         589015.16
14        maker_pct_net_ret                          1.482454
15        maker_pct_winning                         89.756686
16    maker_win_avg_pct_ret                         16.493403
17   maker_loss_avg_pct_ret                            -100.0
18    maker_fee_pct_of_edge                          8.312714

In [53]:
# Comparison Analysis
# Note, hover over bars for t-test

graph_comparison(
    df           = first_td_df,
    graph_title  = "First Touchdown",
    n_req_trades = 500,
    ci           = 0.95,
)

In [54]:
# Regression Analysis: Maker PnL
# Note, hover for regression details

graph_regression(
    df           = first_td_df,
    graph_title  = "First Touchdown",
    side         = 'maker',
    n_req_trades = 500,
    show_const   = False
)

In [55]:
# Regression Analysis: Taker PnL
# Note, hover for regression details

graph_regression(
    df           = first_td_df,
    graph_title  = "First Touchdown",
    side         = 'taker',
    n_req_trades = 500,
    show_const   = False
)

### Analysis - **Rushing Yards** in a NFL Game

In [56]:
# Market Analysis

market_analytics_df = market_analysis(
    df                = rushing_yards_df,
    n_req_trades      = 500,   
    series_thresholds = True
)

market_analytics_df.sort_values(by = ['total_maker_pnl', 'maker_pct_net_ret', 'n_markets'], ascending = False)

Invalid Series Threshold: [2, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 18, 19, 21, 22, 23, 24, 25, 26, 27, 28, 29, 31, 32, 33, 34, 35, 36, 37, 38, 39, 41, 42, 44, 46, 47, 48, 49, 51, 52, 53, 54, 55, 56, 57, 58, 59, 61, 62, 63, 64, 65, 66, 67, 68, 69, 71, 72, 73, 74, 75, 76, 77, 78, 79, 81, 82, 83, 84, 85, 86, 88, 89, 91, 98, 125, 130] do not have 500 required trades.

,series_threshold,start_date,end_date,n_trades,n_markets,contract_volume,avg_taker_trade_size,median_taker_trade_size,trades_per_market,total_taker_pnl,taker_pct_net_ret,taker_pct_winning,taker_win_avg_pct_ret,taker_loss_avg_pct_ret,total_maker_pnl,maker_pct_net_ret,maker_pct_winning,maker_win_avg_pct_ret,maker_loss_avg_pct_ret,maker_fee_pct_of_edge
6,50,2025-10-06 22:42:19.436342+00:00,2026-02-09 03:24:44.593522+00:00,26373,505,3924963.0,76.816126,13.020,52.223762,-375289.52,-18.057641,41.917871,73.298627,-100.0,309667.81,16.193490,58.082129,115.492174,-100.0,4.090404
5,40,2025-10-06 22:18:26.107057+00:00,2026-02-09 03:24:19.959858+00:00,23468,576,3330398.0,71.611657,11.800,40.743056,-174393.18,-10.111794,41.618374,94.624337,-100.0,119215.36,7.177650,58.381626,120.730652,-100.0,8.524116
7,60,2025-10-06 22:36:15.766195+00:00,2026-02-09 03:25:19.255181+00:00,23332,444,3298601.0,72.585261,13.000,52.549550,-177354.22,-10.190246,48.782788,83.850279,-100.0,118673.38,7.339786,51.217212,122.344014,-100.0,9.050222
8,70,2025-10-06 22:24:19.244556+00:00,2026-02-09 03:25:32.751520+00:00,19282,343,2289553.0,60.598540,10.260,56.215743,-130348.73,-10.845144,49.719946,84.016084,-100.0,88462.75,7.831818,50.280054,120.109362,-100.0,8.708162
4,30,2025-10-06 22:33:44.289461+00:00,2026-02-09 03:25:36.022952+00:00,24529,549,3096247.0,63.512276,9.620,44.679417,-90411.28,-5.655975,46.915895,102.057956,-100.0,39542.68,2.553437,53.084105,110.130842,-100.0,20.588449
0,1,2025-11-16 05:49:33.102518+00:00,2025-12-23 04:16:21.793101+00:00,958,24,78349.0,38.364436,9.360,39.916667,-10216.89,-26.926311,34.446764,97.652741,-100.0,8724.56,20.823611,65.553236,105.333774,-100.0,3.341078
2,17,2025-11-15 06:20:03.774430+00:00,2025-12-29 04:35:47.299279+00:00,1132,11,106966.0,50.903339,11.595,102.909091,13321.99,22.440434,66.961131,75.373526,-100.0,-15505.41,-31.145737,33.038869,185.470038,-100.0,-2.920529
13,120,2025-10-26 02:07:17.310778+00:00,2026-01-05 04:27:06.142083+00:00,512,11,77781.0,47.755996,9.640,46.545455,19718.41,78.174479,60.546875,136.446920,-100.0,-20686.21,-38.647602,39.453125,45.965880,-100.0,-0.953007
1,10,2025-10-07 01:00:54.509583+00:00,2026-02-09 03:24:36.589218+00:00,17723,368,2271646.0,68.515405,9.310,48.160326,-11008.89,-0.886786,52.513683,85.428865,-100.0,-22985.29,-2.159859,47.486317,123.262111,-100.0,-42.504842
12,110,2025-10-12 16:34:48.360043+00:00,2026-02-09 03:24:53.081510+00:00,2646,46,356502.0,59.041712,12.400,57.521739,24969.13,15.536774,47.127740,128.844441,-100.0,-30586.29,-15.186137,52.872260,116.959915,-100.0,-3.842045
3,20,2025-10-06 22:46:11.813489+00:00,2026-02-09 03:25:10.354693+00:00,33164,483,3319427.0,48.475926,9.345,68.662526,-16672.93,-1.010902,47.988783,85.728122,-100.0,-35528.36,-2.062825,52.011217,99.668311,-100.0,-42.202288
9,80,2025-10-06 22:30:36.900242+00:00,2026-02-09 03:20:56.413019+00:00,13862,288,2050553.0,72.283515,13.830,48.131944,33737.32,3.273540,47.215409,95.209337,-100.0,-69558.61,-6.588439,52.784591,102.325723,-100.0,-11.561685
10,90,2025-10-06 22:42:38.691402+00:00,2026-02-09 03:24:27.986666+00:00,7744,192,1256935.0,74.678456,14.040,40.333333,55972.20,9.386304,48.308368,114.017592,-100.0,-78512.19,-11.492551,51.691632,94.068899,-100.0,-6.126179
11,100,2025-10-06 22:29:22.715507+00:00,2026-02-09 03:24:49.406808+00:00,6326,113,945912.0,63.723135,14.050,55.982301,81798.95,19.659899,50.158078,133.273981,-100.0,-98020.27,-17.950350,49.841922,78.750301,-100.0,-3.444430

In [57]:
# Comparison Analysis
# Note, hover over bars for t-test

graph_comparison_by_threshold(
    df            = rushing_yards_df,
    graph_title   = "Rushing Yard",
    n_req_trades  = 500,
    n_req_markets = 10,
    ci            = 0.95,
)

In [58]:
# Regression Analysis: Maker PnL
# Note, hover for regression details

valid_series_thresholds = set({30, 40, 50, 60, 70})     # Series thresholds chosen where maker PnL statistics are favorable
valid_rushing_yards_df = rushing_yards_df[rushing_yards_df['series_threshold'].isin(valid_series_thresholds)].copy()

graph_regression_by_threshold(
    df          = valid_rushing_yards_df,
    side        = 'maker',
    graph_title = 'Rushing Yards',
)

In [59]:
# Regression Analysis: Taker PnL
# Note, hover for regression details

graph_regression_by_threshold(
    df          = valid_rushing_yards_df,
    side        = 'taker',
    graph_title = 'Rushing Yards',
)

### Analysis - **Receiving Yards** in a NFL Game

In [60]:
# Market Analysis

market_analytics_df = market_analysis(
    df                = receiving_yards_df,
    n_req_trades      = 500,   
    series_thresholds = True
)

market_analytics_df.sort_values(by = ['total_maker_pnl', 'maker_pct_net_ret', 'n_markets'], ascending = False)

Invalid Series Threshold: [5, 6, 7, 8, 9, 11, 12, 13, 14, 16, 18, 19, 21, 22, 23, 24, 25, 26, 27, 28, 29, 31, 32, 33, 34, 35, 36, 37, 38, 39, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51, 52, 53, 54, 55, 56, 57, 58, 59, 61, 62, 63, 64, 65, 66, 67, 68, 69, 71, 72, 73, 74, 75, 76, 77, 78, 79, 81, 83, 85, 86, 87, 88, 89, 91, 92, 93, 95, 97, 98, 106, 125, 130] do not have 500 required trades.

,series_threshold,start_date,end_date,n_trades,n_markets,contract_volume,avg_taker_trade_size,median_taker_trade_size,trades_per_market,total_taker_pnl,taker_pct_net_ret,taker_pct_winning,taker_win_avg_pct_ret,taker_loss_avg_pct_ret,total_maker_pnl,maker_pct_net_ret,maker_pct_winning,maker_win_avg_pct_ret,maker_loss_avg_pct_ret,maker_fee_pct_of_edge
5,40,2025-10-06 22:13:15.599604+00:00,2026-02-09 03:25:29.011357+00:00,32827,1397,4493082.0,61.462899,12.88,23.498210,-317943.67,-15.300357,42.072075,97.612210,-100.0,242350.84,9.730386,57.927925,107.146295,-100.0,5.909321
7,60,2025-10-06 22:23:14.058057+00:00,2026-02-09 03:25:26.072785+00:00,17296,804,2517843.0,67.479613,14.26,21.512438,-188070.35,-15.633896,40.980574,103.220760,-100.0,143205.37,10.531800,59.019426,96.715555,-100.0,5.929763
6,50,2025-10-06 22:32:24.920180+00:00,2026-02-09 03:25:07.456588+00:00,24833,1031,3293845.0,60.126764,14.06,24.086324,-160564.08,-10.436268,43.273064,98.404346,-100.0,103726.91,5.723931,56.726936,106.647998,-100.0,9.937327
9,80,2025-10-06 22:44:12.464699+00:00,2026-02-09 02:57:18.458324+00:00,8696,338,1026921.0,55.656089,13.20,25.727811,-84804.52,-16.995114,42.640294,82.295510,-100.0,66010.17,12.073813,57.359706,109.525638,-100.0,5.424610
8,70,2025-10-06 22:30:18.587370+00:00,2026-02-09 03:19:28.109656+00:00,9546,523,1256446.0,60.140277,14.08,18.252390,-67197.15,-11.347704,42.384245,99.395925,-100.0,44577.84,6.489712,57.615755,98.562796,-100.0,9.267535
10,90,2025-10-12 02:49:43.846891+00:00,2026-02-09 03:16:57.184331+00:00,8396,179,854874.0,49.690392,9.69,46.905028,-40336.16,-9.378732,38.434969,89.577100,-100.0,24203.89,5.489343,61.565031,111.067162,-100.0,11.843297
11,100,2025-10-11 19:30:30.623063+00:00,2026-02-09 03:14:32.237700+00:00,5169,96,578666.0,53.389466,12.48,53.843750,-34860.29,-12.240774,38.305281,96.669132,-100.0,23817.34,7.810996,61.694719,91.556852,-100.0,8.543112
0,10,2025-10-06 23:15:16.765083+00:00,2026-02-09 03:25:28.313872+00:00,16443,900,2445979.0,84.064420,10.00,18.270000,-62220.06,-4.399907,58.152405,57.991798,-100.0,22339.83,2.084450,41.847595,159.409294,-100.0,26.439309
12,110,2025-10-11 19:15:40.101172+00:00,2026-02-09 03:14:18.898131+00:00,1857,47,228967.0,54.090894,9.50,39.510638,-26176.66,-25.191506,37.695207,97.168763,-100.0,21839.70,16.878540,62.304793,73.067293,-100.0,3.844046
13,120,2025-11-03 01:17:11.523732+00:00,2026-02-09 02:21:34.543811+00:00,1607,26,175191.0,48.681966,9.50,61.807692,-20685.84,-25.629568,33.789670,94.664638,-100.0,17580.65,18.015665,66.210330,71.020200,-100.0,3.439736
2,17,2025-11-13 05:04:28.275897+00:00,2025-12-28 21:05:22.595544+00:00,568,30,65442.0,63.069665,12.56,18.933333,-10231.49,-27.832087,49.823944,82.921972,-100.0,9056.86,30.336016,50.176056,208.807970,-100.0,2.547030
4,30,2025-10-06 22:13:28.029309+00:00,2026-02-09 03:25:21.049334+00:00,34471,1394,4366884.0,60.642796,11.20,24.728121,-70436.16,-3.278430,48.722114,92.251151,-100.0,-2265.07,-0.098863,51.277886,112.128808,-100.0,118.293514
1,15,2025-11-14 00:02:00.918537+00:00,2025-12-28 23:53:44.081833+00:00,671,37,63993.0,49.537526,10.60,18.135135,8387.00,24.560736,61.251863,85.068499,-100.0,-9524.99,-30.742643,38.748137,143.833737,-100.0,-2.470813
3,20,2025-10-06 22:14:50.501341+00:00,2026-02-09 03:25:26.143456+00:00,36422,1256,4367921.0,58.352936,9.49,28.998408,245455.39,11.233658,55.908517,96.617956,-100.0,-320185.75,-14.182247,44.091483,106.349080,-100.0,-4.936141

In [61]:
# Comparison Analysis
# Note, hover over bars for t-test

graph_comparison_by_threshold(
    df            = receiving_yards_df,
    graph_title   = "Receiving Yard",
    n_req_trades  = 500,
    n_req_markets = 10,
    ci            = 0.95,
)

In [62]:
# Regression Analysis: Maker PnL
# Note, hover for regression details

valid_series_thresholds = set({40, 50, 60, 70, 80})     # Series thresholds chosen where maker PnL statistics are favorable
valid_receiving_yards_df = receiving_yards_df[receiving_yards_df['series_threshold'].isin(valid_series_thresholds)].copy()

graph_regression_by_threshold(
    df          = valid_receiving_yards_df,
    side        = 'maker',
    graph_title = 'Receiving Yards',
)

In [63]:
# Regression Analysis: Taker PnL
# Note, hover for regression details

graph_regression_by_threshold(
    df          = valid_receiving_yards_df,
    side        = 'taker',
    graph_title = 'Receiving Yards',
)

### Analysis - **Passing Yards** in a NFL Game

In [64]:
# Market Analysis

market_analytics_df = market_analysis(
    df                = passing_yards_df,
    n_req_trades      = 500, 
    series_thresholds = True
)

market_analytics_df.sort_values(by = ['total_maker_pnl', 'maker_pct_net_ret', 'n_markets'], ascending = False)

Invalid Series Threshold: [134, 139, 153, 156, 159, 163, 164, 170, 171, 173, 176, 178, 180, 181, 184, 185, 186, 187, 188, 190, 191, 192, 193, 194, 195, 196, 197, 198, 201, 202, 203, 204, 205, 206, 207, 208, 210, 211, 212, 213, 214, 215, 216, 217, 219, 220, 221, 222, 224, 227, 228, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 263, 264, 265, 266, 267, 268, 270, 271, 272, 283] do not have 500 required trades.

,series_threshold,start_date,end_date,n_trades,n_markets,contract_volume,avg_taker_trade_size,median_taker_trade_size,trades_per_market,total_taker_pnl,taker_pct_net_ret,taker_pct_winning,taker_win_avg_pct_ret,taker_loss_avg_pct_ret,total_maker_pnl,maker_pct_net_ret,maker_pct_winning,maker_win_avg_pct_ret,maker_loss_avg_pct_ret,maker_fee_pct_of_edge
1,175,2025-10-06 23:10:03.421116+00:00,2026-02-09 03:24:56.000303+00:00,21661,391,3065535.0,77.149980,10.000,55.398977,-92516.85,-5.424710,57.435021,57.935749,-100.0,49522.15,3.529585,42.564979,166.753114,-100.0,14.898288
2,199,2025-12-07 09:57:25.727075+00:00,2026-01-13 04:15:21.168404+00:00,916,3,80006.0,49.510055,10.440,305.333333,-36557.18,-78.327560,20.414847,76.076429,-100.0,34902.33,99.753234,79.585153,133.554988,-100.0,0.947548
9,229,2025-11-26 08:14:34.075280+00:00,2026-02-09 03:17:28.368213+00:00,1419,9,120062.0,44.729965,9.180,157.666667,-32281.86,-49.356220,20.789288,74.021093,-100.0,29858.80,52.311175,79.210712,113.381946,-100.0,1.611384
7,225,2025-10-06 23:12:46.797345+00:00,2026-02-09 03:25:03.786314+00:00,23311,386,3364105.0,72.058075,14.210,60.391192,-88672.84,-5.131017,51.529321,80.011470,-100.0,28048.62,1.653268,48.470679,113.334575,-100.0,30.306698
14,350,2025-10-06 23:04:32.840031+00:00,2026-02-09 02:48:25.762071+00:00,4695,345,590915.0,36.006961,4.800,13.608696,-26670.49,-15.422397,36.528222,133.024501,-100.0,21798.40,5.155070,63.471778,239.775410,-100.0,4.349688
8,226,2025-11-16 18:21:32.526465+00:00,2026-02-09 03:23:57.381236+00:00,797,7,132367.0,81.795822,11.500,113.857143,-24191.01,-35.961062,58.343789,113.789743,-100.0,21589.60,31.890857,41.656211,186.773514,-100.0,2.363710
11,275,2025-10-06 23:06:02.542735+00:00,2026-02-09 03:25:16.441540+00:00,10451,374,1490533.0,59.191643,12.610,27.943850,-39496.03,-6.192299,41.795044,137.214686,-100.0,15439.18,1.760926,58.204956,97.371132,-100.0,23.880656
3,200,2025-10-06 23:03:00.546020+00:00,2026-02-09 03:25:33.612056+00:00,35833,391,4421073.0,65.888374,11.050,91.644501,-82449.65,-3.406479,55.892613,65.140151,-100.0,8060.66,0.388450,44.107387,138.688526,-100.0,65.029811
13,325,2025-11-13 18:42:31.354507+00:00,2026-02-09 03:21:29.803404+00:00,2735,243,379185.0,50.884355,9.300,11.255144,-11508.13,-8.078765,39.597806,128.378130,-100.0,7395.70,3.070688,60.402194,72.187043,-100.0,10.112291
6,223,2025-11-16 14:09:40.337147+00:00,2026-01-11 21:10:20.772785+00:00,562,5,88479.0,83.447829,14.255,112.400000,7546.37,15.637672,61.032028,60.868412,-100.0,-9248.58,-22.060568,38.967972,100.535011,-100.0,-3.842889
0,158,2025-12-21 20:09:36.798636+00:00,2025-12-23 04:23:20.248405+00:00,520,1,81504.0,81.930654,14.250,520.000000,16705.04,38.219674,71.730769,60.554671,-100.0,-18087.10,-46.166353,28.269231,38.992644,-100.0,-1.561228
12,300,2025-10-06 23:02:44.878263+00:00,2026-02-09 03:24:06.026289+00:00,10938,375,1756945.0,54.927297,10.205,29.168000,-3626.21,-0.584444,35.856647,150.087432,-100.0,-20991.43,-1.807879,64.143353,66.442694,-100.0,-30.924605
5,218,2025-11-30 16:25:54.295971+00:00,2026-01-18 01:08:26.008761+00:00,601,4,93119.0,71.250549,19.040,150.250000,24852.48,56.159329,73.544093,104.645448,-100.0,-26644.53,-52.597373,26.455907,95.087310,-100.0,-1.370051
4,209,2025-12-10 15:28:38.261224+00:00,2026-01-18 23:20:17.617830+00:00,667,3,127796.0,94.587496,14.440,222.333333,34766.31,53.362100,73.163418,79.867748,-100.0,-37346.09,-57.258123,26.836582,107.937771,-100.0,-1.406397
10,250,2025-10-06 23:11:55.959251+00:00,2026-02-09 03:25:26.583681+00:00,19898,388,2924507.0,65.882807,14.040,51.283505,138734.51,10.264013,52.864610,114.989346,-100.0,-189715.05,-11.683198,47.135390,101.921901,-100.0,-5.715624

In [65]:
# Comparison Analysis
# Note, hover over bars for t-test

graph_comparison_by_threshold(
    df            = passing_yards_df,
    graph_title   = "Passing Yards",
    n_req_trades  = 500,
    n_req_markets = 10,
    ci            = 0.95,
)

In [66]:
# Regression Analysis: Maker PnL
# Note, hover for regression details

valid_series_thresholds = set({175, 225, 350})     # Series thresholds chosen where maker PnL statistics are favorable
valid_passing_yards_df = passing_yards_df[passing_yards_df['series_threshold'].isin(valid_series_thresholds)].copy()

graph_regression_by_threshold(
    df          = valid_passing_yards_df,
    side        = 'maker',
    graph_title = 'Passing Yards',
)

In [67]:
# Regression Analysis: Taker PnL
# Note, hover for regression details

valid_series_thresholds = set({175, 225, 350})     # Series thresholds chosen where maker PnL statistics are favorable
valid_passing_yards_df = passing_yards_df[passing_yards_df['series_threshold'].isin(valid_series_thresholds)].copy()

graph_regression_by_threshold(
    df          = valid_passing_yards_df,
    side        = 'taker',
    graph_title = 'Passing Yards',
)

### Analysis - **Passing Touchdowns** in a NFL Game

In [68]:
# Market Analysis

market_analytics_df = market_analysis(
    df                = passing_tds_df,
    n_req_trades      = 500,
    series_thresholds = True
)

market_analytics_df.sort_values(by = ['total_maker_pnl', 'maker_pct_net_ret', 'n_markets'], ascending = False)

,series_threshold,start_date,end_date,n_trades,n_markets,contract_volume,avg_taker_trade_size,median_taker_trade_size,trades_per_market,total_taker_pnl,taker_pct_net_ret,taker_pct_winning,taker_win_avg_pct_ret,taker_loss_avg_pct_ret,total_maker_pnl,maker_pct_net_ret,maker_pct_winning,maker_win_avg_pct_ret,maker_loss_avg_pct_ret,maker_fee_pct_of_edge
3,4,2025-11-21 03:25:29.254042+00:00,2026-02-09 03:23:18.388336+00:00,4608,170,910121.0,39.866393,5.685,27.105882,-62329.11,-32.970147,20.659722,99.189411,-100.0,55631.83,7.644138,79.340278,35.793847,-100.0,2.376903
1,2,2025-11-21 00:29:13.721015+00:00,2026-02-09 03:22:44.074553+00:00,33240,202,2933230.0,41.516832,9.400,164.554455,-58912.09,-4.134318,43.880866,104.268276,-100.0,2620.03,0.167460,56.119134,119.151375,-100.0,81.256689
0,1,2025-11-21 01:15:11.039699+00:00,2026-02-09 02:41:12.490533+00:00,6901,180,777158.0,69.324095,9.180,38.338889,25409.99,5.211643,71.134618,47.569718,-100.0,-36883.50,-12.250826,28.865382,196.365442,-100.0,-6.703269
2,3,2025-11-21 01:44:36.573035+00:00,2026-02-09 03:24:41.020112+00:00,12648,186,1611071.0,38.503525,9.280,68.000000,52314.05,10.350610,32.779886,223.648826,-100.0,-75397.42,-6.679819,67.220114,55.700044,-100.0,-6.581717

In [69]:
# Comparison Analysis
# Note, hover over bars for t-test

graph_comparison_by_threshold(
    df            = passing_tds_df,
    graph_title   = "Passing Touchdowns",
    n_req_trades  = 500,
    n_req_markets = 10,
    ci            = 0.95
)

In [70]:
# Regression Analysis: Maker PnL
# Note, hover for regression details

graph_regression_by_threshold(
    df          = passing_tds_df,   # All series thresholds are considered
    side        = 'maker',
    graph_title = 'Passing Touchdowns',
)

In [71]:
# Regression Analysis: Taker PnL
# Note, hover for regression details

graph_regression_by_threshold(
    df          = passing_tds_df,   # All series thresholds are considered
    side        = 'taker',
    graph_title = 'Passing Touchdowns',
)

### Analysis - **Receptions** in a NFL Game

In [72]:
# Market Analysis

market_analytics_df = market_analysis(
    df                = receptions_df,
    n_req_trades      = 500,
    series_thresholds = True
)

market_analytics_df.sort_values(by = ['total_maker_pnl', 'maker_pct_net_ret', 'n_markets'], ascending = False)

Invalid Series Threshold: [10, 11] do not have 500 required trades.

,series_threshold,start_date,end_date,n_trades,n_markets,contract_volume,avg_taker_trade_size,median_taker_trade_size,trades_per_market,total_taker_pnl,taker_pct_net_ret,taker_pct_winning,taker_win_avg_pct_ret,taker_loss_avg_pct_ret,total_maker_pnl,maker_pct_net_ret,maker_pct_winning,maker_win_avg_pct_ret,maker_loss_avg_pct_ret,maker_fee_pct_of_edge
6,7,2025-10-27 19:14:57.701607+00:00,2026-02-09 02:42:30.012577+00:00,3027,265,403364.0,65.651216,9.54,11.422642,-57842.68,-28.325835,34.819954,86.588855,-100.0,50982.65,24.746535,65.180046,115.815260,-100.0,2.638404
5,6,2025-10-27 20:47:59.611253+00:00,2026-02-09 02:42:35.843433+00:00,4497,477,506251.0,52.241995,9.44,9.427673,-45580.51,-18.885216,36.980209,96.413202,-100.0,37533.47,13.751419,63.019791,137.569051,-100.0,4.146818
3,4,2025-10-27 20:43:13.500948+00:00,2026-02-09 03:24:34.275686+00:00,9675,955,1142092.0,54.707005,9.36,10.130890,-43887.77,-8.054845,43.545220,105.512921,-100.0,24384.69,3.953847,56.454780,110.452080,-100.0,13.884526
4,5,2025-10-27 20:13:20.624829+00:00,2026-02-09 03:25:09.729964+00:00,8599,856,1045385.0,52.710477,9.35,10.045561,-32258.43,-6.914154,39.341784,112.554717,-100.0,15599.68,2.619649,60.658216,117.686260,-100.0,17.720560
2,3,2025-10-27 19:42:25.125953+00:00,2026-02-09 03:25:02.032062+00:00,11396,977,1281709.0,55.629681,9.36,11.664278,-35216.89,-5.404622,43.743419,90.077995,-100.0,13108.24,2.009817,56.256581,114.193642,-100.0,25.376526
0,1,2025-10-27 20:07:17.873576+00:00,2026-02-09 03:03:37.138876+00:00,2883,412,257656.0,53.198463,4.55,6.997573,-1708.59,-1.101480,75.858481,52.437470,-100.0,-487.08,-0.465064,24.141519,152.342984,-100.0,-1187.549564
8,9,2025-11-02 13:34:59.064912+00:00,2026-02-09 02:09:39.811342+00:00,554,51,70429.0,59.892094,9.45,10.862745,-171.23,-0.501402,36.101083,108.853339,-100.0,-1043.38,-2.782838,63.898917,268.753162,-100.0,-30.621698
7,8,2025-10-27 22:15:44.555103+00:00,2026-02-09 02:15:39.693293+00:00,1275,118,138335.0,52.564957,9.60,10.805085,2384.65,3.449448,39.450980,85.790881,-100.0,-5028.32,-6.998619,60.549020,96.470805,-100.0,-11.847818
1,2,2025-10-27 20:22:31.136549+00:00,2026-02-09 03:25:24.053868+00:00,10727,842,1082975.0,51.135594,9.25,12.739905,41955.45,7.456022,56.642118,83.831743,-100.0,-59715.92,-11.098996,43.357882,160.294126,-100.0,-6.389584

In [73]:
# Comparison Analysis
# Note, hover over bars for t-test

graph_comparison_by_threshold(
    df            = receptions_df,
    graph_title   = "Receptions",
    n_req_trades  = 500,
    n_req_markets = 10,
    ci            = 0.95,
)

In [74]:
# Regression Analysis: Maker PnL
# Note, hover for regression details

valid_series_thresholds = set({4, 5, 6, 7})     # Series thresholds chosen where maker PnL statistics are favorable
valid_receptions_df = receptions_df[receptions_df['series_threshold'].isin(valid_series_thresholds)].copy()

graph_regression_by_threshold(
    df          = valid_receptions_df,
    side        = 'maker',
    graph_title = 'Receptions',
)

In [75]:
# Regression Analysis: Taker PnL
# Note, hover for regression details

graph_regression_by_threshold(
    df          = valid_receptions_df,
    side        = 'taker',
    graph_title = 'Receptions',
)